// Hand verdicts for Y2 / Y3, round 2. Every entry was judged from items generated WITH the opts below
// (tests/scripts/wrm-tagging/items.mjs; log in design/audit/runs/wrm-tagging/Y2-Y3-items.md).
//   direct:[{key,opts}]  partials:[{key,missing,opts?}]  verdict  missing  build  pre  preBuild  related  note
//   reviewed:true = the SKILL_WRM tags were re-generated and stand as they are.
export const exclude = ['addition:equal_sign']; // deals plain column addition today (build-list equal_sign_repair)
const D = (key, opts = {}) => ({ key, opts });
const P = (key, missing, opts) => ({ key, missing, ...(opts ? { opts } : {}) });
const R = (key, why) => ({ key, why });
const USD = { currency: 'usd' };
const zero = (step) => ({ rows: [{ step, start: 'zero', dir: 'up' }] });
const OK = { reviewed: true };

export const steps = {
  // ---------------- Y2 B1 place value ----------------
  'Y2.B1.S1': { direct: [D('composing:teen_compose'), D('composing:base10_build', { band: 20 })] },
  'Y2.B1.S2': { partials: [P('composing:base10_build', 'grouping loose objects into tens to count them (the skill shows ready-made tens rods)', { band: 99 })],
    pre: [R('counting:count_objects', 'Y1.B1.S2 count objects one by one, the first step of counting by tens')] },
  'Y2.B1.S3': OK, 'Y2.B1.S4': OK, 'Y2.B1.S5': OK, 'Y2.B1.S7': OK, 'Y2.B1.S8': OK,
  'Y2.B1.S6': { direct: [D('composing:number_word_form', { wordform: ['to_words', 'to_number'], range: 100 })],
    related: [R('placevalue:unit_form', 'the same number said as tens and ones before it is written in words')] },
  'Y2.B1.S9': OK, 'Y2.B1.S10': OK, 'Y2.B1.S11': OK, 'Y2.B1.S12': OK, 'Y2.B1.S13': OK, 'Y2.B1.S14': OK,
  'Y2.B1.S15': { direct: [D('multiplication:count_by_tables', { rows: [{ step: 2, start: 'zero', dir: 'up' }, { step: 5, start: 'zero', dir: 'up' }, { step: 10, start: 'zero', dir: 'up' }] })],
    why: { 'patterns:seq_2': 'items start anywhere (49, 51, 53): not the multiples of 2', 'patterns:seq_5': 'items start anywhere (49, 54, 59): not multiples of 5', 'patterns:seq_10': 'items start anywhere (23, 33, 43): not multiples of 10' },
    related: [R('patterns:seq_10', 'counting on in 10s from any number: the next idea (1.NBT.C.5)'), R('patterns:skip_count_line', 'the same count as jumps on a number line')] },
  'Y2.B1.S16': { direct: [D('multiplication:count_by_tables', zero(3))], verdict: 'full',
    note: 'count_by_tables with a row {step 3, from 0} deals 0, 3, 6 ... 33: the count_3s proposal is already built (retire it)',
    related: [R('patterns:skip_count_line', 'counting in 3s as jumps on a number line')] },
  // ---------------- Y2 B2 addition and subtraction ----------------
  'Y2.B2.S1': { direct: [D('composing:make_ten')], why: { 'composing:number_bonds': 'deals bonds of 4, 5, 6 ... within 10, not bonds TO 10: kept as a pre-skill' },
    pre: [R('composing:number_bonds', 'Y1 bonds within 10: the part-whole step before bonds to 10'), R('composing:ten_frame_build', 'numbers to 10 on a ten frame, the picture a bond to 10 is read from')] },
  'Y2.B2.S2': OK, 'Y2.B2.S3': OK, 'Y2.B2.S4': OK, 'Y2.B2.S7': OK, 'Y2.B2.S8': OK, 'Y2.B2.S10': OK, 'Y2.B2.S11': OK,
  'Y2.B2.S15': OK, 'Y2.B2.S16': OK, 'Y2.B2.S18': OK, 'Y2.B2.S21': OK,
  'Y2.B2.S5': { partials: [P('placevalue:more_less_10', 'only ±1; adding or subtracting several ones to a 2-digit number (34 + 3) without crossing a ten is not dealt', { step: 1 }),
      P('addition:number_line_add', 'within 20 only, not ones added to a 2-digit number')], build: ['one_digit_addend'] },
  'Y2.B2.S6': OK,
  'Y2.B2.S9': { partials: [P('addition:add_50_regroup', 'items mix 1-digit + 1-digit and 2-digit + 2-digit; 2-digit + 1-digit across a ten (38 + 5) is not alone on a page'),
      P('number_sense:make_a_ten', 'bridges 10 within 20 only, not a 2-digit number across the next ten')], build: ['add_next_10'] },
  'Y2.B2.S12': { partials: [P('subtraction:sub_50_regroup', 'items mix 2-digit − 2-digit with 2-digit − 1-digit; a page of 2-digit − 1-digit across a ten is not available', { band: 50 })],
    why: { 'subtraction:sub_100_regroup': 'deals 2-digit − 2-digit (66 − 17): that is Y2.B2.S18' }, build: ['one_digit_addend'],
    related: [R('subtraction:sub_100_regroup', 'the next step: 2-digit − 2-digit across a ten')] },
  'Y2.B2.S13': { direct: [D('placevalue:more_less_10', { step: 10 })] },
  'Y2.B2.S14': { partials: [P('addition:add_sub_10s', 'deals only a decade ± 10 (70 − 10); adding 20 or subtracting 30, and a 2-digit number ± tens (34 + 20), are not dealt')],
    build: ['tens_any'], pre: [R('placevalue:more_less_10', 'Y2.B2.S13 10 more, 10 less')] },
  'Y2.B2.S17': { reviewed: true, pre: [R('subtraction:sub_50_no_regroup', 'subtracting within 50 without an exchange, the smaller band first')] },
  'Y2.B2.S19': { reviewed: true, pre: [R('addition:add_100_no_regroup', 'Y2.B2.S15 adding two 2-digit numbers'), R('subtraction:sub_100_no_regroup', 'Y2.B2.S17 subtracting two 2-digit numbers'), R('addition:add_wp_20', 'one-step addition stories within 20'), R('subtraction:sub_wp_20', 'one-step subtraction stories within 20')], preOnly: true },
  'Y2.B2.S20': OK,
  // ---------------- Y2 B3 shape ----------------
  'Y2.B3.S1': OK, 'Y2.B3.S4': OK, 'Y2.B3.S5': OK, 'Y2.B3.S7': OK, 'Y2.B3.S11': OK, 'Y2.B3.S12': OK,
  'Y2.B3.S2': { direct: [D('shapes_early:count_sides_vertices_2d', { forms: [0] })] },
  'Y2.B3.S3': { direct: [D('shapes_early:shape_corners_count'), D('shapes_early:count_sides_vertices_2d', { forms: [1] })] },
  'Y2.B3.S6': { reviewed: true, preOnly: true, pre: [R('angles_lines:symmetry', 'Y2.B3.S5 lines of symmetry: find the mirror line before completing the half'), R('angles_lines:place_symmetry_lines', 'Y2.B3.S5 drawing the line of symmetry'), R('shapes_early:name_2d_shapes', 'Y2.B3.S1 naming the shape that is being completed')] },
  'Y2.B3.S8': { direct: [D('shapes_early:count_edges_faces_vertices', { forms: [0] })], verdict: 'full',
    note: 'forms [0] = faces only: the shape_faces proposal is already built (retire it). Owner question: the skill says a cylinder has 3 faces; WRM Y2 says 2 flat faces and 1 curved surface.' },
  'Y2.B3.S9': { direct: [D('shapes_early:count_edges_faces_vertices', { forms: [1] })] },
  'Y2.B3.S10': { direct: [D('shapes_early:count_edges_faces_vertices', { forms: [2] })] },
  // ---------------- Y2 B4 money (US dollars, owner answer) ----------------
  'Y2.B4.S1': { direct: [D('measurement:money_count', { currency: 'usd', kind: 'like' }), D('measurement:coin_value', USD)] },
  'Y2.B4.S2': { direct: [D('measurement:money_count', { currency: 'usd', kind: 'note' })], verdict: 'full', note: 'kind "note" counts $1, $5, $10, $20 bills: the money_uk option is built for this step' },
  'Y2.B4.S3': { direct: [D('measurement:money_count', { currency: 'usd', kind: 'both' })], verdict: 'full', note: 'kind "both": count the bills, then the coins, write both numbers' },
  'Y2.B4.S4': { partials: [P('measurement:make_change_least_coins', 'coins only and always the FEWEST coins; choosing bills and coins to make an amount (any way) is not dealt', USD)], build: ['make_amount_notes'] },
  'Y2.B4.S5': { direct: [D('measurement:equiv_coin_sets', USD)] },
  'Y2.B4.S6': { reviewed: true, note: 'money_compare has no US option (plain or QAR): plain cents are dealt' },
  'Y2.B4.S7': { partials: [P('measurement:money', 'adds whole-dollar prices only; finding the difference between two amounts is not dealt', USD)],
    why: { 'measurement:enough_money': 'asks "is there enough?" (a compare), not a calculation: kept as related' }, build: ['money_difference'],
    related: [R('measurement:enough_money', 'compare an amount with a price, the reasoning behind a difference'), R('measurement:money_change', 'the next step: change is a difference')] },
  'Y2.B4.S8': { partials: [P('measurement:equiv_coin_sets', 'checks whether coins make an amount up to $1; making exactly $1 (100 cents) in different ways is not asked', { currency: 'usd', band: 100 })], build: ['money_uk'] },
  'Y2.B4.S9': { direct: [D('measurement:money_change', { currency: 'usd', step: 100 })] },
  'Y2.B4.S10': { reviewed: true, preOnly: true, pre: [R('measurement:money', 'Y2.B4.S7 adding prices'), R('measurement:money_change', 'Y2.B4.S9 finding change'), R('addition:add_wp_100', 'one-step addition stories within 100'), R('subtraction:sub_wp_100', 'one-step subtraction stories within 100')] },
  // ---------------- Y2 B5 multiplication and division ----------------
  'Y2.B5.S1': OK, 'Y2.B5.S2': OK, 'Y2.B5.S4': OK, 'Y2.B5.S5': OK, 'Y2.B5.S7': OK, 'Y2.B5.S8': OK, 'Y2.B5.S12': OK,
  'Y2.B5.S3': { direct: [D('multiplication:arrays_groups', { forms: [1] }), D('multiplication:repeated_add_to_mult', { band: 25 })] },
  'Y2.B5.S6': { direct: [D('multiplication:arrays_groups', { forms: [0] }), D('multiplication:dot_array_mult', { band: 25 })] },
  'Y2.B5.S9': { direct: [D('multiplication:mult_facts', { constant: [2] }), D('multiplication:count_by_tables', zero(2))] },
  'Y2.B5.S10': { direct: [D('division:div_facts', { constant: [2] })] },
  'Y2.B5.S11': { direct: [D('patterns:double', { band: 20 }), D('patterns:halve', { band: 20 })] },
  'Y2.B5.S13': { direct: [D('multiplication:mult_facts', { constant: [10] }), D('multiplication:count_by_tables', zero(10))] },
  'Y2.B5.S14': { direct: [D('division:div_facts', { constant: [10] })] },
  'Y2.B5.S15': { direct: [D('multiplication:mult_facts', { constant: [5] }), D('multiplication:count_by_tables', zero(5))] },
  'Y2.B5.S16': { direct: [D('division:div_facts', { constant: [5] })] },
  'Y2.B5.S17': { direct: [D('multiplication:mult_facts', { constant: [5, 10] }), D('multiplication:mult_chart_easy', { constant: [5, 10] })] },
  // ---------------- Y2 B6 length ----------------
  'Y2.B6.S1': { reviewed: true, pre: [R('shapes_early:measure_nonstandard', 'Y1.B7.S2 measuring length with cubes and paper clips (prior learning wk W21)'), R('comparing:compare_objects', 'Y1.B7.S1 compare lengths and heights')],
    related: [R('measurement:estimate_length', 'estimating a length before measuring it'), R('measurement:length_metric', 'cm and m as units of the same length')] },
  'Y2.B6.S2': { reviewed: true, related: [R('measurement:estimate_length', 'choosing cm or m for an object'), R('measurement:reading_ruler', 'measuring on a scale (the ruler)')] },
  'Y2.B6.S3': { partials: [P('comparing:compare_objects', 'compares pictured objects; comparing lengths given in cm and m with <, > and = is not dealt'), P('shapes_early:order_objects_length', 'orders pictured objects; no lengths in cm or m')], build: ['compare_lengths'],
    related: [R('placevalue:compare', 'comparing the numbers of the measurements with <, >, =')] },
  'Y2.B6.S4': { partials: [P('shapes_early:order_objects_length', 'orders pictured objects; ordering lengths given in cm and m is not dealt')], build: ['compare_lengths'],
    related: [R('placevalue:order_least_to_greatest', 'ordering the numbers of the measurements')] },
  'Y2.B6.S5': { reviewed: true, preOnly: true, pre: [R('measurement:reading_ruler', 'Y2.B6.S1 measuring a length'), R('addition:add_wp_100', 'addition stories within 100'), R('subtraction:sub_wp_100', 'subtraction and difference stories within 100'), R('multiplication:mult_facts', 'Y2.B5 the 2, 5 and 10 times-tables ("twice as tall")'), R('patterns:halve', 'Y2.B5.S11 halving ("half as tall")')],
    related: [R('measurement:estimate_length', 'estimating lengths to check a calculation'), R('measurement:unit_conversion_word', 'measure word problems in the next years')] },
  // ---------------- Y2 B7 mass, capacity, temperature ----------------
  'Y2.B7.S1': { reviewed: true, related: [R('comparing:compare_objects', 'comparing by length and height, the same compare language')] },
  'Y2.B7.S2': { partials: [P('measurement:mass_volume_liquid', 'reads one kind of g scale (and some kg items); reading scales in grams with different steps is not dealt', { forms: [1] })], build: ['mass_scales'] },
  'Y2.B7.S3': { partials: [P('measurement:mass_volume_liquid', 'mostly grams; reading a kilogram scale is not dealt', { forms: [1] })], build: ['mass_scales'] },
  'Y2.B7.S4': { reviewed: true, preOnly: true, pre: [R('measurement:mass_volume_liquid', 'Y2.B7.S2 reading a mass in grams'), R('addition:add_wp_100', 'addition stories within 100'), R('subtraction:sub_wp_100', 'subtraction stories within 100'), R('measurement:heavier_lighter_visual', 'Y2.B7.S1 heavier and lighter')],
    related: [R('measurement:capacity', 'the same operations with capacity (Y2.B7.S8)')] },
  'Y2.B7.S5': { reviewed: true, pre: [R('comparing:compare_objects', 'compare language (more, less) from length and height')], related: [R('measurement:capacity', 'capacity units and comparing containers'), R('measurement:heavier_lighter_visual', 'comparing mass, the same compare language')] },
  'Y2.B7.S6': { direct: [D('measurement:mass_volume_liquid', { forms: [0] })] },
  'Y2.B7.S7': { partials: [P('measurement:mass_volume_liquid', 'reads millilitres only; reading a jug in litres is not dealt', { forms: [0] })], build: ['mass_scales'] },
  'Y2.B7.S8': { reviewed: true, preOnly: true, pre: [R('measurement:mass_volume_liquid', 'Y2.B7.S6 reading millilitres'), R('addition:add_wp_100', 'addition stories within 100'), R('subtraction:sub_wp_100', 'subtraction stories within 100')], related: [R('measurement:capacity', 'capacity units')] },
  'Y2.B7.S9': { direct: [D('measurement:temperature', { forms: [1] })], note: 'forms [1] reads a °C thermometer (forms [0] is °F)' },
  // ---------------- Y2 B8 fractions ----------------
  'Y2.B8.S1': OK, 'Y2.B8.S2': OK, 'Y2.B8.S9': OK, 'Y2.B8.S15': OK,
  'Y2.B8.S3': { direct: [D('shapes_early:partition_shapes', { parts: [0] })] },
  'Y2.B8.S4': { direct: [D('patterns:halve', { band: 20 })], partials: [P('fractions:shade_fraction', 'denoms [2] is the halves family: it also deals 4/8 and 5/8, not only 1/2', { denoms: [2] })],
    why: { 'fractions:fraction_of_set': 'ignores denoms in its missing-numerator items (generator bug): cannot be narrowed to halves' },
    note: 'half of an amount is dealt by halve {band 20}; a page of 1/2 of a shape needs single_fraction',
    related: [R('shapes_early:partition_shapes', 'Y2.B8.S3 recognising a half of a shape')] },
  'Y2.B8.S5': { direct: [D('shapes_early:partition_shapes', { parts: [2] })] },
  'Y2.B8.S6': { partials: [P('fractions:shade_fraction', 'the halves family (1/2, 1/4, 3/4, eighths): a page of quarters only is not available', { denoms: [2] })],
    why: { 'fractions:fraction_of_set': 'ignores denoms in missing-numerator items (bug)' }, build: ['single_fraction'] },
  'Y2.B8.S7': { direct: [D('shapes_early:partition_shapes', { parts: [1] })] },
  'Y2.B8.S8': { partials: [P('fractions:shade_fraction', 'the thirds family also deals sixths and twelfths; a page of 1/3 only is not available', { denoms: [3] })],
    why: { 'fractions:fraction_of_set': 'ignores denoms in missing-numerator items (bug)' }, build: ['single_fraction'] },
  'Y2.B8.S10': { direct: [D('fractions:identify', { denoms: [2, 3] }), D('fractions:write_fraction', { denoms: [2, 3] })] },
  'Y2.B8.S11': { direct: [D('fractions:write_fraction', { denoms: [2, 3] }), D('fractions:shade_fraction', { denoms: [2, 3] })] },
  'Y2.B8.S12': { partials: [P('fractions:equiv_frac_visual', 'the halves family deals 3/4 = 12/16 and eighths too; a page of 1/2 = 2/4 only is not available', { denoms: [2] })], build: ['single_fraction'] },
  'Y2.B8.S13': { partials: [P('shapes_early:partition_shapes', 'quarters shapes: shades 1/4, 2/4 and 3/4, not three-quarters alone', { parts: [2] }), P('fractions:identify', 'the halves family, not 3/4 alone', { denoms: [2] })],
    why: { 'fractions:write_fraction': 'deals sixths, fifths and eighths at Y2 (no single-fraction option)' }, build: ['single_fraction'] },
  'Y2.B8.S14': { partials: [P('fractions:shade_fraction', 'the halves family; a page of 3/4 of a shape or amount is not available', { denoms: [2] })],
    why: { 'fractions:fraction_of_set': 'ignores denoms in missing-numerator items (bug)' }, build: ['single_fraction'] },
  // ---------------- Y2 B9 time ----------------
  'Y2.B9.S1': OK, 'Y2.B9.S2': OK, 'Y2.B9.S3': OK, 'Y2.B9.S4': OK, 'Y2.B9.S5': OK, 'Y2.B9.S6': OK, 'Y2.B9.S7': OK,
  // ---------------- Y2 B10 statistics ----------------
  'Y2.B10.S1': OK, 'Y2.B10.S2': OK, 'Y2.B10.S3': OK, 'Y2.B10.S4': OK, 'Y2.B10.S5': OK, 'Y2.B10.S6': OK, 'Y2.B10.S7': OK,
  // ---------------- Y2 B11 position ----------------
  'Y2.B11.S1': OK, 'Y2.B11.S2': OK, 'Y2.B11.S4': OK, 'Y2.B11.S5': OK,
  'Y2.B11.S3': { reviewed: true, pre: [R('shapes_early:shape_positions', 'Y2.B11.S1 the language of position (left, right)'), R('fractions:shade_fraction', 'Y2.B8 halves and quarters: a half turn and a quarter turn')] },
};
export const extendSteps = {
  tens_any: ['Y2.B2.S14'],
  add_next_10: ['Y2.B2.S9'],
};
export const retireBuilt = [
  { id: 'count_3s', by: 'multiplication:count_by_tables {rows:[{step:3,start:"zero"}]}', steps: ['Y2.B1.S16'] },
  { id: 'shape_faces', by: 'shapes_early:count_edges_faces_vertices {forms:[0]} / [1] / [2]', steps: ['Y2.B3.S8', 'Y2.B3.S9', 'Y2.B3.S10'] },
  { id: 'money_uk', by: 'measurement:money_count {kind:"note"|"both", currency:"usd"} (Y2.B4.S2, S3); still open for Y2.B4.S8 "make $1"', steps: ['Y2.B4.S2', 'Y2.B4.S3'] },
];
export const proposals = {
  one_digit_addend: { kind: 'option', skill: 'addition:add_100_mixed', option: 'second number 1-digit (also on subtraction:sub_100_mixed): across a ten / not across', name: 'Add or Subtract Ones to a 2-Digit Number (option)',
    teaches: 'adding and subtracting a 1-digit number to or from a 2-digit number, first without and then across a ten (34 + 3, 34 − 3; 38 + 5, 42 − 5)',
    representation: 'one boxed cell per item: the across sentence with a base-10 picture (tens rods, ones cubes) under it as the structural support; answer box', family: 'operations',
    steps: ['Y2.B2.S5', 'Y2.B2.S12'], ccss: ['1.NBT.C.4', '1.OA.C.6', '2.NBT.B.5'], why: 'the bands mix 1-digit + 1-digit and 2-digit + 2-digit; no option isolates 2-digit ± ones' },
  make_amount_notes: { kind: 'option', skill: 'measurement:equiv_coin_sets', option: 'task "make": choose bills and coins to make a given amount, any way (drawn bills $1/$5/$10/$20 and coins)', name: 'Make an Amount With Bills and Coins (option)',
    teaches: 'choosing bills and coins to make an amount ($35 = $20 + $10 + $5) and finding more than one way',
    representation: 'the amount in a box; a bank of drawn bills and coins to ring or tally; answer: tally boxes under each value', family: 'measurement',
    steps: ['Y2.B4.S4'], ccss: ['2.MD.C.8'], why: 'make_change_least_coins uses coins only and asks for the fewest coins; no skill deals bills to make an amount' },
  money_difference: { kind: 'option', skill: 'measurement:money', option: 'op "difference": subtract two prices / find how much more', name: 'Difference Between Two Amounts (option)',
    teaches: 'finding the difference between two amounts of money (a $7 toy and a $15 toy: $8 more), by counting on or subtracting',
    representation: 'two price tags in one cell, the sentence "___ − ___ = ___" with a bar model support; answer box with the $ sign printed', family: 'measurement',
    steps: ['Y2.B4.S7', 'Y3.B9.S5'], ccss: ['2.MD.C.8'], why: 'measurement:money only adds prices; money_change finds change from a whole amount, not a difference' },
  single_fraction: { kind: 'option', skill: 'fractions:shade_fraction', option: 'fraction: one chosen fraction (1/2, 1/4, 3/4, 1/3, 2/4) instead of a denominator family; also on identify, write_fraction, equiv_frac_visual, fraction_of_set', name: 'One Fraction per Page (option)',
    teaches: 'a page about ONE fraction (find a quarter, find a third, three-quarters) of a shape and of an amount, as WRM Y2 teaches them one at a time',
    representation: 'the existing fraction cells (area, bar, circle, set of objects) with the one fraction; answer: shade or write the number', family: 'fractions',
    steps: ['Y2.B8.S6', 'Y2.B8.S8', 'Y2.B8.S12', 'Y2.B8.S13', 'Y2.B8.S14'], ccss: ['1.G.A.3', '2.G.A.3'], why: '`denoms` picks a family (halves → quarters, eighths); WRM Y2 needs one fraction per step' },
};
export const extraPre = {
  'Y2.B7.S6': [R('number_sense:place_on_number_line', 'reading a scale is reading a number line in steps'), R('multiplication:count_by_tables', 'counting in 2s, 5s and 10s from 0 to read the scale marks')],
  'Y2.B7.S7': [R('measurement:mass_volume_liquid', 'Y2.B7.S6 reading millilitres on a jug (a partial skill of this step too)'), R('number_sense:place_on_number_line', 'reading a scale is reading a number line')],
  'Y2.B7.S9': [R('number_sense:place_on_number_line', 'a thermometer is a vertical number line'), R('multiplication:count_by_tables', 'counting in 2s, 5s and 10s from 0 to read the marks')],
  'Y2.B9.S1': [R('measurement:clock_parts', 'the parts of a clock face: hour hand and minute hand')],
};
export const extraRelated = {
  'Y2.B1.S9': [R('multiplication:count_by_tables', 'counting in 10s from 0, the count the line is marked in')],
  'Y2.B1.S11': [R('measurement:estimate_length', 'estimating a length, the same judging-by-eye'), R('placevalue:compare', 'deciding which number is nearer, the same reasoning as an estimate')],
  'Y2.B2.S1': [R('subtraction:sub_facts', 'the inverse: 10 − 3 = 7 from 3 + 7 = 10')],
  'Y2.B3.S8': [R('angles_lines:symmetry', 'looking closely at flat faces and their shapes'), R('shapes_early:shape_attributes', 'describing shapes by their properties'), R('shapes_early:shape_name_match_3d', 'matching 3-D shapes to names by their faces'), R('shapes_early:name_3d_shapes', 'naming the shape whose faces are counted')],
  'Y2.B3.S9': [R('shapes_early:shape_attributes', 'describing shapes by their properties'), R('shapes_early:shape_name_match_3d', 'matching 3-D shapes to names by their properties'), R('shapes_early:name_3d_shapes', 'naming the shape whose edges are counted')],
  'Y2.B4.S1': [R('measurement:money_compare', 'comparing two amounts of coins, the next use of a total')],
  'Y2.B4.S9': [R('subtraction:sub_wp_100', 'take-away stories: change is a subtraction')],
  'Y2.B5.S1': [R('multiplication:mult_word_problems', 'equal groups in stories'), R('division:share_into_groups', 'making equal groups from a total, the inverse view'), R('multiplication:arrays_groups', 'equal groups written as "groups of" sentences, the next idea')],
  'Y2.B5.S2': [R('multiplication:mult_word_problems', 'equal groups in stories'), R('multiplication:dot_array_mult', 'equal groups set out in rows as an array'), R('multiplication:repeated_add_to_mult', 'adding the equal groups made')],
  'Y2.B5.S3': [R('multiplication:mult_facts', 'the multiplication fact the repeated addition becomes')],
  'Y2.B5.S4': [R('multiplication:mult_facts', 'the × facts the symbol is used for'), R('multiplication:arrays_groups', 'the × sentence read from a picture of groups')],
  'Y2.B5.S5': [R('multiplication:mult_word_problems', 'multiplication sentences in stories'), R('multiplication:dot_array_mult', 'the same sentence read from an array')],
  'Y2.B5.S6': [R('multiplication:mult_facts', 'the facts an array shows'), R('multiplication:repeated_add_to_mult', 'an array row by row is a repeated addition')],
  'Y2.B5.S15': [R('measurement:time_fives_ring', 'counting in 5s round a clock face'), R('division:div_facts', 'the inverse: dividing by 5 (Y2.B5.S16)')],
  'Y2.B5.S17': [R('measurement:money_count', 'counting 5-cent and 10-cent coins'), R('division:div_facts', 'the inverse: dividing by 5 and 10')],
  'Y2.B8.S15': [R('multiplication:count_by_tables', 'counting in equal steps from 0, the same count with whole numbers')],
  'Y2.B9.S3': [R('measurement:time_analog_digital', 'the same time written as digits')],
  'Y2.B9.S5': [R('measurement:time_analog_digital', 'matching a clock to its digital time')],
  'Y2.B9.S6': [R('measurement:elapsed_hour', 'durations in hours, where minutes-in-an-hour is used')],
  'Y2.B9.S7': [R('measurement:time_sense', 'which unit of time an activity takes')],
  'Y2.B10.S1': [R('graphs:pictograph', 'the same data shown as a pictogram')],
  'Y2.B10.S7': [R('graphs:bar_graph', 'the same questions read from a bar chart')],
  'Y2.B11.S5': [R('patterns:shape_pattern', 'repeating shape patterns without turns')],
  'Y2.B1.S1': [R('placevalue:expand', 'a teen number written as 10 + 5, the same idea in symbols')],
  'Y2.B1.S5': [R('placevalue:combine', 'the inverse: put the parts back together (50 + 7 = 57)')],
  'Y2.B6.S4': [R('measurement:estimate_length', 'estimating lengths before ordering them')],
  'Y2.B7.S2': [R('measurement:unit_conversions', 'grams and kilograms as units of the same mass (later: 1 kg = 1,000 g)')],
  'Y2.B7.S3': [R('measurement:unit_conversions', 'kilograms and grams as units of the same mass')],
  'Y2.B7.S6': [R('measurement:capacity', 'capacity units and comparing containers')],
  'Y2.B7.S7': [R('measurement:capacity', 'capacity units: litres and smaller units')],
  'Y2.B7.S9': [R('comparing:compare_objects', 'warmer and colder as comparison language, like longer and shorter')],
  'Y2.B8.S1': [R('fractions:identify', 'naming a part of a whole as a fraction, where parts and wholes lead')],
  'Y2.B8.S3': [R('fractions:identify', 'name the fraction shaded: 1/2 among others')],
  'Y2.B8.S4': [R('patterns:double', 'doubling is the inverse of halving')],
  'Y2.B8.S5': [R('fractions:identify', 'name the fraction shaded, quarters among others')],
  'Y2.B8.S6': [R('fractions:identify', 'name the fraction shaded: 1/4 among others')],
  'Y2.B8.S7': [R('fractions:identify', 'name the fraction shaded, thirds among others')],
  'Y2.B11.S1': [R('coordinates:coordinate_q1', 'describing position on a grid, where this language leads')],
  'Y2.B11.S2': [R('coordinates:geo_translate', 'movement on a grid as a translation (later years)')],
  'Y2.B11.S3': [R('coordinates:geo_rotate', 'turns of a shape as a rotation (later years)')],
  'Y2.B11.S4': [R('coordinates:geo_translate', 'movement on a grid as a translation'), R('coordinates:geo_rotate', 'turns as a rotation')],
};
