// Hand verdicts for Y2 / Y3, round 2. Every entry was judged from items generated WITH the opts below
// (tests/scripts/wrm-tagging/items.mjs; log in design/audit/runs/wrm-tagging/Y2-Y3-items.md).
//   direct:[{key,opts}]  partials:[{key,missing,opts?}]  verdict  missing  build  pre  preBuild  related  note
//   reviewed:true = the SKILL_WRM tags were re-generated and stand as they are.
export const exclude = ['addition:equal_sign']; // deals plain column addition today (build-list equal_sign_repair)
const D = (key, opts = {}) => ({ key, opts });
const P = (key, missing, opts) => ({ key, missing, ...(opts ? { opts } : {}) });
const R = (key, why) => ({ key, why });
const USD = { currency: 'usd' };
const zero = (step) => ({ rows: [{ step, start: 'zero', dir: 'up' }] });
const OK = { reviewed: true };

export const steps = {
  // ---------------- Y2 B1 place value ----------------
  'Y2.B1.S1': { direct: [D('composing:teen_compose'), D('composing:base10_build', { band: 20 })] },
  'Y2.B1.S2': { partials: [P('composing:base10_build', 'grouping loose objects into tens to count them (the skill shows ready-made tens rods)', { band: 99 })],
    pre: [R('counting:count_objects', 'Y1.B1.S2 count objects one by one, the first step of counting by tens')] },
  'Y2.B1.S3': { direct: [D('composing:tens_foundation_visual', { band: 90 }), D('composing:base10_build', { band: 99 })] },
  'Y2.B1.S4': { direct: [D('placevalue:identify', { band: 99 }), D('placevalue:value', { band: 99 })], note: 'band 99 keeps the chart to tens and ones (the default 999 deals 3-digit numbers, above Y2)' },
  'Y2.B1.S5': { direct: [D('placevalue:expand', { band: 99 }), D('placevalue:unit_form', { band: 99 })] },
  'Y2.B1.S7': OK,
  'Y2.B1.S8': { direct: [D('placevalue:expand', { band: 99 }), D('placevalue:combine', { band: 99 })] },
  'Y2.B1.S6': { direct: [D('composing:number_word_form', { wordform: ['to_words', 'to_number'], range: 100 })],
    related: [R('placevalue:unit_form', 'the same number said as tens and ones before it is written in words')] },
  'Y2.B1.S9': { partials: [P('number_sense:place_on_number_line', 'counting in 10s along a whole 0-100 line marked in tens (the line spans one ten)', { span: 10, band: 100 })], build: ['nl_20'] },
  'Y2.B1.S10': { partials: [P('number_sense:place_on_number_line', 'a whole 0-100 line counted in tens then ones (the line spans one ten)', { span: 10, band: 100 })], build: ['nl_20'] },
  'Y2.B1.S11': { partials: [P('number_sense:place_on_number_line', 'estimating on a 0-100 line with only the ends marked (every tick is drawn)', { span: 10, band: 100 })], build: ['nl_20'] },
  'Y2.B1.S12': OK,
  'Y2.B1.S13': { direct: [D('placevalue:compare', { band: 99 })] },
  'Y2.B1.S14': { direct: [D('placevalue:order_least_to_greatest', { band: 99 }), D('placevalue:order_greatest_to_least', { band: 99 })] },
  'Y2.B1.S15': { direct: [D('multiplication:count_by_tables', { rows: [{ step: 2, start: 'zero', dir: 'up' }, { step: 5, start: 'zero', dir: 'up' }, { step: 10, start: 'zero', dir: 'up' }] })],
    why: { 'patterns:seq_2': 'items start anywhere (49, 51, 53): not the multiples of 2', 'patterns:seq_5': 'items start anywhere (49, 54, 59): not multiples of 5', 'patterns:seq_10': 'items start anywhere (23, 33, 43): not multiples of 10' },
    related: [R('patterns:seq_10', 'counting on in 10s from any number: the next idea (1.NBT.C.5)'), R('patterns:skip_count_line', 'the same count as jumps on a number line')] },
  'Y2.B1.S16': { direct: [D('multiplication:count_by_tables', zero(3))], verdict: 'full',
    note: 'count_by_tables with a row {step 3, from 0} deals 0, 3, 6 ... 33: the count_3s proposal is already built (retire it)',
    related: [R('patterns:skip_count_line', 'counting in 3s as jumps on a number line')] },
  // ---------------- Y2 B2 addition and subtraction ----------------
  'Y2.B2.S1': { direct: [D('composing:make_ten')], why: { 'composing:number_bonds': 'deals bonds of 4, 5, 6 ... within 10, not bonds TO 10: kept as a pre-skill' },
    pre: [R('composing:number_bonds', 'Y1 bonds within 10: the part-whole step before bonds to 10'), R('composing:ten_frame_build', 'numbers to 10 on a ten frame, the picture a bond to 10 is read from')] },
  'Y2.B2.S2': OK, 'Y2.B2.S3': OK, 'Y2.B2.S4': OK, 'Y2.B2.S7': OK, 'Y2.B2.S8': OK, 'Y2.B2.S10': OK, 'Y2.B2.S11': OK,
  'Y2.B2.S15': OK, 'Y2.B2.S16': OK, 'Y2.B2.S18': OK, 'Y2.B2.S21': OK,
  'Y2.B2.S5': { partials: [P('placevalue:more_less_10', 'only ±1; adding or subtracting several ones to a 2-digit number (34 + 3) without crossing a ten is not dealt', { step: 1 }),
      P('addition:number_line_add', 'within 20 only, not ones added to a 2-digit number')], build: ['one_digit_addend'] },
  'Y2.B2.S6': OK,
  'Y2.B2.S9': { partials: [P('addition:add_50_regroup', 'items mix 1-digit + 1-digit and 2-digit + 2-digit; 2-digit + 1-digit across a ten (38 + 5) is not alone on a page'),
      P('number_sense:make_a_ten', 'bridges 10 within 20 only, not a 2-digit number across the next ten')], build: ['add_next_10'] },
  'Y2.B2.S12': { partials: [P('subtraction:sub_50_regroup', 'items mix 2-digit − 2-digit with 2-digit − 1-digit; a page of 2-digit − 1-digit across a ten is not available', { band: 50 })],
    why: { 'subtraction:sub_100_regroup': 'deals 2-digit − 2-digit (66 − 17): that is Y2.B2.S18' }, build: ['one_digit_addend'],
    related: [R('subtraction:sub_100_regroup', 'the next step: 2-digit − 2-digit across a ten')] },
  'Y2.B2.S13': { direct: [D('placevalue:more_less_10', { step: 10 })] },
  'Y2.B2.S14': { partials: [P('addition:add_sub_10s', 'deals only a decade ± 10 (70 − 10); adding 20 or subtracting 30, and a 2-digit number ± tens (34 + 20), are not dealt')],
    build: ['tens_any'], pre: [R('placevalue:more_less_10', 'Y2.B2.S13 10 more, 10 less')] },
  'Y2.B2.S17': { reviewed: true, pre: [R('subtraction:sub_50_no_regroup', 'subtracting within 50 without an exchange, the smaller band first')] },
  'Y2.B2.S19': { direct: [D('addition:add_wp_100'), D('subtraction:sub_wp_100')], why: { 'subtraction:mixed_add_sub': 'sums pass 100 (96 + 44 = 140) and its range option is ignored: kept as related' }, related: [R('subtraction:mixed_add_sub', 'mixed + and − without a story (sums can pass 100)')], pre: [R('addition:add_100_no_regroup', 'Y2.B2.S15 adding two 2-digit numbers'), R('subtraction:sub_100_no_regroup', 'Y2.B2.S17 subtracting two 2-digit numbers'), R('addition:add_wp_20', 'one-step addition stories within 20'), R('subtraction:sub_wp_20', 'one-step subtraction stories within 20')], preOnly: true },
  'Y2.B2.S20': OK,
  // ---------------- Y2 B3 shape ----------------
  'Y2.B3.S1': OK, 'Y2.B3.S4': OK, 'Y2.B3.S5': OK, 'Y2.B3.S7': OK, 'Y2.B3.S11': OK, 'Y2.B3.S12': OK,
  'Y2.B3.S2': { direct: [D('shapes_early:count_sides_vertices_2d', { forms: [0] })] },
  'Y2.B3.S3': { direct: [D('shapes_early:shape_corners_count'), D('shapes_early:count_sides_vertices_2d', { forms: [1] })] },
  'Y2.B3.S6': { reviewed: true, preOnly: true, pre: [R('angles_lines:symmetry', 'Y2.B3.S5 lines of symmetry: find the mirror line before completing the half'), R('angles_lines:place_symmetry_lines', 'Y2.B3.S5 drawing the line of symmetry'), R('shapes_early:name_2d_shapes', 'Y2.B3.S1 naming the shape that is being completed')] },
  'Y2.B3.S8': { direct: [D('shapes_early:count_edges_faces_vertices', { forms: [0] })], verdict: 'full',
    note: 'forms [0] = faces only: the shape_faces proposal is already built (retire it). Owner question: the skill says a cylinder has 3 faces; WRM Y2 says 2 flat faces and 1 curved surface.' },
  'Y2.B3.S9': { direct: [D('shapes_early:count_edges_faces_vertices', { forms: [1] })] },
  'Y2.B3.S10': { direct: [D('shapes_early:count_edges_faces_vertices', { forms: [2] })] },
  // ---------------- Y2 B4 money (US dollars, owner answer) ----------------
  'Y2.B4.S1': { direct: [D('measurement:money_count', { currency: 'usd', kind: 'like' }), D('measurement:coin_value', USD)] },
  'Y2.B4.S2': { direct: [D('measurement:money_count', { currency: 'usd', kind: 'note' })], verdict: 'full', note: 'kind "note" counts $1, $5, $10, $20 bills: the money_uk option is built for this step' },
  'Y2.B4.S3': { direct: [D('measurement:money_count', { currency: 'usd', kind: 'both' })], verdict: 'full', note: 'kind "both": count the bills, then the coins, write both numbers' },
  'Y2.B4.S4': { partials: [P('measurement:make_change_least_coins', 'coins only and always the FEWEST coins; choosing bills and coins to make an amount (any way) is not dealt', USD)], build: ['make_amount_notes'] },
  'Y2.B4.S5': { direct: [D('measurement:equiv_coin_sets', USD)] },
  'Y2.B4.S6': { reviewed: true, note: 'money_compare has no US option (plain or QAR): plain cents are dealt' },
  'Y2.B4.S7': { partials: [P('measurement:money', 'adds whole-dollar prices only; finding the difference between two amounts is not dealt', USD)],
    why: { 'measurement:enough_money': 'asks "is there enough?" (a compare), not a calculation: kept as related' }, build: ['money_difference'],
    related: [R('measurement:enough_money', 'compare an amount with a price, the reasoning behind a difference'), R('measurement:money_change', 'the next step: change is a difference')] },
  'Y2.B4.S8': { partials: [P('measurement:equiv_coin_sets', 'checks whether coins make an amount up to $1; making exactly $1 (100 cents) in different ways is not asked', { currency: 'usd', band: 100 })], build: ['money_uk'] },
  'Y2.B4.S9': { direct: [D('measurement:money_change', { currency: 'usd', step: 100 })] },
  'Y2.B4.S10': { reviewed: true, preOnly: true, pre: [R('measurement:money', 'Y2.B4.S7 adding prices'), R('measurement:money_change', 'Y2.B4.S9 finding change'), R('addition:add_wp_100', 'one-step addition stories within 100'), R('subtraction:sub_wp_100', 'one-step subtraction stories within 100')] },
  // ---------------- Y2 B5 multiplication and division ----------------
  'Y2.B5.S1': OK, 'Y2.B5.S2': OK, 'Y2.B5.S4': OK, 'Y2.B5.S5': OK, 'Y2.B5.S7': OK, 'Y2.B5.S8': OK, 'Y2.B5.S12': OK,
  'Y2.B5.S3': { direct: [D('multiplication:arrays_groups', { forms: [1] }), D('multiplication:repeated_add_to_mult', { band: 25 })] },
  'Y2.B5.S6': { direct: [D('multiplication:arrays_groups', { forms: [0] }), D('multiplication:dot_array_mult', { band: 25 })] },
  'Y2.B5.S9': { direct: [D('multiplication:mult_facts', { constant: [2] }), D('multiplication:count_by_tables', zero(2))] },
  'Y2.B5.S10': { direct: [D('division:div_facts', { constant: [2] })] },
  'Y2.B5.S11': { direct: [D('patterns:double', { band: 20 }), D('patterns:halve', { band: 20 })] },
  'Y2.B5.S13': { direct: [D('multiplication:mult_facts', { constant: [10] }), D('multiplication:count_by_tables', zero(10))] },
  'Y2.B5.S14': { direct: [D('division:div_facts', { constant: [10] })] },
  'Y2.B5.S15': { direct: [D('multiplication:mult_facts', { constant: [5] }), D('multiplication:count_by_tables', zero(5))] },
  'Y2.B5.S16': { direct: [D('division:div_facts', { constant: [5] })] },
  'Y2.B5.S17': { direct: [D('multiplication:mult_facts', { constant: [5, 10] }), D('multiplication:mult_chart_easy', { constant: [5, 10] })] },
  // ---------------- Y2 B6 length ----------------
  'Y2.B6.S1': { reviewed: true, pre: [R('shapes_early:measure_nonstandard', 'Y1.B7.S2 measuring length with cubes and paper clips (prior learning wk W21)'), R('comparing:compare_objects', 'Y1.B7.S1 compare lengths and heights')],
    related: [R('measurement:estimate_length', 'estimating a length before measuring it'), R('measurement:length_metric', 'cm and m as units of the same length')] },
  'Y2.B6.S2': { reviewed: true, related: [R('measurement:estimate_length', 'choosing cm or m for an object'), R('measurement:reading_ruler', 'measuring on a scale (the ruler)')] },
  'Y2.B6.S3': { partials: [P('comparing:compare_objects', 'compares pictured objects; comparing lengths given in cm and m with <, > and = is not dealt'), P('shapes_early:order_objects_length', 'orders pictured objects; no lengths in cm or m')], build: ['compare_lengths'],
    related: [R('placevalue:compare', 'comparing the numbers of the measurements with <, >, =')] },
  'Y2.B6.S4': { partials: [P('shapes_early:order_objects_length', 'orders pictured objects; ordering lengths given in cm and m is not dealt')], build: ['compare_lengths'],
    related: [R('placevalue:order_least_to_greatest', 'ordering the numbers of the measurements')] },
  'Y2.B6.S5': { reviewed: true, preOnly: true, pre: [R('measurement:reading_ruler', 'Y2.B6.S1 measuring a length'), R('addition:add_wp_100', 'addition stories within 100'), R('subtraction:sub_wp_100', 'subtraction and difference stories within 100'), R('multiplication:mult_facts', 'Y2.B5 the 2, 5 and 10 times-tables ("twice as tall")'), R('patterns:halve', 'Y2.B5.S11 halving ("half as tall")')],
    related: [R('measurement:estimate_length', 'estimating lengths to check a calculation'), R('measurement:unit_conversion_word', 'measure word problems in the next years')] },
  // ---------------- Y2 B7 mass, capacity, temperature ----------------
  'Y2.B7.S1': { reviewed: true, related: [R('comparing:compare_objects', 'comparing by length and height, the same compare language')] },
  'Y2.B7.S2': { partials: [P('measurement:mass_volume_liquid', 'reads one kind of g scale (and some kg items); reading scales in grams with different steps is not dealt', { forms: [1] })], build: ['mass_scales'] },
  'Y2.B7.S3': { partials: [P('measurement:mass_volume_liquid', 'mostly grams; reading a kilogram scale is not dealt', { forms: [1] })], build: ['mass_scales'] },
  'Y2.B7.S4': { reviewed: true, preOnly: true, pre: [R('measurement:mass_volume_liquid', 'Y2.B7.S2 reading a mass in grams'), R('addition:add_wp_100', 'addition stories within 100'), R('subtraction:sub_wp_100', 'subtraction stories within 100'), R('measurement:heavier_lighter_visual', 'Y2.B7.S1 heavier and lighter')],
    related: [R('measurement:capacity', 'the same operations with capacity (Y2.B7.S8)')] },
  'Y2.B7.S5': { reviewed: true, pre: [R('comparing:compare_objects', 'compare language (more, less) from length and height')], related: [R('measurement:capacity', 'capacity units and comparing containers'), R('measurement:heavier_lighter_visual', 'comparing mass, the same compare language')] },
  'Y2.B7.S6': { direct: [D('measurement:mass_volume_liquid', { forms: [0] })] },
  'Y2.B7.S7': { partials: [P('measurement:mass_volume_liquid', 'reads millilitres only; reading a jug in litres is not dealt', { forms: [0] })], build: ['mass_scales'] },
  'Y2.B7.S8': { reviewed: true, preOnly: true, pre: [R('measurement:mass_volume_liquid', 'Y2.B7.S6 reading millilitres'), R('addition:add_wp_100', 'addition stories within 100'), R('subtraction:sub_wp_100', 'subtraction stories within 100')], related: [R('measurement:capacity', 'capacity units')] },
  'Y2.B7.S9': { direct: [D('measurement:temperature', { forms: [1] })], note: 'forms [1] reads a °C thermometer (forms [0] is °F)' },
  // ---------------- Y2 B8 fractions ----------------
  'Y2.B8.S1': OK, 'Y2.B8.S2': OK, 'Y2.B8.S9': OK, 'Y2.B8.S15': OK,
  'Y2.B8.S3': { direct: [D('shapes_early:partition_shapes', { parts: [0] })] },
  'Y2.B8.S4': { direct: [D('patterns:halve', { band: 20 })], partials: [P('fractions:shade_fraction', 'denoms [2] is the halves family: it also deals 4/8 and 5/8, not only 1/2', { denoms: [2] })],
    why: { 'fractions:fraction_of_set': 'ignores denoms in its missing-numerator items (generator bug): cannot be narrowed to halves' },
    note: 'half of an amount is dealt by halve {band 20}; a page of 1/2 of a shape needs single_fraction',
    related: [R('shapes_early:partition_shapes', 'Y2.B8.S3 recognising a half of a shape')] },
  'Y2.B8.S5': { direct: [D('shapes_early:partition_shapes', { parts: [2] })] },
  'Y2.B8.S6': { partials: [P('fractions:shade_fraction', 'the halves family (1/2, 1/4, 3/4, eighths): a page of quarters only is not available', { denoms: [2] })],
    why: { 'fractions:fraction_of_set': 'ignores denoms in missing-numerator items (bug)' }, build: ['single_fraction'] },
  'Y2.B8.S7': { direct: [D('shapes_early:partition_shapes', { parts: [1] })] },
  'Y2.B8.S8': { partials: [P('fractions:shade_fraction', 'the thirds family also deals sixths and twelfths; a page of 1/3 only is not available', { denoms: [3] })],
    why: { 'fractions:fraction_of_set': 'ignores denoms in missing-numerator items (bug)' }, build: ['single_fraction'] },
  'Y2.B8.S10': { partials: [P('fractions:identify', 'denoms [2,3] are families: items deal 2/6, 1/6 and 7/8, not only unit halves, quarters and thirds', { denoms: [2, 3] }), P('fractions:write_fraction', 'deals 7/8 and 1/6 (non-unit, sixths, eighths)', { denoms: [2, 3] })], build: ['single_fraction'] },
  'Y2.B8.S11': { partials: [P('fractions:write_fraction', 'denoms [2,3] also deal sixths and eighths (7/8), above Y2', { denoms: [2, 3] }), P('fractions:shade_fraction', 'deals 7/8 and 1/6', { denoms: [2, 3] })], build: ['single_fraction'] },
  'Y2.B8.S12': { partials: [P('fractions:equiv_frac_visual', 'the halves family deals 3/4 = 12/16 and eighths too; a page of 1/2 = 2/4 only is not available', { denoms: [2] })], build: ['single_fraction'] },
  'Y2.B8.S13': { partials: [P('shapes_early:partition_shapes', 'quarters shapes: shades 1/4, 2/4 and 3/4, not three-quarters alone', { parts: [2] }), P('fractions:identify', 'the halves family, not 3/4 alone', { denoms: [2] })],
    why: { 'fractions:write_fraction': 'deals sixths, fifths and eighths at Y2 (no single-fraction option)' }, build: ['single_fraction'] },
  'Y2.B8.S14': { partials: [P('fractions:shade_fraction', 'the halves family; a page of 3/4 of a shape or amount is not available', { denoms: [2] })],
    why: { 'fractions:fraction_of_set': 'ignores denoms in missing-numerator items (bug)' }, build: ['single_fraction'] },
  // ---------------- Y2 B9 time ----------------
  'Y2.B9.S1': OK, 'Y2.B9.S2': OK,
  'Y2.B9.S3': { partials: [P('measurement:time_5min', 'words-past turns "twenty past two" into 2:20 but mixes in "to" times; reading a clock and saying it as minutes PAST the hour is not dealt', { stimulus: 'words-past' })], build: ['time_past_to'],
    related: [R('measurement:time_analog_digital', 'the same time written as digits')] },
  'Y2.B9.S4': { partials: [P('measurement:time_5min', 'words-past mixes "past" and "to"; reading a clock and saying it as minutes TO the next hour is not dealt', { stimulus: 'words-past' })], build: ['time_past_to'] }, 'Y2.B9.S5': OK, 'Y2.B9.S6': OK, 'Y2.B9.S7': OK,
  // ---------------- Y2 B10 statistics ----------------
  'Y2.B10.S1': OK, 'Y2.B10.S2': OK, 'Y2.B10.S3': OK, 'Y2.B10.S4': OK, 'Y2.B10.S5': OK, 'Y2.B10.S6': OK, 'Y2.B10.S7': OK,
  // ---------------- Y2 B11 position ----------------
  'Y2.B11.S1': OK, 'Y2.B11.S2': OK, 'Y2.B11.S4': OK, 'Y2.B11.S5': OK,
  'Y2.B11.S3': { reviewed: true, pre: [R('shapes_early:shape_positions', 'Y2.B11.S1 the language of position (left, right)'), R('fractions:shade_fraction', 'Y2.B8 halves and quarters: a half turn and a quarter turn')] },

  // ================= Y3 B1 place value =================
  'Y3.B1.S1': { direct: [D('composing:base10_build', { band: 99 }), D('placevalue:unit_form', { band: 99 })] },
  'Y3.B1.S2': { direct: [D('placevalue:expand', { band: 99 })], related: [R('composing:base10_build', 'the same partition built with tens rods and ones cubes')] }, 'Y3.B1.S3': OK, 'Y3.B1.S5': OK, 'Y3.B1.S6': OK, 'Y3.B1.S7': OK, 'Y3.B1.S8': OK, 'Y3.B1.S12': OK, 'Y3.B1.S13': OK,
  'Y3.B1.S4': { partials: [P('composing:base10_build_hundreds', 'builds 3-digit numbers; counting in 100s and 10 hundreds = 1,000 are not dealt'),
      P('multiplication:count_by_tables', 'counts in 100s from 0 but runs past 1,000 (to 1,100)', zero(100))], build: ['count_50s'] },
  'Y3.B1.S9': { partials: [P('placevalue:more_less_100', 'steps of 10 and 100 only (step "mixed" also adds 1,000 more, past the step); 1 more and 1 less on a 3-digit number is not dealt', { step: 0 })], build: ['more_less_1_3digit'] },
  'Y3.B1.S10': { partials: [P('number_sense:place_on_number_line', 'marks a number between two hundreds; a whole 0-1,000 line counted in 100s, and reading the value at an arrow, are not dealt', { span: 100, band: 1000 })], build: ['nl_20'] },
  'Y3.B1.S11': { partials: [P('number_sense:place_on_number_line', 'the hundreds are marked; estimating on a line with only the ends (0 and 1,000) marked is not dealt', { span: 100, band: 1000 })], build: ['nl_20'] },
  'Y3.B1.S14': { direct: [D('multiplication:count_by_tables', zero(50))], verdict: 'full',
    preOnly: true, pre: [R('patterns:seq_10', 'Y2.B1.S15 counting in 10s'), R('multiplication:mult_facts', 'Y2.B5.S15 the 5 times-table: 50 is 5 tens (opts constant [5])'), R('placevalue:more_less_100', 'Y3.B1.S4 counting in 100s: two 50s make 100')],
    related: [R('patterns:skip_count_line', 'counting in 50s as jumps on a number line')],
    note: 'count_by_tables with a row {step 50, from 0} deals 0, 50 ... 550: count_50s is built for this step (still open for Y3.B1.S4)' },
  // ================= Y3 B2 addition and subtraction =================
  'Y3.B2.S1': { partials: [P('addition:add_sub_10s', 'a decade ± 10 only; 30 + 40 from 3 + 4 is not dealt'), P('addition:add_sub_100s', 'a hundred ± 100 only; 300 + 400 from 3 + 4 is not dealt')],
    why: { 'addition:add_facts': 'within-20 facts: the bonds themselves, not applied to tens and hundreds (kept as pre)', 'subtraction:sub_facts': 'within-20 facts (kept as pre)' },
    build: ['add_sub_patterns'], preOnly: true, pre: [R('composing:number_bonds', 'Y2.B2.S1 bonds within 10: the facts being applied'), R('composing:make_ten', 'bonds to 10'), R('addition:add_facts', 'addition facts within 20'), R('subtraction:sub_facts', 'subtraction facts within 20'), R('addition:add_sub_10s', 'Y2.B2.S14 adding and subtracting 10s')] },
  'Y3.B2.S2': { reviewed: true, build: ['add_sub_patterns', 'one_digit_addend'] },
  'Y3.B2.S3': { partials: [P('addition:add_sub_10s', 'a decade ± 10 only; adding and subtracting 10s to a 2- or 3-digit number (234 + 30) is not dealt'), P('placevalue:more_less_100', '10 more / 10 less only, not several tens', { step: 10 })], build: ['tens_any'] },
  'Y3.B2.S4': { partials: [P('addition:add_sub_100s', 'a hundred ± 100 only; adding hundreds to a 3-digit number (234 + 200) is not dealt'), P('placevalue:more_less_100', '100 more / 100 less only', { step: 100 })], build: ['hundreds_any'] },
  'Y3.B2.S5': OK, 'Y3.B2.S6': OK, 'Y3.B2.S7': OK, 'Y3.B2.S8': OK, 'Y3.B2.S9': OK, 'Y3.B2.S10': OK, 'Y3.B2.S11': OK, 'Y3.B2.S12': OK,
  'Y3.B2.S19': OK, 'Y3.B2.S20': OK, 'Y3.B2.S21': OK, 'Y3.B2.S22': OK,
  'Y3.B2.S13': { partials: [P('addition:add_1k_regroup', 'exchanges in the ones and the tens are mixed (167 + 499 exchanges twice); a page with one exchange in the ones only is not available')], build: ['exchange_count'] },
  'Y3.B2.S14': { partials: [P('addition:add_1k_regroup', 'exchanges are mixed; a page with one exchange in the tens (across a 100) only is not available')], build: ['exchange_count'] },
  'Y3.B2.S15': { partials: [P('subtraction:sub_1k_regroup', 'exchanges are mixed (307 − 278 exchanges twice); one exchange from the tens only is not available')], build: ['exchange_count'] },
  'Y3.B2.S16': { direct: [D('subtraction:sub_across_zeros', { band: 500 })], partials: [P('subtraction:sub_1k_regroup', 'exchanges are mixed; one exchange from the hundreds only is not available')], verdict: 'partial', build: ['exchange_count'] },
  'Y3.B2.S17': { partials: [P('addition:add_1k_mixed', 'mostly 3-digit + 3-digit (404 + 134); a page of 2-digit + 3-digit is not available')], build: ['two_and_three_digit'] },
  'Y3.B2.S18': { partials: [P('subtraction:sub_1k_mixed', 'mostly 3-digit − 3-digit (538 − 404); a page of 3-digit − 2-digit is not available')], build: ['two_and_three_digit'] },
  // ================= Y3 B3 multiplication and division A =================
  'Y3.B3.S1': { direct: [D('multiplication:arrays_groups', { forms: [1] }), D('multiplication:repeated_add_to_mult', { band: 36 })] },
  'Y3.B3.S2': { direct: [D('multiplication:arrays_groups', { forms: [0] }), D('multiplication:dot_array_mult', { band: 100 })] },
  'Y3.B3.S3': { reviewed: true, related: [R('composing:odd_even', 'multiples of 2 are the even numbers')] },
  'Y3.B3.S4': { reviewed: true, related: [R('multiplication:count_by_tables', 'counting in 5s and 10s from 0 lists the multiples')] },
  'Y3.B3.S5': OK,
  'Y3.B3.S6': { direct: [D('multiplication:mult_facts', { constant: [3] })] },
  'Y3.B3.S7': { direct: [D('division:div_facts', { constant: [3] })] },
  'Y3.B3.S8': { direct: [D('multiplication:mult_facts', { constant: [3] }), D('multiplication:count_by_tables', zero(3))] },
  'Y3.B3.S9': { direct: [D('multiplication:mult_facts', { constant: [4] })] },
  'Y3.B3.S10': { direct: [D('division:div_facts', { constant: [4] })] },
  'Y3.B3.S11': { direct: [D('multiplication:mult_facts', { constant: [4] }), D('multiplication:count_by_tables', zero(4))] },
  'Y3.B3.S12': { direct: [D('multiplication:mult_facts', { constant: [8] })] },
  'Y3.B3.S13': { direct: [D('division:div_facts', { constant: [8] })] },
  'Y3.B3.S14': { direct: [D('multiplication:mult_facts', { constant: [8] }), D('multiplication:count_by_tables', zero(8))] },
  'Y3.B3.S15': { partials: [P('multiplication:mult_facts', 'drills the three tables mixed; the doubling link (2 → 4 → 8) is not taught', { constant: [2, 4, 8] })], build: ['tables_links'] },
  // ================= Y3 B4 multiplication and division B =================
  'Y3.B4.S1': { direct: [D('multiplication:mult_zeros', { forms: [0] }), D('multiplication:count_by_tables', zero(10))],
    why: { 'patterns:seq_10': 'counts on in 10s from any number (49, 59): not the multiples of 10' }, related: [R('patterns:seq_10', 'counting on in 10s from any number, the next idea')] },
  'Y3.B4.S2': OK, 'Y3.B4.S3': OK, 'Y3.B4.S6': OK,
  'Y3.B4.S7': { partials: [P('division:box_division_easy', 'regroup "none" still deals 75 ÷ 5 and 84 ÷ 7 (an exchange of tens) and 1-digit dividends (15 ÷ 3): a page of 2-digit ÷ 1-digit with no exchange is not available', { regroup: 'none' })],
    why: { 'division:area_model_div_2by1': 'partitions with an exchange (65 ÷ 5 = 50 ÷ 5 + 15 ÷ 5): that is Y3.B4.S8' }, build: ['exchange_count'],
    related: [R('division:area_model_div_2by1', 'the next step: dividing by flexible partitioning')] }, 'Y3.B4.S8': OK, 'Y3.B4.S9': OK, 'Y3.B4.S10': OK,
  'Y3.B4.S4': { partials: [P('multiplication:multiply', '2-digit × 1-digit with and without exchanges mixed (53 × 8); a no-exchange page is not available', { tiles: 21 }), P('multiplication:area_model_mult', 'the partition picture, exchanges mixed', { tiles: 21 })], build: ['exchange_count'] },
  'Y3.B4.S5': { partials: [P('multiplication:multiply', 'mostly with an exchange, but no-exchange items (30 × 2) are mixed in', { tiles: 21 }), P('multiplication:area_model_mult', 'the partition picture; exchanges are not controlled (3 × 13)', { tiles: 21 })], build: ['exchange_count'] },
  'Y3.B4.S11': { reviewed: true, preOnly: true, pre: [R('multiplication:mult_facts', 'Y3.B3 the 2, 3, 4, 5, 8, 10 tables'), R('multiplication:arrays_groups', 'Y3.B3.S2 rows and columns: a table of combinations is an array'), R('multiplication:mult_word_problems', 'multiplication in stories')] },
  // ================= Y3 B5 length and perimeter =================
  'Y3.B5.S1': { partials: [P('measurement:length_metric', 'converts whole metres to cm; measuring in m and cm with a mixed answer (1 m 25 cm) is not dealt', { forms: [1] })], build: ['mm_cm_m'] },
  'Y3.B5.S2': OK, 'Y3.B5.S3': OK, 'Y3.B5.S7': OK, 'Y3.B5.S8': OK, 'Y3.B5.S9': OK, 'Y3.B5.S10': OK, 'Y3.B5.S11': OK, 'Y3.B5.S12': OK,
  'Y3.B5.S4': { direct: [D('measurement:length_metric', { forms: [0, 1, 2] })], note: 'forms 0-2 = mm/cm, cm/m, mm/m; form 3 (m in km) is above the step' },
  'Y3.B5.S5': { partials: [P('measurement:length_metric', 'whole metres to cm only (3 m = 300 cm); mixed units (1 m 20 cm = 120 cm) are not dealt', { forms: [1] })], build: ['mm_cm_m'] },
  'Y3.B5.S6': { partials: [P('measurement:length_metric', 'whole cm to mm only; mixed units (4 cm 5 mm = 45 mm) are not dealt', { forms: [0] })], build: ['mm_cm_m'] },
  // ================= Y3 B6 fractions A =================
  'Y3.B6.S1': OK, 'Y3.B6.S3': OK, 'Y3.B6.S4': OK, 'Y3.B6.S6': OK, 'Y3.B6.S7': OK, 'Y3.B6.S8': OK, 'Y3.B6.S9': OK, 'Y3.B6.S10': OK,
  'Y3.B6.S2': { partials: [P('fractions:compare', 'compares any two fractions (2/6 and 7/8); a page of unit fractions only is not available', { forms: [0] }), P('fractions:order_fractions', 'orders non-unit fractions too')], build: ['compare_kind'] },
  'Y3.B6.S5': { partials: [P('fractions:compare', 'forms [1] mixes same-denominator pairs (3/10, 9/10) with others (5/8, 1/3)', { forms: [1] }), P('fractions:order_fractions', 'mixed denominators')], build: ['compare_kind'] },
  // ================= Y3 B7 mass and capacity =================
  'Y3.B7.S1': { partials: [P('measurement:mass_volume_liquid', 'reads one kind of scale each; scales with different intervals are not dealt', { forms: [0, 1] })], build: ['mass_scales'] },
  'Y3.B7.S2': { partials: [P('measurement:mass_volume_liquid', 'grams on a scale, but some items ask the mass in kg (answer 0) on the same scale', { forms: [1] })], build: ['mass_scales'] },
  'Y3.B7.S3': { partials: [P('measurement:mass_volume_liquid', 'g or kg alone; mixed kg and g readings are not dealt', { forms: [1] })], build: ['mass_scales'] },
  'Y3.B7.S4': { partials: [], verdict: 'gap', why: { 'measurement:unit_conversions': 'customary units only (ounces and pounds) with every option: no kg and g' }, build: ['metric_mass_capacity'], missing: 'converting kilograms and grams, including mixed units (1 kg 250 g = 1,250 g)' },
  'Y3.B7.S5': { partials: [P('measurement:heavier_lighter_visual', 'pictured objects; comparing masses in g and kg with <, > and = is not dealt')], build: ['compare_measures'] },
  'Y3.B7.S6': OK,
  'Y3.B7.S7': { direct: [D('measurement:mass_volume_liquid', { forms: [0] })] },
  'Y3.B7.S8': { partials: [P('measurement:mass_volume_liquid', 'millilitres only; mixed l and ml readings are not dealt', { forms: [0] })], build: ['mass_scales'] },
  'Y3.B7.S9': { partials: [P('measurement:capacity', 'L ↔ mL but with decimals (1.5 L), above the step; mixed units (1 l 500 ml) are not dealt', { units: [1], forms: [0] })], build: ['metric_mass_capacity'] },
  'Y3.B7.S10': { reviewed: true, build: ['compare_measures'] },
  'Y3.B7.S11': OK,
  // ================= Y3 B8 fractions B =================
  'Y3.B8.S1': { partials: [P('fraction_operations:add_fractions_like', 'sums pass one whole (4/5 + 2/5 = 1 1/5), above the step; adding within a whole only is not available', { denoms: [2, 3, 5] })], why: { 'fraction_operations:add_frac_like_nv': 'deals elevenths and sums above 1 (no picture): kept as related' }, build: ['within_whole'],
    related: [R('fraction_operations:add_frac_like_nv', 'the same sums without a picture')] },
  'Y3.B8.S2': { direct: [D('fraction_operations:sub_fractions_like', { denoms: [2, 3, 5] }), D('fraction_operations:sub_frac_like_nv', { denoms: [2, 3, 5] })] },
  'Y3.B8.S3': OK, 'Y3.B8.S6': OK,
  'Y3.B8.S5': { partials: [P('fractions:fraction_of_set', 'mixes unit fractions (1/5 of 60) and missing-numerator items, and ignores denoms there (generator bug); a page of non-unit fractions of a set (3/5 of 20) is not available'),
      P('fractions:fraction_of_set_nv', 'mixes unit and non-unit fractions, without the set pictured')], build: ['fos_kind'] },
  'Y3.B8.S4': { partials: [P('fractions:fraction_of_set', 'mixes non-unit fractions (3/5 of the cats) and ignores denoms in missing-numerator items (generator bug); a page of unit fractions of a set is not available')], build: ['fos_kind'] },
  // ================= Y3 B9 money (US dollars) =================
  'Y3.B9.S1': { direct: [D('measurement:money_count', { currency: 'usd', kind: 'both' }), D('measurement:money_notation', USD)], note: 'pounds and pence taught as dollars and cents (school uses US money)' },
  'Y3.B9.S2': OK,
  'Y3.B9.S3': { direct: [D('measurement:money', { currency: 'usd', step: 5 })] },
  'Y3.B9.S4': { partials: [P('measurement:money_change', 'subtracts a price from a whole-dollar payment; subtracting any two amounts (a difference) is not dealt', { currency: 'usd', step: 5 })], build: ['money_difference'] },
  'Y3.B9.S5': { direct: [D('measurement:money_change', { currency: 'usd', step: 5 })] },
  // ================= Y3 B10 time =================
  'Y3.B10.S1': { reviewed: true, note: 'beyond CCSS (owner ruling: keep); roman_12 is the clock band of the one roman_numerals skill (wrm.js roman_100 / roman_1000)' },
  'Y3.B10.S2': OK, 'Y3.B10.S3': OK, 'Y3.B10.S4': OK, 'Y3.B10.S5': OK, 'Y3.B10.S6': OK, 'Y3.B10.S7': OK, 'Y3.B10.S8': OK, 'Y3.B10.S9': OK, 'Y3.B10.S10': OK, 'Y3.B10.S11': OK, 'Y3.B10.S12': OK,
  // ================= Y3 B11 shape =================
  'Y3.B11.S1': OK, 'Y3.B11.S2': OK, 'Y3.B11.S3': OK, 'Y3.B11.S4': OK, 'Y3.B11.S5': OK, 'Y3.B11.S6': OK, 'Y3.B11.S7': OK, 'Y3.B11.S8': OK, 'Y3.B11.S10': OK,
  'Y3.B11.S9': OK,
  // ================= Y3 B12 statistics =================
  'Y3.B12.S1': OK, 'Y3.B12.S2': OK, 'Y3.B12.S3': OK, 'Y3.B12.S4': OK, 'Y3.B12.S5': OK, 'Y3.B12.S6': OK,
};
export const extendSteps = {
  tens_any: ['Y2.B2.S14', 'Y3.B2.S3'],
  mm_cm_m: ['Y3.B5.S5', 'Y3.B5.S6'],
  add_next_10: ['Y2.B2.S9'],
};
export const retireBuilt = [
  { id: 'count_50s', by: 'multiplication:count_by_tables {rows:[{step:50,start:"zero"}]} closes Y3.B1.S14; still open for Y3.B1.S4 (100s run past 1,000) and Y4', steps: ['Y3.B1.S14'] },
  { id: 'count_3s', by: 'multiplication:count_by_tables {rows:[{step:3,start:"zero"}]}', steps: ['Y2.B1.S16'] },
  { id: 'shape_faces', by: 'shapes_early:count_edges_faces_vertices {forms:[0]} / [1] / [2]', steps: ['Y2.B3.S8', 'Y2.B3.S9', 'Y2.B3.S10'] },
  { id: 'money_uk', by: 'measurement:money_count {kind:"note"|"both", currency:"usd"} (Y2.B4.S2, S3); still open for Y2.B4.S8 "make $1"', steps: ['Y2.B4.S2', 'Y2.B4.S3'] },
];
export const proposals = {

  more_less_1_3digit: { kind: 'option', skill: 'placevalue:more_less_100', option: 'step 1 (1 more / 1 less), step "ones" (add or subtract 1-9 without crossing a ten) and a "1, 10 or 100" mix, all within 1,000', name: 'Find 1, 10 or 100 More or Less; Add and Subtract Ones (option)',
    teaches: 'finding 1, 10 or 100 more or less than a 3-digit number, including across a ten or hundred (399 + 1, 305 − 10), and adding or subtracting ones to a 3-digit number where only the ones digit changes (234 + 5, 238 − 6)',
    representation: 'the existing frame cell "1 more than 489 is ____" with the place-value chart support; answer box', family: 'place value',
    steps: ['Y3.B1.S9', 'Y3.B2.S2'], ccss: ['2.NBT.B.8', '2.NBT.B.5'], why: 'more_less_100 has steps 10, 100, 1,000 only; more_less_10 stops at 120; no skill adds ones to a 3-digit number (one_digit_addend is 2-digit only)' },
  hundreds_any: { kind: 'option', skill: 'addition:add_sub_100s', option: 'task: any multiple of 100 to or from a 3-digit number (234 + 200, 650 − 300)', name: 'Add and Subtract Hundreds (option)',
    teaches: 'adding and subtracting multiples of 100 to and from 3-digit numbers, seeing only the hundreds digit change',
    representation: 'equation cell with place-value counters (hundreds, tens, ones) drawn beside it as the structural support; answer box', family: 'operations',
    steps: ['Y3.B2.S4'], ccss: ['2.NBT.B.7', '2.NBT.B.8'], why: 'add_sub_100s deals only a hundred ± 100 (900 − 100); tens_any is the tens version' },
  exchange_count: { kind: 'option', skill: 'addition:add_1k_regroup', skills: ['addition:add_1k_regroup', 'subtraction:sub_1k_regroup', 'subtraction:sub_across_zeros', 'multiplication:multiply', 'multiplication:area_model_mult', 'division:box_division_easy'], option: 'exchanges: none / one in the ones / one in the tens / two or more (owner ruling 2026-10-10: on every regroup band, + − × and short ÷)', name: 'Number and Place of Exchanges (option)',
    teaches: 'column addition, subtraction and short multiplication with exactly one exchange (across a 10, or across a 100) before two or more, so each WRM step adds one new thing',
    representation: 'the existing column cell with its regroup boxes; the generator only picks operands with the chosen exchanges', family: 'operations',
    steps: ['Y3.B2.S13', 'Y3.B2.S14', 'Y3.B2.S15', 'Y3.B2.S16', 'Y3.B4.S4', 'Y3.B4.S5', 'Y3.B4.S7'], ccss: ['2.NBT.B.7', '3.NBT.A.2', '4.NBT.B.5', '3.OA.C.7'], why: 'the regroup bands mix exchange places and counts; WRM splits "across a 10" from "across a 100", and Y3.B4.S4 needs no exchange' },
  two_and_three_digit: { kind: 'option', skill: 'addition:add_1k_mixed', option: 'digits: 2-digit and 3-digit operands (also on subtraction:sub_1k_mixed)', name: 'Add or Subtract a 2-Digit and a 3-Digit Number (option)',
    teaches: 'adding a 2-digit number to a 3-digit number and subtracting a 2-digit number from a 3-digit number in columns, lining up the places',
    representation: 'the column cell with the empty hundreds place of the 2-digit number shown, place headings H T O; answer boxes', family: 'operations',
    steps: ['Y3.B2.S17', 'Y3.B2.S18'], ccss: ['2.NBT.B.7'], why: 'the 1k bands deal mostly 3-digit with 3-digit; lining up a shorter number is the step' },
  compare_kind: { kind: 'option', skill: 'fractions:compare', option: 'kind: unit fractions / same denominator / same numerator (also on order_fractions)', name: 'Compare Unit or Same-Denominator Fractions (option)',
    teaches: 'comparing and ordering unit fractions (1/3 > 1/5: more parts, smaller part) and fractions with the same denominator (2/5 < 4/5)',
    representation: 'two bar models of the same whole length, one under the other, with the sign box between; ordering cell with 3 fractions', family: 'fractions',
    steps: ['Y3.B6.S2', 'Y3.B6.S5'], ccss: ['3.NF.A.3d'], why: 'compare mixes every kind of pair; WRM teaches unit fractions, then same denominators, as separate steps' },
  metric_mass_capacity: { kind: 'option', skill: 'measurement:capacity', option: 'metric whole and mixed units without decimals: kg ↔ g and l ↔ ml (2 kg = 2,000 g; 1 l 500 ml = 1,500 ml)', name: 'Equivalent Masses and Capacities (option)',
    teaches: 'converting kilograms and grams, litres and millilitres, using 1 kg = 1,000 g and 1 l = 1,000 ml and number bonds to 1,000',
    representation: 'conversion cell "1 kg 250 g = ____ g" with a part-whole bar (1,000 + 250); answer box', family: 'measurement',
    steps: ['Y3.B7.S4', 'Y3.B7.S9'], ccss: ['3.MD.A.2', '4.MD.A.1'], why: 'unit_conversions is customary only (ounces, pounds); capacity converts L/mL with decimals (1.5 L) and has no mass' },
  compare_measures: { kind: 'new', skill: 'measurement:compare_measures', name: 'Compare Measures', options: 'measure: length / mass / capacity; units: one unit (cm or m, g or kg, ml or l) / mixed units; task: compare two / order three',
    teaches: 'comparing two lengths, masses or capacities with <, > and =, and ordering three: first in one unit (24 cm < 31 cm), then in mixed units (450 g < 1 kg; 1,200 ml > 1 l)',
    representation: 'two measurement labels (or two drawn bars or scales) with a sign box between; the ordering cell has three labels and three answer boxes', family: 'measurement',
    steps: ['Y2.B6.S3', 'Y2.B6.S4', 'Y3.B7.S5', 'Y3.B7.S10'], ccss: ['1.MD.A.1', '2.MD.A.4', '3.MD.A.2'], why: 'compare_lengths (Y3) is mixed units only; heavier_lighter_visual, compare_objects and order_objects_length compare pictures without units; no skill compares measures given as numbers with units' },
  within_whole: { kind: 'option', skill: 'fraction_operations:add_fractions_like', skills: ['fraction_operations:add_fractions_like', 'fraction_operations:sub_fractions_like', 'fraction_operations:sub_frac_like_nv'], option: 'within one whole: sums at most 1, differences from a fraction at most 1, no compare-to-1/2 sort items, no simplifying', name: 'Add and Subtract Fractions Within a Whole (option)',
    teaches: 'adding and subtracting fractions with the same denominator within one whole (2/5 + 1/5 = 3/5; 4/5 − 1/5 = 3/5), the answer over the same denominator',
    representation: 'the existing bar-model add cell; answer: numerator over the given denominator', family: 'fractions',
    steps: ['Y3.B8.S1', 'Y3.B8.S2'], ccss: ['3.NF.A.1', '4.NF.B.3'], why: 'the add skill deals sums past 1 (4/5 + 2/5 = 1 1/5), which is Y4; both subtract skills mix in compare-to-1/2 sort items and "simplify"' },
  one_digit_addend: { kind: 'option', skill: 'addition:add_100_mixed', option: 'second number 1-digit (also on subtraction:sub_100_mixed): across a ten / not across', name: 'Add or Subtract Ones to a 2-Digit Number (option)',
    teaches: 'adding and subtracting a 1-digit number to or from a 2-digit number, first without and then across a ten (34 + 3, 34 − 3; 38 + 5, 42 − 5)',
    representation: 'one boxed cell per item: the across sentence with a base-10 picture (tens rods, ones cubes) under it as the structural support; answer box', family: 'operations',
    steps: ['Y2.B2.S5', 'Y2.B2.S12', 'Y3.B2.S2'], ccss: ['1.NBT.C.4', '1.OA.C.6', '2.NBT.B.5'], why: 'the bands mix 1-digit + 1-digit and 2-digit + 2-digit; no option isolates 2-digit ± ones' },
  make_amount_notes: { kind: 'option', skill: 'measurement:equiv_coin_sets', option: 'task "make": choose bills and coins to make a given amount, any way (drawn bills $1/$5/$10/$20 and coins)', name: 'Make an Amount With Bills and Coins (option)',
    teaches: 'choosing bills and coins to make an amount ($35 = $20 + $10 + $5) and finding more than one way',
    representation: 'the amount in a box; a bank of drawn bills and coins to ring or tally; answer: tally boxes under each value', family: 'measurement',
    steps: ['Y2.B4.S4'], ccss: ['2.MD.C.8'], why: 'make_change_least_coins uses coins only and asks for the fewest coins; no skill deals bills to make an amount' },
  money_difference: { kind: 'option', skill: 'measurement:money', option: 'op "difference": subtract two prices / find how much more', name: 'Difference Between Two Amounts (option)',
    teaches: 'finding the difference between two amounts of money (a $7 toy and a $15 toy: $8 more), by counting on or subtracting',
    representation: 'two price tags in one cell, the sentence "___ − ___ = ___" with a bar model support; answer box with the $ sign printed', family: 'measurement',
    steps: ['Y2.B4.S7', 'Y3.B9.S4'], ccss: ['2.MD.C.8'], why: 'measurement:money only adds prices; money_change finds change from a whole amount, not a difference' },
  time_past_to: { kind: 'option', skill: 'measurement:time_5min', option: 'say: "past" only / "to" only — a clock is shown and the pupil completes "___ minutes past ___" or "___ minutes to ___"', name: 'Minutes Past and To the Hour (option)',
    teaches: 'reading the minute hand on a clock and saying the time as minutes past the hour (20 past 3), then as minutes to the next hour (10 to 4)',
    representation: 'the B&W clock in its cell with the frame "___ minutes past ___" (two answer boxes); the "to" page shades nothing and keeps the same frame',
    family: 'measurement', steps: ['Y2.B9.S3', 'Y2.B9.S4'], ccss: ['2.MD.C.7'], why: 'time_5min reads the clock as digital (6:05); its words stimulus mixes past and to and goes words → digits' },
  fos_kind: { kind: 'option', skill: 'fractions:fraction_of_set', option: 'kind: unit fractions only / non-unit fractions only (and denoms honoured in every item type)', name: 'Unit or Non-Unit Fractions of a Set (option)',
    teaches: 'finding a unit fraction of a set (1/3 of 12: share into 3, count one group), then a non-unit fraction (2/3 of 12: count two groups)',
    closes: 'Y3.B8.S4 unit fractions of a set; Y3.B8.S5 non-unit fractions of a set',
    representation: 'the pictured set ringed into equal groups, the sentence "2/3 of 12 = ___"; answer box', family: 'fractions',
    steps: ['Y3.B8.S4', 'Y3.B8.S5'], ccss: ['3.NF.A.1'], why: 'fraction_of_set mixes unit and non-unit items and ignores denoms in its missing-numerator items' },
  sub_from_ten: { kind: 'option', skill: 'subtraction:sub_100_mixed', option: 'first number a multiple of 10, second number 1-digit (40 − 3, 70 − 6)', name: 'Subtract Ones From a Multiple of 10 (option)',
    teaches: 'subtracting a 1-digit number from a multiple of 10 by exchanging one ten for ten ones (40 − 3 = 37)',
    representation: 'one boxed cell: the sentence "40 − 3 = ___" with 4 tens rods drawn, one rod shown as 10 ones to cross out; answer box', family: 'operations',
    steps: ['Y2.B2.S11'], ccss: ['1.NBT.C.6', '2.NBT.B.5'], why: 'no band isolates a multiple of 10 minus ones; add_next_10 adds to the next 10 and one_digit_addend subtracts from any 2-digit number' },
  order_pictures: { kind: 'option', skill: 'placevalue:order_least_to_greatest', skills: ['placevalue:order_least_to_greatest', 'placevalue:order_greatest_to_least'], option: 'show: numerals / base-10 pictures (tens rods and ones) / objects in groups of ten', name: 'Order Numbers Shown as Pictures (option)',
    teaches: 'ordering three numbers to 100 shown as base-10 pictures or groups of objects, by comparing tens first and then ones',
    representation: 'three boxed pictures of tens rods and ones cubes, labelled A, B, C; answer: the letters (or the numbers) written in order in three boxes', family: 'place value',
    steps: ['Y2.B1.S14'], ccss: ['1.NBT.B.3'], why: 'the order skills show numerals only; WRM Y2 orders objects and numbers' },
  single_fraction: { kind: 'option', skill: 'fractions:shade_fraction', option: 'fraction: one chosen fraction (1/2, 1/4, 3/4, 1/3, 2/4) instead of a denominator family; also on identify, write_fraction, equiv_frac_visual, fraction_of_set', name: 'One Fraction per Page (option)',
    teaches: 'a page about ONE fraction (find a quarter, find a third, three-quarters) of a shape and of an amount, as WRM Y2 teaches them one at a time',
    representation: 'the existing fraction cells (area, bar, circle, set of objects) with the one fraction; answer: shade or write the number', family: 'fractions',
    steps: ['Y2.B8.S6', 'Y2.B8.S8', 'Y2.B8.S10', 'Y2.B8.S11', 'Y2.B8.S12', 'Y2.B8.S13', 'Y2.B8.S14'], ccss: ['1.G.A.3', '2.G.A.3'], why: '`denoms` picks a family (halves → quarters, eighths); WRM Y2 needs one fraction per step' },
};
export const extraPre = {
  'Y3.B7.S2': [R('measurement:mass_volume_liquid', 'Y2.B7.S2 reading a mass in grams on a simple scale (the same skill, Y2 opts forms [1])'), R('multiplication:count_by_tables', 'counting in 10s, 50s and 100s from 0 to read the scale marks')],
  'Y3.B7.S3': [R('measurement:heavier_lighter_visual', 'Y2.B7.S1 heavier and lighter'), R('multiplication:count_by_tables', 'counting in 100s to read a kg scale marked in 100 g')],
  'Y3.B7.S7': [R('measurement:capacity', 'capacity language and units (Y2.B7.S5 compare capacity)')],
  'Y3.B7.S8': [R('measurement:mass_volume_liquid', 'Y3.B7.S7 reading millilitres (partial skill of this step too)'), R('number_sense:place_on_number_line', 'reading a scale')],
  'Y3.B3.S12': [R('division:div_facts', 'the 4 times-table and dividing by 4 (Y3.B3.S9-S11): mult_facts {constant:[4]} doubled gives the 8s')],
  'Y3.B3.S14': [R('patterns:double', 'Y3.B3.S11 the 4 times-table doubled (practise mult_facts {constant:[4]} first)')],
  'Y2.B7.S6': [R('number_sense:place_on_number_line', 'reading a scale is reading a number line in steps'), R('multiplication:count_by_tables', 'counting in 2s, 5s and 10s from 0 to read the scale marks')],
  'Y2.B7.S7': [R('measurement:mass_volume_liquid', 'Y2.B7.S6 reading millilitres on a jug (a partial skill of this step too)'), R('number_sense:place_on_number_line', 'reading a scale is reading a number line')],
  'Y2.B7.S9': [R('number_sense:place_on_number_line', 'a thermometer is a vertical number line'), R('multiplication:count_by_tables', 'counting in 2s, 5s and 10s from 0 to read the marks')],
  'Y2.B9.S1': [R('measurement:clock_parts', 'the parts of a clock face: hour hand and minute hand')],
};
export const extraRelated = {
  'Y3.B5.S3': [R('measurement:estimate_length', 'choosing mm or cm for an object')],
  'Y3.B5.S12': [R('addition:add_three', 'adding three or four side lengths is adding three numbers')],
  'Y3.B7.S10': [R('measurement:heavier_lighter_visual', 'comparing masses, the same compare idea'), R('placevalue:compare', 'comparing the numbers once the units match')],
  'Y3.B7.S7': [R('number_sense:place_on_number_line', 'a measuring jug scale is a vertical number line')],
  'Y3.B1.S1': [R('placevalue:place_value_disks', 'the same number shown with place-value counters'), R('placevalue:expand', 'the same number written as tens + ones')],
  'Y3.B1.S5': [R('placevalue:expand', 'the number written as hundreds + tens + ones'), R('number_sense:place_on_number_line', 'the same number placed on a line')],
  'Y3.B1.S6': [R('placevalue:combine', 'the inverse: recombine the parts'), R('placevalue:place_value_disks', 'the parts shown as counters')],
  'Y3.B1.S13': [R('placevalue:compare', 'comparing two numbers, the step inside ordering')],
  'Y3.B2.S5': [R('placevalue:more_less_100', 'which digit changes when adding 10 or 100')],
  'Y3.B2.S7': [R('placevalue:more_less_100', '10 more across a hundred (298 + 10)'), R('addition:add_1k_regroup', 'the written method for crossing a hundred')],
  'Y3.B2.S21': [R('subtraction:missing_add_sub', 'finding a missing number with the inverse'), R('addition:add_sub_fact_family', 'fact families show the inverse')],
  'Y3.B3.S5': [R('multiplication:arrays_groups', 'equal groups written as a multiplication: the inverse')],
  'Y3.B3.S8': [R('division:div_facts', 'the inverse: dividing by 3')],
  'Y3.B3.S10': [R('multiplication:count_by_tables', 'counting in 4s from 0 finds the multiples used')],
  'Y3.B3.S11': [R('division:div_facts', 'the inverse: dividing by 4')],
  'Y3.B3.S12': [R('patterns:double', 'double the 4 times-table to get the 8 times-table')],
  'Y3.B3.S13': [R('multiplication:count_by_tables', 'counting in 8s from 0')],
  'Y3.B3.S14': [R('division:div_facts', 'the inverse: dividing by 8')],
  'Y3.B3.S15': [R('patterns:double', 'doubling links the 2, 4 and 8 tables')],
  'Y3.B5.S1': [R('measurement:estimate_length', 'choosing m or cm for an object')],
  'Y3.B5.S2': [R('measurement:length_metric', 'mm and cm as units of the same length (10 mm = 1 cm)')],
  'Y3.B5.S4': [R('measurement:estimate_length', 'choosing a sensible unit')],
  'Y3.B5.S5': [R('measurement:estimate_length', 'choosing m or cm'), R('placevalue:unit_form', 'the same exchange as 1 hundred = 10 tens (1 m = 100 cm)')],
  'Y3.B5.S6': [R('measurement:reading_ruler', 'measuring on a ruler marked in cm and mm')],
  'Y3.B5.S7': [R('placevalue:compare', 'comparing the numbers once the units match')],
  'Y3.B6.S8': [R('composing:fraction_number_line', 'reading a fraction at a point on the line')],
  'Y3.B6.S10': [R('fractions:equiv_frac_nv', 'equivalent fractions without a picture (the next idea)')],
  'Y3.B7.S1': [R('number_sense:place_on_number_line', 'a scale is a number line with intervals')],
  'Y3.B7.S2': [R('number_sense:place_on_number_line', 'a scale is a number line')],
  'Y3.B7.S3': [R('number_sense:place_on_number_line', 'a scale is a number line')],
  'Y3.B7.S4': [R('placevalue:unit_form', '1 kg = 1,000 g is the same exchange as 1 thousand = 10 hundreds')],
  'Y3.B7.S5': [R('placevalue:compare', 'comparing the numbers once the units match')],
  'Y3.B7.S6': [R('addition:add_1k_mixed', 'the column addition used with masses'), R('subtraction:sub_1k_mixed', 'the column subtraction used with masses')],
  'Y3.B7.S9': [R('placevalue:unit_form', '1 l = 1,000 ml, the same exchange as 1 thousand')],
  'Y3.B8.S6': [R('fractions:fraction_of_set_nv', 'fractions of amounts without pictures')],
  'Y3.B9.S1': [R('measurement:coin_value', 'the value of each coin'), R('placevalue:expand', 'dollars and cents as two parts of one amount')],
  'Y3.B9.S2': [R('placevalue:unit_form', '345 cents = 3 dollars 45 cents is the same exchange as 3 hundreds 45 ones')],
  'Y3.B9.S3': [R('addition:add_1k_mixed', 'the column addition behind adding amounts')],
  'Y3.B9.S4': [R('subtraction:sub_1k_mixed', 'the column subtraction behind a difference')],
  'Y3.B9.S5': [R('subtraction:sub_wp_100', 'take-away stories: change is a subtraction')],
  'Y3.B10.S8': [R('measurement:time_analog_digital', 'reading the start and end times')],
  'Y3.B10.S9': [R('measurement:time_analog_digital', 'reading the start and end times')],
  'Y3.B10.S10': [R('measurement:time_1min', 'minutes on the clock, the next unit up')],
  'Y3.B10.S12': [R('measurement:elapsed_mixed', 'finding an end time from a duration')],
  'Y3.B11.S9': [R('shapes_early:shape_name_match_3d', 'matching 3-D shapes and their names')],
  'Y3.B11.S10': [R('shapes_early:name_3d_shapes', 'naming the shape made'), R('area_perimeter:net_surface_area', 'nets of 3-D shapes in later years')],
  'Y3.B12.S4': [R('graphs:bar_graph', 'reading the bar chart drawn')],
  'Y3.B12.S5': [R('graphs:bar_graph', 'reading a chart of the data collected')],
  'Y3.B12.S6': [R('graphs:bar_graph', 'the same data as a chart')],
  'Y2.B1.S9': [R('multiplication:count_by_tables', 'counting in 10s from 0, the count the line is marked in')],
  'Y2.B1.S11': [R('measurement:estimate_length', 'estimating a length, the same judging-by-eye'), R('placevalue:compare', 'deciding which number is nearer, the same reasoning as an estimate')],
  'Y2.B2.S1': [R('subtraction:sub_facts', 'the inverse: 10 − 3 = 7 from 3 + 7 = 10')],
  'Y2.B3.S8': [R('shapes_early:shape_attributes', 'describing shapes by their properties'), R('shapes_early:shape_name_match_3d', 'matching 3-D shapes to names by their faces'), R('shapes_early:name_3d_shapes', 'naming the shape whose faces are counted')],
  'Y2.B3.S9': [R('shapes_early:shape_attributes', 'describing shapes by their properties'), R('shapes_early:shape_name_match_3d', 'matching 3-D shapes to names by their properties'), R('shapes_early:name_3d_shapes', 'naming the shape whose edges are counted')],
  'Y2.B4.S1': [R('measurement:money_compare', 'comparing two amounts of coins, the next use of a total')],
  'Y2.B4.S9': [R('subtraction:sub_wp_100', 'take-away stories: change is a subtraction')],
  'Y2.B5.S1': [R('multiplication:mult_word_problems', 'equal groups in stories'), R('division:share_into_groups', 'making equal groups from a total, the inverse view'), R('multiplication:arrays_groups', 'equal groups written as "groups of" sentences, the next idea')],
  'Y2.B5.S2': [R('multiplication:mult_word_problems', 'equal groups in stories'), R('multiplication:dot_array_mult', 'equal groups set out in rows as an array'), R('multiplication:repeated_add_to_mult', 'adding the equal groups made')],
  'Y2.B5.S3': [R('multiplication:mult_facts', 'the multiplication fact the repeated addition becomes')],
  'Y2.B5.S4': [R('multiplication:mult_facts', 'the × facts the symbol is used for'), R('multiplication:arrays_groups', 'the × sentence read from a picture of groups')],
  'Y2.B5.S5': [R('multiplication:mult_word_problems', 'multiplication sentences in stories'), R('multiplication:dot_array_mult', 'the same sentence read from an array')],
  'Y2.B5.S6': [R('multiplication:mult_facts', 'the facts an array shows'), R('multiplication:repeated_add_to_mult', 'an array row by row is a repeated addition')],
  'Y2.B5.S15': [R('measurement:time_fives_ring', 'counting in 5s round a clock face'), R('division:div_facts', 'the inverse: dividing by 5 (Y2.B5.S16)')],
  'Y2.B5.S17': [R('measurement:money_count', 'counting 5-cent and 10-cent coins'), R('division:div_facts', 'the inverse: dividing by 5 and 10')],
  'Y2.B8.S15': [R('multiplication:count_by_tables', 'counting in equal steps from 0, the same count with whole numbers')],
  'Y2.B9.S3': [R('measurement:time_analog_digital', 'the same time written as digits')],
  'Y2.B9.S5': [R('measurement:time_analog_digital', 'matching a clock to its digital time')],
  'Y2.B9.S6': [R('measurement:elapsed_hour', 'durations in hours, where minutes-in-an-hour is used')],
  'Y2.B9.S7': [R('measurement:time_sense', 'which unit of time an activity takes')],
  'Y2.B10.S1': [R('graphs:pictograph', 'the same data shown as a pictogram')],
  'Y2.B10.S7': [R('graphs:bar_graph', 'the same questions read from a bar chart')],
  'Y2.B11.S5': [R('patterns:shape_pattern', 'repeating shape patterns without turns')],
  'Y2.B1.S1': [R('placevalue:expand', 'a teen number written as 10 + 5, the same idea in symbols')],
  'Y2.B1.S5': [R('placevalue:combine', 'the inverse: put the parts back together (50 + 7 = 57)')],
  'Y2.B6.S4': [R('measurement:estimate_length', 'estimating lengths before ordering them')],
  'Y2.B7.S2': [R('number_sense:place_on_number_line', 'a scale is a number line: find the value at the pointer')],
  'Y2.B7.S3': [R('number_sense:place_on_number_line', 'a scale is a number line: find the value at the pointer')],
  'Y2.B7.S6': [R('measurement:capacity', 'capacity units and comparing containers')],
  'Y2.B7.S7': [R('measurement:capacity', 'capacity units: litres and smaller units')],
  'Y2.B7.S9': [R('comparing:compare_objects', 'warmer and colder as comparison language, like longer and shorter')],
  'Y2.B8.S1': [R('fractions:identify', 'naming a part of a whole as a fraction, where parts and wholes lead')],
  'Y2.B8.S3': [R('fractions:identify', 'name the fraction shaded: 1/2 among others')],
  'Y2.B8.S4': [R('patterns:double', 'doubling is the inverse of halving')],
  'Y2.B8.S5': [R('fractions:identify', 'name the fraction shaded, quarters among others')],
  'Y2.B8.S6': [R('fractions:identify', 'name the fraction shaded: 1/4 among others')],
  'Y2.B8.S7': [R('fractions:identify', 'name the fraction shaded, thirds among others')],
  'Y2.B11.S1': [R('coordinates:coordinate_q1', 'describing position on a grid, where this language leads')],
  'Y2.B11.S2': [R('coordinates:geo_translate', 'movement on a grid as a translation (later years)')],
  'Y2.B11.S3': [R('coordinates:geo_rotate', 'turns of a shape as a rotation (later years)')],
  'Y2.B11.S4': [R('coordinates:geo_translate', 'movement on a grid as a translation'), R('coordinates:geo_rotate', 'turns as a rotation')],
};
// self-check r2b: hand pre lists where the filtered week list still gave weak ladders (preOnly = no automatic entries)
export const prePatch = {
  'Y2.B4.S1': { preOnly: true, pre: [R('multiplication:count_by_tables', 'Y2.B1.S15 counting in 2s, 5s and 10s from 0: counting 5-cent and 10-cent coins'), R('measurement:coin_value', 'Y1.B13.S2 recognising coins'), R('counting:count_objects', 'counting a set one by one, for 1-cent coins')] },
  'Y2.B4.S5': { preOnly: true, pre: [R('measurement:make_change_least_coins', 'Y2.B4.S4 choosing coins'), R('measurement:money_count', 'Y2.B4.S1 counting coins'), R('measurement:coin_value', 'Y1.B13.S2 coin values'), R('addition:add_three', 'adding three small numbers (three coins)')] },
  'Y3.B2.S17': { preOnly: true, pre: [R('addition:add_1k_regroup', 'Y3.B2.S13 adding two 3-digit numbers in columns'), R('addition:add_100_regroup', 'Y2.B2.S16 adding two 2-digit numbers across a 10'), R('placevalue:identify', 'Y2.B1.S4 the place of each digit (lining up the columns)'), R('placevalue:value', 'the value of each digit')] },
  'Y3.B2.S19': { preOnly: true, pre: [R('composing:make_ten', 'Y2.B2.S1 bonds to 10: 3 + 7 gives 30 + 70'), R('addition:add_sub_10s', 'Y2.B2.S14 adding and subtracting 10s'), R('placevalue:more_less_10', 'Y2.B2.S13 10 more, 10 less'), R('addition:cloze_addition', 'Y2.B2.S21 missing-number additions')] },
  'Y3.B11.S3': { preOnly: true, pre: [R('angles_lines:identify_angles', 'Y3.B11.S2 right angles: the angle every other is compared with'), R('shapes_early:shape_corners_count', 'Y2.B3.S3 corners (vertices) of 2-D shapes'), R('shapes_early:shape_positions', 'Y2.B11 position and turn language')], preBuild: ['turns'],
    related: [R('angles_lines:angle_types', 'naming acute, right and obtuse angles (the next idea)')] },
  'Y3.B11.S4': { preOnly: true, pre: [R('measurement:estimate_length', 'Y2.B6 choosing and estimating lengths in cm'), R('angles_lines:identify_angles', 'Y3.B11.S2 right angles for drawing a rectangle'), R('shapes_early:count_sides_vertices_2d', 'Y2.B3.S2 sides of 2-D shapes')] },
};

// ======================= round 3 (critic Y2-Y3 r2: S6 pre/related swap, S7 thin measure pre, S8 step fixes) =======================
// r3 entries are merged OVER steps + prePatch. `core` = the main building block (pre tier 1, never pushed out by the cap);
// `dropPre` removes an automatic pre entry that is not a building block.
const C = (key, why) => ({ key, why });
const CBT = 'multiplication:count_by_tables';
export const r3 = {
  // S6: the main building block first
  'Y2.B2.S6': { core: [C('composing:make_ten', 'Y2.B2.S1 bonds to 10: making 10 is the first jump (8 + 5 = 8 + 2 + 3)'), C('composing:number_bonds', 'Y1 bonds within 10: splitting the second number')] },
  'Y2.B5.S13': { core: [C('patterns:seq_10', 'Y2.B1.S15 counting in 10s: the 10 times-table is the count of 10s')] },
  'Y2.B3.S8': { core: [C('shapes_early:name_3d_shapes', 'Y2.B3.S1 naming 3-D shapes (xlsx prior learning: recognise and name 3-D shapes)'), C('shapes_early:shape_name_match_3d', 'Y2.B3.S1 matching a 3-D shape to its name')] },
  'Y2.B3.S9': { core: [C('shapes_early:name_3d_shapes', 'Y2.B3.S1 naming 3-D shapes'), C('shapes_early:shape_name_match_3d', 'Y2.B3.S1 matching a 3-D shape to its name')] },
  'Y2.B3.S10': { core: [C('shapes_early:name_3d_shapes', 'Y2.B3.S1 naming 3-D shapes')] },
  'Y2.B10.S3': { partials: [P('measurement:bar_graph_intro', 'reads a 1-to-1 bar chart (how many, how many more); drawing a block diagram, and blocks stacked as squares (one square = one) rather than bars, are not dealt')],
    build: ['block_diagram'], core: [C('graphs:tally_chart', 'Y2.B10.S1 tally charts: the counts a block diagram shows'), C('measurement:pictograph_intro', 'Y2.B10.S5 one picture = one: the same 1-to-1 idea')] },
  'Y3.B4.S4': { core: [C('placevalue:expand', 'Y2.B1.S8 / Y3.B1.S6 partitioning into tens and ones: 23 × 3 = 20 × 3 + 3 × 3'), C('multiplication:mult_zeros', 'Y3.B4.S1 multiples of 10: 20 × 3')] },
  'Y3.B4.S5': { core: [C('placevalue:expand', 'Y2 "Partition numbers to 100" (xlsx prior learning): 24 × 4 = 20 × 4 + 4 × 4'), C('multiplication:mult_zeros', 'Y3.B4.S1 multiples of 10: 20 × 4')] },
  'Y3.B4.S10': { dropPre: ['division:div_remainders'] },
  'Y3.B12.S5': { core: [C('graphs:tally_chart', 'Y2.B10.S1 tally charts: collecting the data')] },
  'Y3.B12.S6': { core: [C('graphs:tally_chart', 'Y2.B10.S1 tally charts and Y2.B10.S2 tables: a table of counts')] },
  'Y2.B4.S2': { dropPre: ['composing:make_ten', 'addition:add_5_pictures'], core: [C(CBT, 'Y2.B1.S15 counting in 5s and 10s from 0: counting $5 and $10 bills'), C('measurement:money_count', 'Y2.B4.S1 counting coins (kind "like")')] },
  'Y2.B4.S3': { dropPre: ['composing:make_ten', 'addition:add_5_pictures'], core: [C(CBT, 'Y2.B1.S15 counting in 5s and 10s from 0: counting bills and coins'), C('measurement:money_count', 'Y2.B4.S2 counting bills')] },
  'Y2.B4.S4': { core: [C(CBT, 'Y2.B1.S15 counting in 5s and 10s: making an amount from $5 and $10 bills'), C('measurement:money_count', 'Y2.B4.S3 counting bills and coins')] },
  // S8: options that change what is dealt (generated: $5/$10/$20 paid, change $1-$8; Y3 $1/$5 paid, change in dollars and cents)
  'Y2.B4.S9': { direct: [D('measurement:money_change', { currency: 'usd', step: 100, paid: 'note', band: 2000 })],
    core: [C('subtraction:sub_wp_100', 'Y2.B2.S19 take-away stories: change is a subtraction'), C('measurement:money', 'Y2.B4.S7 adding prices')] },
  'Y3.B9.S5': { direct: [D('measurement:money_change', { currency: 'usd', step: 5, paid: 'note' })],
    core: [C('subtraction:sub_1k_mixed', 'Y3.B2.S18 subtracting in columns: change is a subtraction'), C('measurement:money', 'Y3.B9.S3 adding money')] },
  'Y3.B9.S4': { core: [C('subtraction:sub_1k_mixed', 'Y3.B2.S18 subtracting in columns: the calculation behind a difference')] },
  'Y2.B6.S3': { partials: [P('comparing:compare_objects', 'compares pictured objects; comparing two lengths given in the same unit (cm or m) with <, > and = is not dealt'), P('shapes_early:order_objects_length', 'orders pictured objects; no lengths in cm or m')], build: ['compare_measures'] },
  'Y2.B6.S4': { partials: [P('shapes_early:order_objects_length', 'orders pictured objects; ordering three lengths given in the same unit (cm or m) is not dealt')], build: ['compare_measures'] },
  'Y2.B2.S11': { partials: [], verdict: 'gap', build: ['sub_from_ten'], why: { 'addition:add_next_10': 'the proposed bridge-to-10 skill adds to the next 10; it does not subtract from a multiple of 10' } },
  'Y3.B2.S2': { partials: [], verdict: 'gap', build: ['more_less_1_3digit'], removeWhy: 'add_100_no_regroup deals 2-digit + 2-digit (41 + 30, 20 + 52): it never adds ones to a 3-digit number' },
  'Y3.B11.S3': { partials: [P('angles_lines:identify_angles', 'names one angle at a time as acute, right or obtuse (and also deals straight angles, above the step); comparing two angles, or an angle with a right angle, using a right-angle tester is not dealt', { forms: [0] })], build: ['turns_angles'] },
  'Y3.B9.S2': { partials: [P('measurement:money_notation', 'writes "7 dollars 5 cents" or "75 cents" as $7.05 / $0.75; converting a number of cents to dollars and cents and back (345 cents = $3.45, $2.10 = 210 cents) is not dealt', { currency: 'usd', task: 'words' })], build: ['money_convert'] },
  'Y3.B8.S2': { direct: [], partials: [P('fraction_operations:sub_fractions_like', 'subtracts within a whole with a bar picture, but "differences less than 1/2" sort items are mixed in; a page of subtraction only is not available', { denoms: [2, 3, 5] }),
      P('fraction_operations:sub_frac_like_nv', 'forms [0] is plain subtraction, but the compare-to-1/2 sort items are still mixed in and the families deal eighths and tenths', { denoms: [2, 3, 5], forms: [0] })],
    verdict: 'partial', build: ['within_whole'] },
  'Y2.B8.S4': { partials: [], why: { 'fractions:shade_fraction': 'denoms [2] is the halves family: it also deals 4/8 and 5/8, not a page of 1/2 (kept as related)', 'fractions:fraction_of_set': 'ignores denoms in its missing-numerator items (generator bug): cannot be narrowed to halves' }, related: [R('fractions:shade_fraction', 'shading 1/2 of a shape (denoms [2]): the same half shown on a shape'), R('composing:compose_whole', 'two halves make a whole')] },
  'Y2.B8.S6': { partials: [P('fractions:shade_fraction', 'the halves family (1/2, 1/4, 3/4, eighths): a page of quarters only is not available, and a quarter of a quantity (1/4 of 12) is not dealt', { denoms: [2] })] },
  'Y2.B8.S8': { partials: [P('fractions:shade_fraction', 'the thirds family also deals sixths and twelfths: a page of 1/3 of a shape only is not available, and a third of a quantity (1/3 of 12) is not dealt', { denoms: [3] })] },
  // related noise named by the critic: hand related only (relOnly), sharing the idea
  'Y3.B11.S5': { preOnly: true, pre: [R('shapes_early:shape_positions', 'Y2.B11.S1 position language: up and down, left and right are the vertical and horizontal directions'), R('angles_lines:identify_angles', 'Y3.B11.S2 right angles: a horizontal and a vertical line meet at a right angle'), R('angles_lines:symmetry', 'Y2.B3.S5 a vertical line of symmetry: the first vertical line pupils name')],
    preBuild: ['movement'], relOnly: true, related: [R('angles_lines:identify_lines', 'naming parallel and perpendicular lines, the next idea (Y3.B11.S6)'), R('coordinates:coordinate_q1', 'grid lines run horizontally and vertically')] },
  'Y2.B1.S14': { direct: [], partials: [P('placevalue:order_least_to_greatest', 'orders numerals only; ordering objects or base-10 pictures of numbers is not dealt', { band: 99 }), P('placevalue:order_greatest_to_least', 'orders numerals only; objects are not ordered', { band: 99 })],
    verdict: 'partial', build: ['order_pictures'], core: [C('placevalue:compare', 'Y2.B1.S13 comparing two numbers: the step inside ordering')],
    relOnly: true, related: [R('shapes_early:order_objects_length', 'ordering objects by length: the same ordering idea with objects')] },
  'Y2.B3.S6': { relOnly: true, related: [R('coordinates:geo_reflect', 'reflecting a shape in a mirror line (later years): the same idea on a coordinate grid')] },
  'Y3.B2.S19': { relOnly: true, related: [R('measurement:money_change', 'change from $1 (100 cents) is a complement to 100'), R('subtraction:missing_add_sub', '37 + ? = 100 is a missing-number addition')] },
  'Y3.B11.S8': { core: [C('measurement:reading_ruler', 'Y3.B11.S4 measuring and drawing lines accurately with a ruler'), C('shapes_early:name_2d_shapes', 'Y3.B11.S7 recognising and naming 2-D shapes')],
    relOnly: true, related: [R('coordinates:coord_polygon', 'drawing a polygon from its vertices on a grid (later years)')] },
  'Y3.B4.S1': { core: [C('patterns:seq_10', 'Y2.B1.S15 counting in 10s: the multiples of 10 are the 10s count'), C('placevalue:unit_form', 'Y3.B1.S8 ten tens = 1 hundred: 12 tens = 120')] },
  'Y2.B4.S1': { core: [C('patterns:seq_5', 'Y1.B9.S3 counting in 5s: counting 5-cent coins'), C('patterns:seq_10', 'Y1.B9.S2 counting in 10s: counting 10-cent coins')] },
  'Y2.B11.S1': { preOnly: true, pre: [R('shapes_early:name_2d_shapes', 'Y1.B3.S3 naming the shapes whose positions are described'), R('shapes_early:name_3d_shapes', 'Y1.B3.S1 naming the objects (cube, ball) placed on, under, next to'), R('counting:count_objects', 'Y1.B1.S2 counting along a row: "the 3rd from the left"'), R('comparing:compare_objects', 'Y1.B7.S1 comparing words (taller, nearer): the same describing language')] },
  'Y2.B1.S16': { core: [C('patterns:seq_2', 'Y1.B9.S1 / Y2.B1.S15 counting in 2s: counting in equal steps'), C('patterns:seq_5', 'Y1.B9.S3 / Y2.B1.S15 counting in 5s'), C('patterns:seq_10', 'Y2.B1.S15 counting in 10s')], dropPre: ['comparing:compare_groups'] },
  'Y2.B2.S13': { core: [C('patterns:seq_10', 'Y2.B1.S15 counting on and back in 10s'), C('composing:base10_build', 'Y2.B1.S3 tens and ones: one more tens rod is 10 more'), C('placevalue:identify', 'Y2.B1.S4 the tens digit is the digit that changes')] },
  // S7: measurement steps keep a real ladder (rule 15)
  'Y3.B7.S7': { core: [C('measurement:mass_volume_liquid', 'Y2.B7.S6 reading millilitres on a jug (the same skill at Y2, forms [0])')] },
};
// rule 16: every gap step's own missing clause (the step, not the proposal's `teaches`)
export const gapMissing = {
  'Y2.B1.S7': 'partitioning a 2-digit number in more than one way (45 = 40 + 5 = 30 + 15 = 20 + 25) with base-10 and part-whole models',
  'Y2.B2.S8': 'adding the ones that take a 2-digit number to the next multiple of 10 (38 + 2 = 40; 64 + ? = 70)',
  'Y2.B2.S11': 'subtracting a 1-digit number from a multiple of 10 (40 − 3 = 37), exchanging one ten for ten ones',
  'Y2.B3.S4': 'drawing a named 2-D shape (square, rectangle, triangle) on dot or square paper, and drawing a shape from a description of its sides',
  'Y2.B3.S6': 'completing the other half of a shape or pattern across a vertical line of symmetry on a square grid',
  'Y2.B3.S11': 'sorting 3-D shapes by one property (flat or curved faces, rolls or stacks, number of faces) and naming the sorting rule',
  'Y2.B4.S10': 'two-step money stories: add two prices, then find the change or the amount left (buy a $3 and a $4 toy with $10)',
  'Y2.B5.S2': 'making equal groups: arranging a given number of objects into equal groups and drawing them (12 as 3 groups of 4)',
  'Y2.B6.S2': 'measuring lengths and heights in whole metres (a metre stick) and choosing cm or m for an object',
  'Y2.B6.S5': 'adding, subtracting, doubling and halving lengths in cm or m in short stories (a 15 cm tower and one 8 cm taller)',
  'Y2.B7.S4': 'adding, subtracting, multiplying and dividing masses in g or kg in short stories (two 5 kg bags; half of 20 kg)',
  'Y2.B7.S5': 'comparing how much two containers hold, with the words full, empty, half full, nearly full and nearly empty',
  'Y2.B7.S8': 'adding, subtracting, multiplying and dividing capacities in ml or l in short stories (two 250 ml cups; 20 l shared between 4)',
  'Y2.B8.S1': 'naming the parts and the whole of an object, shape or quantity in a part-whole picture, before any fraction is named',
  'Y2.B8.S2': 'deciding whether a shape is split into equal or unequal parts',
  'Y2.B8.S9': 'finding the whole from a given part (half of the cubes is 4: how many cubes in the whole?)',
  'Y2.B8.S15': 'counting on and back in halves and quarters up to one whole (1/4, 2/4, 3/4, 1) on a number line',
  'Y2.B9.S6': 'knowing that an hour has 60 minutes and using it (half an hour = 30 minutes; minutes in 2 hours)',
  'Y2.B9.S7': 'knowing that a day has 24 hours and using it to compare durations (more or less than a day)',
  'Y2.B10.S2': 'reading and completing a simple table of counts (made from a tally) and answering how many / how many more',
  'Y2.B11.S2': 'describing movement on a grid by direction and number of squares (2 squares right, 3 squares up)',
  'Y2.B11.S3': 'describing whole, half, quarter and three-quarter turns, clockwise and anticlockwise, of an object or an arrow',
  'Y2.B11.S4': 'describing a route that combines moves on a grid with turns (forward 3, quarter turn clockwise, forward 2)',
  'Y2.B11.S5': 'continuing and completing a pattern in which a shape turns a quarter or a half turn each time',
  'Y3.B1.S7': 'partitioning a 3-digit number in more than one way (245 = 200 + 45 = 100 + 145 = 240 + 5) with base-10 and part-whole models',
  'Y3.B2.S2': 'adding and subtracting ones (1-9) to and from a 3-digit number without crossing a ten (234 + 5, 238 − 6)',
  'Y3.B2.S5': 'using a known fact to add or subtract tens and hundreds (3 + 4 = 7, so 30 + 40 = 70 and 300 + 400 = 700) and saying which digit changes',
  'Y3.B2.S7': 'adding multiples of 10 that cross a hundred (180 + 30 = 210; 375 + 40 = 415)',
  'Y3.B2.S9': 'subtracting multiples of 10 that cross back over a hundred (210 − 40 = 170; 405 − 20 = 385)',
  'Y3.B2.S19': 'finding the number that makes 100 with a multiple of 10 (30 + ? = 100) and then with any 2-digit number (37 + ? = 100)',
  'Y3.B2.S22': 'choosing a mental strategy or the column method for a given calculation and saying why',
  'Y3.B4.S11': 'finding every combination of two sets systematically (3 tops and 4 bottoms) and seeing the count as 3 × 4',
  'Y3.B5.S3': 'measuring a length on a ruler in cm and mm (4 cm 5 mm)',
  'Y3.B5.S7': 'comparing and ordering lengths given in mm, cm and m, including mixed units (1 m 20 cm vs 125 cm)',
  'Y3.B5.S8': 'adding lengths in the same unit and in mixed units (1 m 20 cm + 50 cm)',
  'Y3.B5.S9': 'subtracting lengths and finding how much longer or shorter, in the same and mixed units (1 m − 35 cm)',
  'Y3.B6.S6': 'reading a value on a scale or number line split into halves, quarters, fifths or tenths of a unit',
  'Y3.B6.S8': 'counting on and back in unit fractions along a number line, past one whole (3/4, 4/4, 5/4)',
  'Y3.B7.S4': 'converting kilograms and grams, including mixed units (1 kg 250 g = 1,250 g)',
  'Y3.B7.S6': 'adding and subtracting masses in g and kg, including mixed units (1 kg 200 g + 500 g)',
  'Y3.B7.S10': 'comparing and ordering capacities given in ml and l (1,200 ml > 1 l) with <, > and =',
  'Y3.B7.S11': 'adding and subtracting capacities in ml and l, including mixed units (1 l 300 ml − 500 ml)',
  'Y3.B8.S3': 'finding the fraction that completes one whole (3/5 + ? = 1) with a part-whole or bar model',
  'Y3.B10.S1': 'reading Roman numerals I to XII, as on a clock face',
  'Y3.B10.S6': 'knowing the months of the year and the days in each month and in a year (and a leap year), and converting years, months and days',
  'Y3.B10.S7': 'converting between days and hours (24 hours in a day; 3 days = 72 hours) and comparing durations',
  'Y3.B10.S10': 'knowing that a minute has 60 seconds, converting minutes and seconds, and comparing short durations',
  'Y3.B10.S11': 'choosing a sensible unit of time and comparing durations given in different units',
  'Y3.B11.S1': 'seeing an angle as an amount of turn, and a quarter turn as a right angle',
  'Y3.B11.S5': 'naming horizontal and vertical lines in shapes, pictures and on a grid',
  'Y3.B11.S8': 'drawing polygons from a name or from given side lengths on dot or square paper, with a ruler',
  'Y3.B11.S10': 'making skeleton 3-D shapes (straws and modelling clay) and matching nets or faces to the shape made',
  'Y3.B12.S5': 'collecting data into a tally chart and choosing a table, pictogram or bar chart to show it',
  'Y3.B12.S6': 'reading and completing two-way tables (rows, columns and totals)',
};
// rule 15: the topic ladder, used only while a step has fewer than 3 pre entries (every entry is earlier learning)
export const ladders = {
  length: [C('measurement:reading_ruler', 'Y2.B6.S1 measuring on a ruler'), C('shapes_early:measure_nonstandard', 'Y1.B7.S2 measuring with cubes and paper clips'), C('comparing:compare_objects', 'Y1.B7.S1 comparing lengths and heights'), C('number_sense:place_on_number_line', 'Y2.B1.S9 a ruler is a number line')],
  mass: [C('measurement:heavier_lighter_visual', 'Y1.B8.S3 / Y2.B7.S1 heavier and lighter'), C('number_sense:place_on_number_line', 'Y2.B1.S9 a scale is a number line: find the value at the pointer'), C(CBT, 'Y2.B1.S15 counting in 2s, 5s and 10s from 0 to read the scale marks'), C('comparing:compare_objects', 'Y1.B7.S1 the compare language (more, less)')],
  capacity: [C('comparing:compare_objects', 'Y1.B7.S1 the compare language (more, less)'), C('number_sense:place_on_number_line', 'Y2.B1.S9 a jug scale is a vertical number line'), C(CBT, 'Y2.B1.S15 counting in 2s, 5s and 10s from 0 to read the jug marks'), C('measurement:heavier_lighter_visual', 'Y2.B7.S1 comparing masses: the same compare idea')],
  temp: [C('number_sense:place_on_number_line', 'Y2.B1.S9 a thermometer is a vertical number line'), C(CBT, 'Y2.B1.S15 counting in 2s, 5s and 10s to read the marks'), C('comparing:compare_objects', 'Y1.B7.S1 the compare language (warmer, colder)')],
  time: [C('measurement:clock_parts', 'the parts of a clock face: hour hand and minute hand'), C('shapes_early:partition_shapes', 'Y1.B10.S1 a half of a shape: half past is half way round'), C(CBT, 'Y2.B1.S15 counting in 5s from 0: the minutes on the clock')],
  stats: [C('graphs:tally_chart', 'Y2.B10.S1 tallying a count'), C('counting:count_objects', 'Y1.B1.S2 counting a set'), C('comparing:compare_groups', 'Y1.B1.S12 more, fewer, the same'), C('comparing:classify_count', 'Y1.B1.S1 sorting objects into groups')],
  position: [C('shapes_early:shape_positions', 'Y1.B11.S4 position words (left, right, above, below)'), C('shapes_early:partition_shapes', 'Y1.B10.S5 quarters: a quarter turn is a quarter of a whole turn'), C('shapes_early:name_2d_shapes', 'Y1.B3.S3 naming the shapes that are moved and turned'), C('counting:count_objects', 'Y1.B1.S2 counting the squares moved')],
  shape: [C('shapes_early:name_2d_shapes', 'Y1.B3.S3 naming 2-D shapes'), C('shapes_early:name_3d_shapes', 'Y1.B3.S1 naming 3-D shapes'), C('shapes_early:shape_corners_count', 'Y2.B3.S3 counting corners')],
};
// rule 5/14: related for steps whose old related entries were earlier steps (now pre): the same idea in another form,
// the inverse, or the next idea
export const relR3 = {
  'Y2.B2.S20': [R('algebra:balance_addsub', '7 + 5 = __ + 3: the two sides of a number sentence balance'), R('number_ops_mixed:which_sign', 'choosing the sign that makes a sentence true')],
  'Y2.B2.S21': [R('algebra:balance_addsub', 'a missing number that makes both sides equal'), R('algebra:tape_diagram', 'a bar model shows the missing part')],
  'Y2.B3.S12': [R('patterns:number_pattern', 'a repeating pattern of numbers: the same rule-spotting')],
  'Y2.B4.S9': [R('addition:comparison_word', 'how many more: the difference behind change'), R('algebra:tape_diagram', 'a bar model: the amount paid split into the price and the change')],
  'Y2.B4.S10': [R('algebra:multi_step_word', 'two-step stories in other contexts'), R('measurement:enough_money', 'is there enough money: the check after a two-step total')],
  'Y2.B5.S12': [R('patterns:skip_count_grid', 'counting in 2s on a grid marks the even numbers')],
  'Y2.B5.S17': [R('patterns:skip_count_line', 'the 5s and 10s as jumps on a number line'), R('measurement:time_fives_ring', 'counting in 5s round a clock face'), R('multiplication:mult_word_problems', 'the 5 and 10 times-tables in stories')],
  'Y2.B6.S3': [R('measurement:estimate_length', 'estimating lengths in cm or m before comparing'), R('measurement:heavier_lighter_visual', 'comparing masses (Y2.B7.S1): the same compare language')],
  'Y2.B7.S2': [R('measurement:temperature', 'a thermometer (Y2.B7.S9): another scale read at a pointer')],
  'Y2.B7.S3': [R('measurement:temperature', 'a thermometer (Y2.B7.S9): another scale read at a pointer')],
  'Y2.B7.S9': [R('number_sense:between_tens', 'which two tens a reading lies between')],
  'Y2.B8.S12': [R('fractions:select_equiv_frac', 'circle the fractions equal to 1/2'), R('fractions:equiv_frac_nv', '1/2 = 2/4 without a picture, the next idea')],
  'Y2.B8.S13': [R('composing:compose_whole', 'three quarters and one more quarter make the whole')],
  'Y2.B8.S14': [R('composing:compose_whole', '3/4 and 1/4 make the whole'), R('fractions:fraction_of_set_nv', 'a fraction of an amount without the picture')],
  'Y2.B8.S15': [R('composing:fraction_number_line', 'reading fractions at points on a line'), R('composing:compose_whole', 'counting quarters up to one whole')],
  'Y2.B11.S5': [R('coordinates:geo_rotate', 'turning a shape as a rotation (later years)'), R('patterns:number_pattern', 'continuing a repeating pattern')],
  'Y3.B1.S13': [R('fractions:order_fractions', 'ordering fractions (Y3.B6): the same ordering idea with another kind of number')],
  'Y3.B2.S22': [R('number_sense:estimate_sum', 'estimating first to judge a method and check the answer'), R('number_sense:compensation', 'a mental strategy: 299 + 50 as 300 + 50 − 1'), R('number_sense:doubles_near_doubles', 'another mental strategy: near doubles (25 + 26)')],
  'Y3.B3.S5': [R('division:nl_div', 'grouping as equal jumps back on a number line'), R('division:div_equation_parts', 'the parts of a division sentence')],
  'Y3.B3.S7': [R('division:nl_div', 'dividing by 3 as jumps on a number line'), R('division:missing_mult_div', '3 × ? = 12: division as a missing factor')],
  'Y3.B3.S8': [R('multiplication:nl_mult', 'the 3 times-table as jumps on a number line'), R('multiplication:mult_word_problems', 'the 3 times-table in stories')],
  'Y3.B3.S9': [R('multiplication:nl_mult', 'multiplying by 4 as jumps on a number line'), R('multiplication:mult_word_problems', 'multiplying by 4 in stories')],
  'Y3.B3.S10': [R('division:nl_div', 'dividing by 4 as jumps on a number line'), R('division:missing_mult_div', '4 × ? = 20: division as a missing factor')],
  'Y3.B3.S11': [R('multiplication:nl_mult', 'the 4 times-table as jumps on a number line'), R('multiplication:mult_div_fact_family', '4 × 3 = 12 and 12 ÷ 4 = 3: the fact family')],
  'Y3.B3.S12': [R('multiplication:nl_mult', 'multiplying by 8 as jumps on a number line'), R('multiplication:mult_word_problems', 'multiplying by 8 in stories')],
  'Y3.B3.S13': [R('division:nl_div', 'dividing by 8 as jumps on a number line'), R('division:missing_mult_div', '8 × ? = 32: division as a missing factor')],
  'Y3.B3.S14': [R('multiplication:mult_div_fact_family', '8 × 3 = 24 and 24 ÷ 8 = 3: the fact family'), R('multiplication:nl_mult', 'the 8 times-table as jumps on a number line')],
  'Y3.B3.S15': [R('multiplication:mult_chart_easy', 'the 2, 4 and 8 rows of a times-table chart side by side'), R('multiplication:mult_div_fact_family', 'fact families across the three tables')],
  'Y3.B4.S10': [R('algebra:tape_diagram', 'a bar model: 3 times as long'), R('multiplication:mult_word_problems', 'multiplication in stories')],
  'Y3.B4.S11': [R('multiplication:mult_chart_easy', 'a times-table chart is a table of combinations: rows × columns')],
  'Y3.B5.S2': [R('measurement:estimate_length', 'choosing mm or cm for an object'), R('measurement:reading_ruler_hard', 'a ruler in cm and mm with harder readings')],
  'Y3.B6.S8': [R('fractions:order_frac_numline', 'placing and ordering fractions on a line'), R('fractions:fraction_nl_drag', 'placing a fraction on the line')],
  'Y3.B6.S9': [R('fractions:select_equiv_frac', 'circle the equivalent fractions'), R('fractions:equiv_frac_nv', 'equivalent fractions without a picture, the next idea')],
  'Y3.B7.S1': [R('measurement:temperature', 'a thermometer: the same scale reading'), R('measurement:reading_ruler_hard', 'a ruler: another scale with intervals')],
  'Y3.B7.S2': [R('measurement:temperature', 'a thermometer: the same scale reading')],
  'Y3.B7.S3': [R('measurement:temperature', 'a thermometer: the same scale reading'), R('measurement:length_metric', 'm and cm: mixed units like kg and g')],
  'Y3.B7.S4': [R('measurement:length_metric', 'converting m and cm: the same exchange with 100'), R('measurement:unit_conversions', 'the same conversion with customary units (ounces and pounds)')],
  'Y3.B7.S5': [R('measurement:money_compare', 'comparing two amounts of money: the same <, > and = with units')],
  'Y3.B7.S6': [R('measurement:money', 'adding amounts of money (Y3.B9.S3): the same calculation with units'), R('algebra:tape_diagram', 'a bar model of two masses and their total')],
  'Y3.B7.S7': [R('measurement:temperature', 'a thermometer: the same scale reading')],
  'Y3.B7.S9': [R('measurement:length_metric', 'converting m and cm: the same exchange with 100'), R('measurement:unit_conversions', 'the same conversion with customary units')],
  'Y3.B7.S10': [R('measurement:money_compare', 'comparing two amounts of money: the same <, > and = with units')],
  'Y3.B7.S11': [R('measurement:money', 'adding amounts of money: the same calculation with units'), R('algebra:tape_diagram', 'a bar model of two capacities and their total')],
  'Y3.B8.S6': [R('fractions:fraction_of_set_hard_nv', 'fractions of amounts without pictures, harder'), R('fraction_operations:mult_frac_whole', 'a fraction of an amount as fraction × whole number (Grade 4)')],
  'Y3.B9.S1': [R('measurement:enough_money', 'is there enough money: reading the amount first'), R('measurement:money_compare', 'comparing two amounts')],
  'Y3.B9.S2': [R('measurement:money_compare', 'comparing two amounts once they are in the same form'), R('measurement:unit_conversions', 'converting a bigger unit into smaller ones (feet to inches): the same idea as dollars to cents')],
  'Y3.B9.S3': [R('measurement:enough_money', 'is there enough: the total compared with what you have'), R('algebra:tape_diagram', 'a bar model of two prices and the total')],
  'Y3.B9.S4': [R('measurement:enough_money', 'is there enough: the difference between what you have and a price'), R('addition:comparison_word', 'how many more: a difference')],
  'Y3.B10.S8': [R('measurement:elapsed_visual_easy', 'elapsed time on a time line'), R('measurement:elapsed_visual_medium', 'elapsed time on a time line, harder')],
  'Y3.B10.S9': [R('measurement:elapsed_visual_easy', 'a duration on a time line'), R('measurement:elapsed_visual_medium', 'a duration on a time line, harder')],
  'Y3.B10.S10': [R('measurement:unit_conversions', 'converting a bigger unit into smaller ones (pounds to ounces): the same idea as minutes to seconds')],
  'Y3.B10.S11': [R('measurement:unit_conversions', 'choosing and converting units of length, mass and capacity: the same idea with time')],
  'Y3.B10.S12': [R('measurement:elapsed_visual_medium', 'durations on a time line'), R('algebra:multi_step_word', 'two-step stories in other contexts')],
  'Y3.B11.S10': [R('area_perimeter:net_surface_area', 'nets of 3-D shapes in later years'), R('shapes_early:compose_shapes', 'building a shape from other shapes')],
  'Y3.B12.S4': [R('graphs:line_plot_g2', 'another way to draw data (Grade 2 line plots)')],
  'Y3.B12.S5': [R('graphs:line_plot_g2', 'another way to show collected data')],
  'Y3.B12.S6': [R('coordinates:coordinate_q1', 'reading a grid by row and column, like a two-way table')],
};
