# Rule 13 (revised 2026-10-10): every partial or gap step names the skill or option still to be made that would make
# it full — SHORT for now: name, kind, teaches (what the pupil does on THIS step), closes, representation.
# name / kind come from the proposal; `teaches` is written per step here; `closes` defaults to the step's missing clause
# (CLOSES gives it per proposal where a step needs two builds); representation is the proposal's, or ENVREP in a few words.
ENVISION = {
 'Y4.B1.S3':  {'nl_20': 'read the number at an arrow and place numbers on 0-1,000 lines counted in 10s, 50s or 100s with some ticks unlabelled, and estimate on a line with only 0 and 1,000 marked'},
 'Y4.B1.S4':  {'regroup_thousands': 'exchange 1 thousand cube for 10 hundred flats and back, and write 1,000 = __ hundreds = __ tens',
               'count_50s': 'count on and back in 1,000s from any multiple of 1,000 to 10,000 (3,000, 4,000, __)'},
 'Y4.B1.S7':  {'flex_partition': 'complete a part-whole model for a 4-digit number split in a non-standard way (3,452 = 2,000 + __ + 52)'},
 'Y4.B1.S8':  {'more_less_all': 'write 1, 10, 100 or 1,000 more or less than a 4-digit number on one mixed page, including across a boundary (3,995 + 10)'},
 'Y4.B1.S9':  {'nl_20': 'read the number at an arrow on 0-10,000 lines counted in 100s, 500s or 1,000s with some labels missing'},
 'Y4.B1.S10': {'nl_20': 'estimate where a number goes, and what number an arrow shows, on a 0-10,000 line with only the ends labelled'},
 'Y4.B1.S13': {'roman_numerals': 'band 100: read a Roman numeral to C and write its value, and write a number to 100 in Roman numerals'},
 'Y4.B2.S1':  {'add_sub_place_units': 'add or subtract a multiple of 1, 10, 100 or 1,000 to a 4-digit number (3,452 + 300), with a place-value chart showing the one column that changes'},
 'Y4.B2.S3':  {'exchange_count_add': 'set exchanges "exactly one": add two 4-digit numbers in columns where exactly one column exchanges'},
 'Y4.B2.S4':  {'exchange_count_add': 'set exchanges "two or more": add two 4-digit numbers in columns with two or more exchanges, including a chain (2,999 + 1,001)'},
 'Y4.B2.S6':  {'exchange_count_sub': 'set exchanges "exactly one": subtract two 4-digit numbers in columns where exactly one column exchanges'},
 'Y4.B2.S7':  {'exchange_count_sub': 'set exchanges "two or more": subtract two 4-digit numbers with two or more exchanges, with and without zeros (5,342 − 2,868; 4,003 − 1,467)'},
 'Y4.B2.S8':  {'mental_add_sub': 'choose and use the quickest method for a 4-digit subtraction (count on for 4,002 − 3,997, constant difference, compensate) and say why',
               'vis_strategy_pictures': 'see the constant-difference shift as two short number lines with matching hops'},
 'Y4.B2.S10': {'inverse_check': 'check a 4-digit addition by subtracting and a subtraction by adding, and check an answer by estimating'},
 'Y4.B3.S1':  {'area_compare': 'compare two surfaces by covering them with squares, and say which covers more'},
 'Y4.B3.S2':  {'area_half_squares': 'count the area of a shape on a grid where some squares are cut in half (two halves make one square)'},
 'Y4.B3.S3':  {'area_compare': 'make two or more different rectilinear shapes from the same number of squares on a grid and write the area of each'},
 'Y4.B3.S4':  {'area_compare': 'count the squares in two or three shapes, write which has the greater area and by how much'},
 'Y4.B4.S6':  {'tables_links': 'use a known 3× fact to find the 6× fact (double) and the 9× fact (triple), and ring the multiples the tables share'},
 'Y4.B4.S12': {'div_by_itself': 'solve n ÷ 1 = __ and n ÷ n = __ from a sharing picture, then as facts only'},
 'Y4.B4.S13': {'mult_three': 'multiply three 1-digit numbers, choosing which two to multiply first (2 × 7 × 5 = 10 × 7)'},
 'Y4.B5.S2':  {'factor_pair_strategy': 'replace one factor by a factor pair to make the product easy (14 × 5 = 7 × 2 × 5 = 7 × 10)'},
 'Y4.B5.S7':  {'scaled_fact_family': 'from 3 × 4 = 12, write the related facts scaled by 10: 30 × 4 = 120, 120 ÷ 4 = 30, 120 ÷ 30 = 4'},
 'Y4.B5.S8':  {'informal_mult': 'multiply a 2-digit by a 1-digit number by partitioning (23 × 4 = 20 × 4 + 3 × 4) and add the parts',
               'vis_array_options': 'see the partition as place-value counters in an array split into tens and ones'},
 'Y4.B5.S11': {'div_exchange': 'set exchange "none": divide a 2-digit number by a 1-digit number where no ten is exchanged (84 ÷ 4, 69 ÷ 3)'},
 'Y4.B5.S12': {'div_exchange': 'set exchange "in the tens": divide a 2-digit number by a 1-digit number exchanging one ten, no remainder (52 ÷ 4)'},
 'Y4.B5.S14': {'correspondence': 'find how many combinations n items make with m items (3 shirts × 4 hats) by listing them in a table, then multiplying'},
 'Y4.B5.S15': {'tables_links': 'use a near multiple or a double to multiply (9 × 7 = 10 × 7 − 7; 8 × 6 = double 4 × 6)',
               'factor_pair_strategy': 'use a factor pair when it is the quickest way (16 × 5 = 8 × 10)'},
 'Y4.B6.S1':  {'km_m': 'choose km or m for a distance, and write a route length as km and m (2 km 300 m) from a map'},
 'Y4.B6.S2':  {'km_m': 'convert km to m and back, including 500 m = 1/2 km and mixed measures (2 km 300 m = 2,300 m)'},
 'Y4.B6.S6':  {'missing_lengths': 'find a missing side of a rectilinear shape from the opposite sides (the two short sides add to the long one)'},
 'Y4.B6.S7':  {'missing_lengths': 'find the missing sides of a rectilinear shape first, then its perimeter'},
 'Y4.B6.S8':  {'regular_polygon': 'find the perimeter of a regular polygon from one marked side (5 sides of 7 cm = 35 cm), and the side from the perimeter',
               'polygons': 'tell whether a polygon is regular, so one side is enough'},
 'Y4.B6.S9':  {'regular_polygon': 'add the side lengths of a pentagon, hexagon or irregular polygon to find its perimeter'},
 'Y4.B7.S2':  {'frac_beyond_1': 'name the mixed number shown by whole and part-shaded shapes (1 1/4) as the count passes 1',
               'frac_count': 'count on in unit fractions past 1 on a line (3/4, 1, 1 1/4, __)'},
 'Y4.B7.S3':  {'frac_beyond_1': 'split a mixed number into wholes and a fraction in a part-whole model (2 3/4 = 2 + 3/4 = 1 + 1 + 3/4)'},
 'Y4.B7.S5':  {'frac_compare_gt1': 'compare two mixed numbers with < > = (whole parts first, then the fractions) and order three or more',
               'frac_beyond_1': 'see the order of mixed numbers on a 0-3 line'},
 'Y4.B7.S7':  {'improper_mixed_dir': 'set direction "to improper": convert a mixed number to an improper fraction (2 3/4 = 11/4), counters ringed into wholes as a fading hint'},
 'Y4.B7.S8':  {'improper_mixed_dir': 'set direction "to mixed": convert an improper fraction to a mixed number (11/4 = 2 3/4) by grouping into wholes'},
 'Y4.B7.S9':  {'frac_nl_equiv': 'read two stacked number lines and write the equivalent fraction at the same point (1/2 = 2/4)',
               'frac_count': 'count along each stacked line in its unit fraction'},
 'Y4.B7.S11': {'frac_add_multi': 'add three or more fractions with the same denominator, totals past 1 (2/5 + 3/5 + 1/5 = 6/5)'},
 'Y4.B7.S14': {'sub_break_whole': 'subtract a fraction from a whole number by renaming one whole (3 − 1/4 = 2 4/4 − 1/4)',
               'frac_add_multi': 'subtract a fraction from a whole as one of the add-and-subtract forms on the same page'},
 'Y4.B8.S1':  {'tenths_only': 'write the tenths shaded in a whole cut into 10 equal parts (3/10), including past 1 (13/10)',
               'frac_count': 'count in tenths on a line past 1'},
 'Y4.B8.S2':  {'dec_fraction_basics': 'write tenths as decimals and back (3/10 = 0.3, 1.3 = 13/10) with a tenths strip'},
 'Y4.B8.S3':  {'decimal_pv': 'read and write a number with tenths from counters in a ones . tenths chart (2 ones and 3 tenths = 2.3)',
               'vis_pv_decimal_places': 'the chart itself: a tenths column after the decimal point'},
 'Y4.B8.S4':  {'dec_nl_past_1': 'place a tenth on a 0-2 or 3-4 line and write the decimal at an arrow'},
 'Y4.B8.S5':  {'div10_small_numbers': 'divide a 1-digit number by 10 on a shift chart (7 ÷ 10 = 0.7), the digit sliding into the tenths'},
 'Y4.B8.S6':  {'div10_small_numbers': 'divide a 2-digit number by 10 on a shift chart (34 ÷ 10 = 3.4)'},
 'Y4.B8.S7':  {'vis_hundred_square': 'read the hundredths shaded in a hundred square',
               'dec_fraction_basics': 'write the shaded hundredths as a fraction (37/100) and count in hundredths'},
 'Y4.B8.S8':  {'dec_fraction_basics': 'write hundredths as decimals and back (37/100 = 0.37, 0.07 = 7/100)',
               'vis_hundred_square': 'shade or read the hundred square that shows it'},
 'Y4.B8.S9':  {'decimal_pv': 'read and write a number to hundredths from counters in a chart, and exchange 10 hundredths for 1 tenth',
               'vis_pv_decimal_places': 'the chart itself: tenths and hundredths columns after the point'},
 'Y4.B8.S10': {'div10_small_numbers': 'divide a 1- or 2-digit number by 100 on a shift chart (7 ÷ 100 = 0.07, 34 ÷ 100 = 0.34)'},
 'Y4.B9.S1':  {'decimal_whole': 'find the tenths that make 1 whole (0.3 + __ = 1) with a tenths strip'},
 'Y4.B9.S2':  {'decimal_whole': 'find the hundredths that make 1 whole (0.36 + __ = 1)',
               'vis_hundred_square': 'a hundred square shaded in two tones as the model'},
 'Y4.B9.S3':  {'decimal_pv': 'partition a decimal into ones, tenths and hundredths (3.45 = 3 + 0.4 + 0.05) from a place-value chart'},
 'Y4.B9.S4':  {'decimal_pv': 'partition a decimal in a second way in a part-whole model (3.45 = 3.4 + 0.05 = 2 + 1.45)'},
 'Y4.B9.S5':  {'dec_same_whole': 'compare two decimals with the same whole part and 1 or 2 places (0.4 vs 0.38) with < > =',
               'dec_compare_model': 'shade both on hundred squares, then compare'},
 'Y4.B9.S6':  {'dec_same_whole': 'order three to five decimals that share the whole part (3.6, 3.65, 3.06), least to greatest or back'},
 'Y4.B9.S7':  {'round_whole': 'round a decimal with 1 or 2 places to the nearest whole number',
               'vis_round_line_decimals': 'on a number line between the two wholes, bounds circled'},
 'Y4.B9.S8':  {'dec_fraction_basics': 'write 1/2, 1/4 and 3/4 as 0.5, 0.25 and 0.75 (and back) from a hundred square'},
 'Y4.B10.S2': {'money_convert': 'convert cents to dollars and cents and back (345¢ = $3.45)'},
 'Y4.B10.S3': {'money_compare_written': 'compare and order amounts written in $ and ¢ ($2.35 vs 189¢) by changing to one unit first'},
 'Y4.B10.S4': {'money_estimate': 'round each price to the nearest dollar to estimate a total or the change'},
 'Y4.B10.S6': {'money_2step': 'solve a two-step money story: buy two or three items, then find the change from a note'},
 'Y4.B11.S1': {'time_calendar': 'convert between years, months, weeks and days (3 weeks = __ days) using a calendar page and a conversion table'},
 'Y4.B11.S2': {'time_calendar': 'convert seconds to minutes and back, mixed units (1 min 20 s = 80 s), and compare two durations given in different units'},
 'Y4.B11.S4': {'time_24h_convert': 'write a 12-hour time with a.m. or p.m. as a 24-hour time (3:15 p.m. = 15:15)'},
 'Y4.B11.S5': {'time_24h_convert': 'write a 24-hour time as a 12-hour time with a.m. or p.m. (19:40 = 7:40 p.m.)'},
 'Y4.B12.S1': {'turns_angles': 'say how far an arrow turns (quarter, half, three-quarter, whole), clockwise or anticlockwise, and that a quarter turn is a right angle'},
 'Y4.B12.S3': {'turns_angles': 'compare and order two or three angles by size, whatever the length of their arms'},
 'Y4.B12.S6': {'polygons': 'name a polygon by its sides (pentagon … octagon) and tick regular or irregular'},
 'Y4.B12.S8': {'symmetry_complete': 'complete a shape on a square grid by reflecting it in a given line'},
 'Y4.B13.S3': {'line_graph': 'read a line graph: the value at a time, the change between two times, and when it was greatest'},
 'Y4.B13.S4': {'line_graph': 'draw a line graph from a table: label the axes, plot each point, join them with straight lines'},
 'Y4.B14.S3': {'coord_polygon_draw': 'plot given vertices and join them to draw a shape, and find the missing vertex of a square or rectangle'},
 'Y4.B14.S4': {'translate_grid': 'translate a point or shape on a first-quadrant grid (3 right, 2 up), draw it, and write the new coordinates'},
 'Y4.B14.S5': {'translate_grid': 'describe the translation from a shape to its image ("__ right, __ up")'},
}
CLOSES = {
 'Y4.B1.S4':  {'regroup_thousands': '1,000 = 10 hundreds as an exchange', 'count_50s': 'counting in 1,000s within 10,000'},
 'Y4.B2.S8':  {'vis_strategy_pictures': 'the picture of a constant-difference shift'},
 'Y4.B5.S8':  {'vis_array_options': 'the place-value-counter array picture'},
 'Y4.B5.S15': {'tables_links': 'doubling and near multiples', 'factor_pair_strategy': 'factor pairs as a choice'},
 'Y4.B6.S8':  {'regular_polygon': 'perimeter as side × number of sides, and the side from the perimeter', 'polygons': 'knowing a shape is regular'},
 'Y4.B7.S2':  {'frac_beyond_1': 'naming the mixed number', 'frac_count': 'counting past 1 on a line'},
 'Y4.B7.S5':  {'frac_compare_gt1': 'comparing and ordering mixed numbers', 'frac_beyond_1': 'mixed numbers on a line as the model'},
 'Y4.B7.S9':  {'frac_nl_equiv': 'equivalent fractions on stacked lines', 'frac_count': 'counting in unit fractions along a line'},
 'Y4.B7.S14': {'sub_break_whole': 'renaming one whole to subtract', 'frac_add_multi': 'whole − fraction as an item form'},
 'Y4.B8.S1':  {'tenths_only': 'tenths only, written n/10, past 1', 'frac_count': 'counting in tenths on a line'},
 'Y4.B8.S3':  {'decimal_pv': 'reading and writing tenths from counters', 'vis_pv_decimal_places': 'the tenths column in the chart'},
 'Y4.B8.S7':  {'vis_hundred_square': 'the hundred-square model', 'dec_fraction_basics': 'hundredths written as fractions'},
 'Y4.B8.S8':  {'dec_fraction_basics': 'hundredths both ways, held to hundredths', 'vis_hundred_square': 'the hundred-square model'},
 'Y4.B8.S9':  {'decimal_pv': 'hundredths from counters and the exchange of 10 hundredths', 'vis_pv_decimal_places': 'the hundredths column in the chart'},
 'Y4.B9.S2':  {'decimal_whole': 'complements to 1 in hundredths', 'vis_hundred_square': 'the two-tone hundred square'},
 'Y4.B9.S5':  {'dec_same_whole': 'comparing with the same whole part', 'dec_compare_model': 'reasoning with hundred squares'},
 'Y4.B9.S7':  {'round_whole': 'rounding to the nearest whole', 'vis_round_line_decimals': 'the decimal rounding line'},
}
ENVREP = {
 'vis_strategy_pictures': 'two short number lines with matching hops',
 'vis_array_options': 'an array of place-value counters split into tens and ones',
 'vis_hundred_square': 'a 10 × 10 hundred square as one whole, shade or read',
 'vis_pv_decimal_places': 'the pv chart with tenths and hundredths columns after the point',
 'vis_round_line_decimals': 'a rounding line between two wholes, bounds circled',
}
ENVISION.update({
 'Y4.B7.S12': {'frac_add_multi': 'add a proper fraction to a mixed number (2 1/5 + 3/5 = 2 4/5), with a bar model as a fading hint'},
 'Y4.B7.S15': {'sub_break_whole': 'set breaking "never": subtract mixed numbers where the fraction parts subtract without an exchange (3 4/5 − 1 2/5)'},
 'Y4.B14.S1': {'coord_forms_fix': 'read the coordinates of drawn points on a first-quadrant grid, every item, on screen and on paper'},
 'Y4.B14.S2': {'coord_forms_fix': 'plot given points on a first-quadrant grid, every item, on screen and on paper'},
})
ENVREP['dec_compare_model'] = 'two hundred squares side by side with a sign box between them'
ENVISION.update({
 'Y4.B7.S4':  {'mixed_nl_read': 'write the mixed number an arrow points to on a 0-3 line (2 1/4), and place mixed numbers, with one on every item'},
 'Y4.B7.S1':  {'whole_nn_only': 'write one whole as a fraction from a shape cut into equal parts (1 = 6/6), and say how many parts make the whole'},
 'Y4.B7.S13': {'frac_answer_as_is': 'subtract two fractions with the same denominator and keep that denominator in the answer (5/8 − 3/8 = 2/8)'},
 'Y4.B9.S4':  {'flex_partition': 'decimal band: partition a decimal in a second way in a part-whole model (3.45 = 3.4 + 0.05 = 2 + 1.45)'},
})
