// build-specs.js — the build spec of every White Rose (WRM_PROPOSALS, js/modules/wrm.js) proposal,
// so the unified build list (js/modules/build-list.js, design/BUILD_LIST.md) carries a full spec for
// every new skill and option, whichever audit found it (owner request 2026-09-25: "design new skills
// to cover them all").
//
// A pure data module. It is NOT imported by the app (globals.js); only the build list and the gates
// read it. Keyed by the WRM proposal id. The grade, the CCSS codes and the Essential Elements are not
// repeated here: build-list.js derives them from the proposal's WRM small steps (Year N = US grade
// N-1) and adds the codes the standards audit (js/modules/standards-audit.js) sends to it.
//
// Fields (S(...) below):
//   problemTypes   3-5 item kinds the skill deals (the research model: identify, compare, make, fill,
//                  reason). Every kind is written for our page: one boxed cell, B&W, Andika, low
//                  writing load (PEDAGOGY_STANDARD P-1 ... P-9).
//   templates      existing sheet-kit templates (js/modules/sheet/cells/*) the cell is drawn with.
//   newTemplates   kit templates this skill needs that do not exist yet (see build-list.js
//                  NEW_TEMPLATES for their owner lane).
//   answer         the written response on paper; the screen host takes the same response
//                  (a production item is never turned into multiple choice on screen).
//   ladder         the option ladder in OPTIONS-RUBRIC terms: O2 difficulty, O3 support (hint
//                  scaffolds fade, structure stays), O6 appearance. O1/O4/O5 are graded on the
//                  built panel, not specified here.
//   misconceptions the 2-4 real errors (they feed error-analysis, True or False? and Reason It pages).

const S = (problemTypes, templates, answer, ladder, misconceptions, newTemplates = []) =>
    ({ problemTypes, templates, newTemplates, answer, ladder, misconceptions });

export const WRM_SPECS = {
    // ------------------------------------------------------------------ algebra
    pattern_make: S(['copy a repeating pattern', 'continue it (next 2-3)', 'circle the repeating unit', 'find the mistake in a pattern', 'make your own AB / ABB pattern'],
        ['wordpic'], 'draw or write the letter of the next shape in each box', 'O2 AB → ABB → ABC → growing unit length · O3 unit boxed and shaded → unit boxed → none · O6 shapes / pictures / letters',
        ['repeats only the last item', 'treats AB and ABB as the same', 'restarts the unit mid-row'], ['picture-row']),
    count_50s: S(['count on in 50s / 100s / 1,000s', 'count back', 'fill a missing term', 'how many 100s make 1,000?'],
        ['count-row', 'base10'], 'write the missing numbers', 'O2 step 100 → 50 → 1,000, forwards then backwards · O3 base-10 picture above each term → none · O6 track / number line',
        ['changes the wrong digit (350 + 50 = 355)', 'forgets the crossing of 1,000 (950, 1,000, 1,050)']),
    function_machine: S(['find the output', 'find the input (work backwards)', 'find the rule from pairs', 'two-step machine'],
        ['function-table'], 'write the number in the empty box; write the rule', 'O2 one step (+ −) → one step (× ÷) → two steps · O3 inverse arrow drawn → none · O6 machine picture / table',
        ['applies the rule forwards when working backwards', 'reads a two-step machine in the wrong order']),
    formulae: S(['substitute into a word formula', 'substitute into a letter formula', 'which formula fits the picture?', 'find a missing value'],
        ['equation', 'function-table'], 'write the value', 'O2 one operation → two operations → brackets and powers (V = s³) · O3 substitution line printed (P = 2 × ( __ + __ )) → none · O6 formula in words / letters',
        ['adds instead of multiplying where letters touch (2l = 2 + l)', 'ignores the brackets'], ['expression']),
    pairs_values: S(['list all pairs for a + b = n', 'list pairs for 2a + b = n', 'find the pair that fits two clues', 'bar-model problem with two unknowns'],
        ['function-table'], 'write the pairs in a two-column table', 'O2 a + b ≤ 10 → 2a + b → two clues · O3 first rows of the table filled, in order → none · O6 table / bar model',
        ['stops before listing every pair', 'lists a pair twice (3,5 and 5,3 when order does not matter)'], ['data-table', 'bar-model']),

    // ------------------------------------------------------------------ counting
    match_same: S(['match identical pictures', 'match picture to object silhouette', 'find the one that is the same', 'match by one attribute'],
        ['wordpic'], 'draw a line between each matching pair', 'O2 2 → 3 → 4 pairs; identical → same kind different look · O3 first pair joined → none · O6 objects / shapes',
        ['matches by colour or size instead of kind', 'uses one picture twice'], ['picture-row']),
    odd_one_out: S(['circle the one that does not belong', 'say why (word bank)', 'find the one that belongs to the set', 'two rules at once'],
        ['wordpic'], 'circle one picture; tick the reason from a bank', 'O2 kind → colour-free attribute (size, shape) → two attributes · O3 reason bank shown → none · O6 objects / shapes',
        ['chooses by position (always the last)', 'picks a reason that fits every picture'], ['picture-row']),
    sort_groups: S(['sort by a given rule', 'find the rule of a sort', 'count each group and say which has most', 'order the groups by count', 'sort by big/small or heavy/light'],
        ['wordpic', 'counters'], 'write each tile letter in its ring; write how many in each group', 'O2 2 groups → 3 groups → rule found by the pupil → order the groups · O3 first tile placed, labels with pictures → words only · O6 rings / Carroll boxes',
        ['sorts by two attributes at once', 'leaves tiles unsorted', 'counts a tile in two rings'], ['sort-rings', 'picture-row']),
    subitise: S(['say how many (dots, dice, fingers)', 'how many on the ten frame?', 'see the two parts (3 and 2)', 'match patterns with the same number'],
        ['counters', 'tenframe'], 'write the number; write the two parts', 'O2 0-3 → 0-5 → to 10 (conceptual) · O3 screen flash time long → short; parts ringed → none · O6 dots / dice / fingers / frame',
        ['counts one by one', 'confuses 4 and 5 dice patterns', 'forgets zero is a number']),
    zero: S(['how many? (including none)', 'write 0 for an empty set', 'which plate has none?', 'take all away: how many are left?'],
        ['counters', 'wordpic'], 'write the number, 0 included', 'O2 0-3 → 0-5 → 0-10 · O3 empty plate shaded → plain · O6 plates / boxes / ten frames',
        ['writes nothing for zero', 'writes 1 for an empty set', 'reads 0 as the letter O']),
    consolidate: S(['count and write', 'compare two groups', 'make 5 / make 10', 'continue the pattern', 'number before / after'],
        ['counters', 'tenframe', 'compare', 'bond', 'seqstrip'], 'as each member skill', 'O2 the pool\'s members at to 5 / to 10 · O3 the members\' own support levels · O6 as the members',
        ['depends on the drawn member (see its skill)']),
    words_0_10: S(['numeral to word', 'word to numeral', 'match the word to the picture count', 'spell the missing letters'],
        ['wordpic'], 'write the numeral or copy the word from a bank', 'O2 0-5 → 0-10 · O3 word bank with pictures → bank only → none · O6 word bank / trace',
        ['writes the word for the next number', 'confuses six/seven, two/three spellings']),
    teen_structure: S(['build 10 on a ten frame', 'build 20 on two frames', '10 is one ten; 20 is two tens', 'how many tens and ones?'],
        ['tenframe', 'counters'], 'write the number / tens and ones', 'O2 10 → 20 → mix with 11-19 · O3 frames drawn full → partly → none · O6 frames / rods',
        ['calls 20 "twelve"', 'counts the ten as 1']),
    ordinal: S(['circle the 3rd', 'write the position of the star', 'match 1st to first', 'who is before / after the 5th?'],
        ['wordpic'], 'circle, or write the ordinal (1st, 2nd …) from a bank', 'O2 1st-3rd → 1st-5th → 1st-10th · O3 start flag and numbers under each place → flag only · O6 children / objects',
        ['counts from the wrong end', 'writes 2th, 3th']),
    ten_count_out: S(['circle exactly n from a larger group', 'count out 1-3 from a set (EE)', 'count out to 20, then to 30', 'is it exactly n? tick'],
        ['counters'], 'circle the objects; write how many you circled', 'O2 1-3 → to 10 → to 20 → to 30 · O3 objects in a line → scattered; touch dots → none · O6 objects / counters',
        ['keeps counting past n', 'counts an object twice']),
    tens_ones_group: S(['ring groups of ten and write tens and ones', 'how many tens? how many ones?', 'write the number', 'which picture shows 34?'],
        ['counters', 'base10'], 'write ___ tens ___ ones = ___', 'O2 to 30 → to 50 → to 100 · O3 tens pre-ringed → first ten ringed → none · O6 objects / sticks / dots',
        ['counts every object instead of grouping', 'writes the ones before the tens (43 for 34)']),
    count_3s: S(['count on in 3s', 'count back in 3s', 'fill the missing 3s', 'jumps on the number line'],
        ['count-row', 'hop-line'], 'write the missing numbers', 'O2 to 15 → to 36; forwards → backwards · O3 hops drawn → none · O6 track / line',
        ['adds 2 or 4 at the crossing of a ten', 'loses the count after 12']),

    // ------------------------------------------------------------------ data
    table_data: S(['read a table', 'complete a table from a tally', 'total a row', 'answer a comparison question'],
        ['legacy'], 'write the missing numbers; one short answer', 'O2 2 rows → 4 rows → totals · O3 first row filled → none · O6 table / tally + table',
        ['reads the wrong row', 'counts tallies of 5 as 4'], ['data-table']),
    block_diagram: S(['count the blocks in a column', 'build the diagram (colour squares)', 'how many more?', 'scale in 2s'],
        ['legacy'], 'write the count; colour the squares', 'O2 scale 1 → 2 · O3 grid numbered → axis only · O6 vertical / horizontal',
        ['counts the grid lines, not the blocks', 'ignores the scale of 2'], ['graph-axes']),
    pictogram_scale: S(['read a pictogram with a key of 2, 5 or 10', 'read half and quarter pictures', 'draw the pictogram from a table', 'how many more?'],
        ['legacy'], 'write the value; draw the pictures', 'O2 key 1 → 2 → 5 → 10 → half pictures · O3 key repeated beside every row → key once · O6 icons / circles',
        ['counts each picture as 1', 'draws a whole picture for 5 when the key is 10'], ['graph-axes']),
    two_way: S(['read a two-way table', 'complete the missing cells', 'find a row or column total', 'answer a combined question'],
        ['legacy'], 'write the missing numbers', 'O2 2×2 → 3×3 with totals · O3 one total given → none · O6 table only',
        ['adds across the totals row', 'reads the wrong header'], ['data-table']),
    collect_data: S(['tally a list of data', 'turn the tally into a table', 'draw a pictogram or bar chart', 'choose the best display'],
        ['legacy'], 'tally marks, a table, then a drawn chart', 'O2 10 items → 20 → 30 · O3 categories given → pupil finds them · O6 pictogram / bar chart',
        ['misses an item', 'tallies five as five upright strokes'], ['data-table', 'graph-axes']),
    line_graph: S(['read a value', 'find the change between two times', 'when was it highest?', 'plot the points and join them'],
        ['legacy'], 'write the value / the difference; plot', 'O2 scale 1 → 2 → 5 → 10; read → plot · O3 gridlines to the axis dashed → none · O6 with / without points',
        ['reads the next gridline', 'joins points in size order not time order'], ['graph-axes']),
    dual_bar: S(['read both bars', 'compare the two sets', 'find the total of one category', 'draw the dual bars'],
        ['legacy'], 'write the value / the difference', 'O2 read → compare → draw · O3 key with patterns labelled on bars → key only · O6 hatched / plain',
        ['mixes up the key', 'compares across categories'], ['graph-axes']),
    pie: S(['read a pie chart in fractions', 'read it in percentages', 'find the amount from the total', 'draw from angles'],
        ['frac-model'], 'write the fraction, percent or amount', 'O2 halves/quarters → tenths/percent → angles (360°) · O3 sector lines at 10% → none · O6 fraction / percent labels',
        ['treats a sector as a count', 'uses 100 instead of 360 for degrees'], ['graph-axes']),

    // ------------------------------------------------------------------ decimals
    decimal_pv: S(['write the decimal shown by counters', 'place a decimal in the chart', 'partition 0.36 = 0.3 + 0.06', 'flexible partition (0.36 = 0.2 + 0.16)', 'value of a digit in tenths and hundredths'],
        ['pv', 'pv-support', 'base10'], 'write the decimal / the parts', 'O2 tenths → hundredths → flexible · O3 chart headings with counters → headings only → none · O6 counters / base-10 (flat = 1) / chart',
        ['writes 0.6 for 6 hundredths', 'thinks 0.36 has 36 tenths']),
    decimal_whole: S(['make 1 with tenths', 'make 1 with hundredths', 'what is missing from 0.45?', 'bond pairs to 1'],
        ['bond', 'frac-model'], 'write the missing part', 'O2 tenths → hundredths (multiples of 5) → any hundredths · O3 hundred square shaded → strip → none · O6 strip / hundred square / bond',
        ['0.45 + 0.65 = 1 (makes 10 in each place)', 'answers 0.55 → 0.65 by adding 1 to tenths']),
    round_whole: S(['round a 1-dp decimal to the nearest whole', 'round a 2-dp decimal', 'mark it on a number line first', 'halfway cases (2.5)'],
        ['number-line', 'pv'], 'write the whole number', 'O2 1 dp → 2 dp; not halfway → halfway · O3 number line from whole to whole → none · O6 line / chart',
        ['rounds to the nearest tenth instead', 'rounds 2.45 up because of the 5']),
    thousandths_pv: S(['thousandths as fractions (x/1000)', 'thousandths as decimals', 'place in a chart to thousandths', 'read and write the number name', 'expanded form with fractions (3 × 1/10 + 9 × 1/100)'],
        ['pv', 'pv-support'], 'write the decimal, fraction, words (bank) or expanded form', 'O2 x/1000 → mixed places → words and expanded · O3 chart headings → none · O6 chart / counters',
        ['0.034 read as thirty-four tenths', 'writes 0.34 for 34 thousandths']),
    dec_known_facts: S(['use a whole fact for tenths (3 + 4 → 0.3 + 0.4)', 'subtract with a known fact', 'complements to 1', 'choose an efficient strategy'],
        ['fact', 'bond'], 'write the answer', 'O2 tenths → hundredths → crossing 1 · O3 the whole fact printed beside → none · O6 fact pair / bond',
        ['0.3 + 0.4 = 0.07', 'forgets to exchange 10 tenths for 1']),
    dec_sequence: S(['continue a decimal sequence', 'find the rule', 'fill a missing term', 'decreasing sequences'],
        ['count-row'], 'write the terms and the rule', 'O2 step 0.1 → 0.2 / 0.5 → 0.25; up → down · O3 step arrows drawn → none · O6 track / number line',
        ['0.9 + 0.1 = 0.10', 'keeps the step in the wrong place (+0.01)']),
    ratio_fraction: S(['write the ratio as a fraction of the whole', 'bar model: parts for each', 'find an amount from a ratio', 'fraction to ratio'],
        ['frac-model'], 'write the fraction or the amount', 'O2 small totals → larger · O3 bar drawn and split → none · O6 bar / counters',
        ['3 : 2 means 3/2', 'uses a part as the whole'], ['bar-model']),
    dec_pv_within1: S(['value of each digit to thousandths', 'numbers with integer and decimal parts', 'partition 4.305', 'which digit is worth 5 hundredths?'],
        ['pv', 'pv-support'], 'write the value or the digit', 'O2 within 1 → integer parts → zeros inside · O3 chart headings → none · O6 chart / expanded',
        ['ignores a zero place', 'reads the decimal part as a whole number']),
    dec_context: S(['money word problems × ÷ integer', 'measure word problems', 'which calculation?', 'two-step problem'],
        ['word-work'], 'write the answer with its unit', 'O2 × by 1-digit → ÷ by 1-digit → two steps · O3 bar model and cues → none · O6 pictures / plain',
        ['puts the decimal point in the wrong place', 'divides the wrong way round']),
    percent_multi: S(['percent of an amount in two steps (10% then 30%)', 'increase / decrease', 'what percent is 12 of 40?', 'missing whole'],
        ['word-work'], 'write the amount or the percent', 'O2 10%, 50% → multiples of 10% → any · O3 bar split into 10% parts → none · O6 bar / table',
        ['adds the percent as a number (40 + 30% = 70)', 'finds 30% and stops for an increase'], ['bar-model']),

    // ------------------------------------------------------------------ fractions
    half_quarter: S(['shade a half / a quarter of a shape', 'circle half / a quarter of a set', 'are the parts equal? tick', 'the whole is two halves / four quarters', 'which is bigger: a half or a quarter?'],
        ['frac-model', 'counters'], 'shade, circle or tick; words half / quarter from a bank', 'O2 half → quarter → mix; shapes → quantities · O3 cut lines drawn → none · O6 shapes / objects',
        ['any two parts is a half', 'a quarter is bigger because 4 > 2']),
    fraction_parts: S(['equal or not equal? tick', 'draw the whole from a part', 'how many parts? are they equal?', 'thirds: the whole is three thirds', 'same size, different shape'],
        ['frac-model'], 'tick, count or draw', 'O2 halves → thirds → quarters; draw the whole · O3 grid under the shape → none · O6 shapes / strips',
        ['counts parts without checking they are equal', 'thinks equal parts must look the same']),
    frac_count: S(['count up in unit fractions', 'count past a whole (3/4, 1, 1 1/4)', 'fill missing ticks on a line', 'equivalent fractions at the same point', 'count down'],
        ['number-line', 'count-row'], 'write the missing fractions', 'O2 within 1 → past 1 → mixed numbers · O3 all ticks labelled → some → ends · O6 line / track',
        ['counts 1/4, 2/4, 3/4, 4/4, 5/4 without naming 1', 'adds to the denominator (1/4, 1/5, 1/6)']),
    frac_whole: S(['how many quarters make a whole?', 'how many more parts make 1?', 'find the whole from a part', '4/4 = 1'],
        ['frac-model'], 'write the number of parts / the fraction', 'O2 halves → eighths · O3 bar drawn and cut → none · O6 bar / circle',
        ['counts shaded parts only', 'thinks the whole has the shaded number of parts'], ['bar-model']),
    frac_scales: S(['read a scale in halves', 'read quarters, fifths, tenths', 'mark a fraction on a scale', 'which reading is larger?'],
        ['number-line'], 'write the reading as a fraction or mixed number', 'O2 halves → quarters → fifths/tenths · O3 every tick labelled → wholes only · O6 ruler / jug / line',
        ['counts ticks not spaces', 'reads the scale as tenths every time'], ['measure-scale']),
    frac_whole_partition: S(['what completes the whole? (1 − 3/5)', 'part-whole model with fractions', 'bar model missing part', 'more than one whole'],
        ['bond', 'frac-model'], 'write the missing fraction', 'O2 halves → fifths → eighths; within 1 → 2 · O3 bar cut into parts → none · O6 bar / bond',
        ['subtracts the denominators', 'writes the shaded part again'], ['bar-model']),
    frac_amount_wp: S(['find a part of an amount (bar model)', 'find the whole from a part', 'compare two fractions of amounts', 'story with a fraction of an amount'],
        ['word-work', 'frac-model'], 'write the missing value', 'O2 unit fractions → non-unit → find the whole · O3 bar split and labelled → none · O6 bar / plain',
        ['divides by the numerator', 'multiplies the amount by the denominator'], ['bar-model']),
    frac_beyond_1: S(['count beyond 1 in fractions', 'wholes and a fraction (partition a mixed number)', 'mixed number on a number line', 'improper and mixed together'],
        ['frac-model', 'number-line'], 'write the mixed number or improper fraction', 'O2 halves → quarters → eighths; to 2 → to 5 · O3 wholes shaded solid → none · O6 bars / circles / line',
        ['writes 1 1/4 as 11/4', 'counts all parts as the denominator']),
    frac_add_multi: S(['add three fractions, same denominator', 'add a fraction to a mixed number', 'subtract from a whole (3 − 3/4)', 'total past 1'],
        ['frac-model'], 'write the answer', 'O2 two addends → three → from a whole · O3 bar model → none · O6 bar / numbers',
        ['adds the denominators', '3 − 3/4 = 3/4']),
    frac_compare_gt1: S(['compare improper fractions', 'compare mixed numbers', 'order improper and mixed', 'mixed vs improper'],
        ['number-line', 'frac-model'], 'write <, > or =; order', 'O2 same denominator → related denominators · O3 number line 0-3 → none · O6 line / bars',
        ['compares only the whole numbers', 'thinks a bigger denominator means bigger']),
    sub_break_whole: S(['subtract by exchanging a whole', 'bar model exchange', 'which is harder: 3 4/5 − 1/5 or 3 1/5 − 4/5?', 'find the mistake'],
        ['frac-model'], 'write the answer', 'O2 halves → fifths → eighths · O3 exchanged whole drawn → none · O6 bar / numbers',
        ['subtracts the smaller fraction from the larger (3 1/5 − 4/5 = 3 3/5)', 'takes 1 whole but forgets to add its parts']),
    mult_mixed_int: S(['mixed number × integer', 'story with a mixed number of a unit', 'repeated addition of a mixed number', 'bar model'],
        ['frac-model', 'word-work'], 'write the answer as a mixed number', 'O2 halves → other; × 2-5 · O3 repeated addition written → none · O6 bars / numbers',
        ['multiplies the whole only', 'forgets to regroup improper parts']),
    frac_operator: S(['2/5 of 30 by ÷ then ×', 'the same fraction three ways (1/4 of 20 = 20 ÷ 4 = 20 × 1/4)', 'fraction of a measure', 'which calculation matches?'],
        ['frac-model'], 'write the calculation and the answer', 'O2 unit → non-unit → measures · O3 bar with operator arrows → none · O6 bar / arrows',
        ['multiplies by the denominator', 'divides by the numerator']),
    frac_nl_equiv: S(['equivalent fractions at one point on two lines', 'same point on the number line?', 'write the equivalent from stacked lines', 'find the matching tick'],
        ['number-line', 'frac-model'], 'write the fraction', 'O2 halves/quarters → thirds/sixths → eighths · O3 dashed line across the stacked lines → none · O6 stacked lines / bars',
        ['thinks more ticks mean a bigger number', 'matches numerators']),
    compare_numerator: S(['same numerator: which is greater?', 'unit fractions (1/3 vs 1/5, EE)', 'order by numerator', 'same whole? can we compare?'],
        ['frac-model', 'compare'], 'write <, > or =', 'O2 unit fractions → same numerator → mixed · O3 bars under each → none · O6 bars / circles',
        ['1/5 > 1/3 because 5 > 3', 'compares fractions of different wholes']),
    frac_multistep: S(['two-step story adding then subtracting fractions', 'unlike denominators in context', 'bar model steps', 'find the missing part of a whole'],
        ['word-work'], 'write each step answer', 'O2 like → unlike denominators · O3 bar model with steps → none · O6 bar / plain',
        ['answers the first step only', 'adds denominators'], ['bar-model']),
    mixed_frac_qs: S(['choose the operation', '+ − × ÷ by an integer mixed', 'non-unit fraction ÷ integer (4/5 ÷ 3)', 'check with the inverse'],
        ['fact'], 'write the answer', 'O2 two operations → four · O3 operation sign boxed → none · O6 cards / plain',
        ['divides the numerator only when it does not divide', 'multiplies both parts by the integer']),
    frac_find_whole: S(['3/5 is 24: what is the whole?', 'unit fraction first', 'story version', 'check by finding the fraction'],
        ['frac-model', 'word-work'], 'write the whole', 'O2 unit → non-unit · O3 bar with the known parts labelled → none · O6 bar / plain',
        ['multiplies 24 by 3/5', 'divides by the denominator only'], ['bar-model']),

    // ------------------------------------------------------------------ geometry
    shapes_world: S(['which shape is this object?', 'circle the objects that are circles', 'match objects to 3-D shapes', 'name from a word bank'],
        ['wordpic'], 'write the shape name from a bank or circle', 'O2 2-D faces → 3-D solids · O3 shape outline drawn beside the object → none · O6 line drawings',
        ['names the object not the shape', 'calls a cylinder a circle'], ['picture-row']),
    compare_shapes: S(['same or different? (sides, corners, curved)', 'tick what both shapes have', 'how are they different?', 'sides of equal length', '3-D: faces and edges'],
        ['wordpic'], 'tick the checklist; one word from a bank', 'O2 2-D → 3-D; one attribute → three · O3 corners dotted → none · O6 outlines / solids',
        ['counts corners on curved shapes', 'thinks size makes a different shape'], ['picture-row']),
    position_map: S(['where is it? (on, under, next to, behind, in front)', 'left or right', 'follow the arrows on a map', 'give the route', 'on / off / in / out (EE)'],
        ['wordpic'], 'circle or write the position word; draw the route', 'O2 on/in/under → next to/behind → left/right → routes · O3 word bank with icons → words · O6 picture / grid map',
        ['left and right from the viewer\'s side', 'behind and in front swapped'], ['picture-row', 'shape-grid']),
    shape_3d_tasks: S(['does it roll, stack or slide?', 'flat or curved faces', 'match the face print to the solid', 'choose a shape for a job'],
        ['wordpic'], 'tick roll / stack / slide; draw a line', 'O2 cube, sphere, cylinder → cone, pyramid, prism · O3 pictures of the action → words · O6 solids',
        ['a cylinder cannot stack', 'every flat face is a square'], ['solid-kit']),
    scenes: S(['copy the shape picture', 'which copy matches?', 'the same scene from another side', 'replicate a scene'],
        ['wordpic'], 'draw in the frame or tick the match', 'O2 2 shapes → 4 → rotated · O3 dotted frame → none · O6 shapes / blocks',
        ['mirrors the picture', 'misses the position of one shape'], ['shape-grid']),
    shape_sort: S(['sort by sides / corners', 'flat or solid (2-D / 3-D)', 'rolls or stacks', 'find the sorting rule', 'Carroll box'],
        ['wordpic'], 'write each tile letter in its ring or box', 'O2 one property → two (Carroll) → rule found · O3 labels with pictures → words · O6 rings / Carroll',
        ['sorts a square out of "rectangles"', 'counts a curved edge as a side'], ['sort-rings']),
    turns: S(['whole, half, quarter or three-quarter turn?', 'clockwise or anticlockwise', 'draw the arrow after the turn', 'how far has it turned?'],
        ['clock'], 'circle the turn from a bank; draw the arrow', 'O2 half/whole → quarter → three-quarter · O3 turn arc drawn → none · O6 arrow / object / clock hand',
        ['clockwise confused with anticlockwise', 'three-quarter turn drawn as quarter'], ['angle-kit']),
    shape_draw: S(['draw a named shape on a dot grid', 'draw from a description (4 sides, 2 long)', 'draw a shape that is NOT a rectangle, rhombus or square (3.G.A.1)', 'complete a half-drawn shape', 'draw with given attributes'],
        ['legacy'], 'draw on the dot grid; the key shows one correct drawing', 'O2 triangle/square → rectangle/pentagon → quadrilaterals by rule · O3 first side drawn → none · O6 dot / square grid',
        ['draws curved sides', 'a square is drawn as a rectangle only'], ['shape-grid']),
    symmetry_complete: S(['complete the shape across a vertical line', 'complete a pattern', 'horizontal mirror line', 'find the mistake'],
        ['legacy'], 'draw the other half', 'O2 vertical → horizontal → diagonal-free patterns · O3 squares numbered from the line → none · O6 square / dot grid',
        ['translates instead of reflecting', 'counts from the wrong edge'], ['shape-grid']),
    shape_faces: S(['count the faces', 'count the edges', 'count the vertices', 'which solid has 6 faces?'],
        ['legacy'], 'write the number', 'O2 one property per page → mixed · O3 hidden edges dashed → none · O6 solid drawings',
        ['misses hidden faces', 'counts a vertex as an edge'], ['solid-kit']),
    movement: S(['write the moves (up 3, right 2)', 'follow a route', 'moves with quarter turns', 'which square does it end on?'],
        ['legacy'], 'write the moves or the end square', 'O2 one direction → two → with turns · O3 arrows drawn → none · O6 grid / map',
        ['counts the start square', 'left and right swapped'], ['shape-grid']),
    pattern_turns: S(['continue a turning pattern', 'which tile comes next?', 'describe the turn each time', 'find the mistake'],
        ['legacy'], 'draw or circle the next tile', 'O2 quarter turns → half turns → mixed · O3 turn arrow between tiles → none · O6 arrows / shapes',
        ['turns the wrong way', 'repeats the first tile'], ['picture-row', 'angle-kit']),
    turns_angles: S(['angle as a turn (quarter turn = right angle)', 'greater than, less than or a right angle?', 'compare two angles (EE)', 'fraction of a full turn to degrees (1/360 = 1°)', 'how many right angles in a turn?'],
        ['legacy'], 'tick greater / less / right angle; write degrees', 'O2 right angles → compare → degrees from turns · O3 angle tester drawn in the corner → none · O6 turns / angles',
        ['longer arms mean a bigger angle', 'a quarter turn is 25°'], ['angle-kit']),
    hv_lines: S(['horizontal or vertical?', 'mark H or V on a shape', 'draw a horizontal line', 'count vertical lines'],
        ['legacy'], 'write H or V', 'O2 shapes → grids → drawing · O3 grid behind → none · O6 shapes / letters',
        ['a slanted line is horizontal', 'confuses the two words'], ['shape-grid']),
    draw_measure: S(['measure a line to the nearest cm', 'to the nearest mm', 'draw a line of given length', 'how much longer?'],
        ['legacy'], 'write the length; draw the line', 'O2 whole cm → half cm → mm · O3 ruler drawn under the line → none · O6 ruler picture',
        ['starts at 1 not 0', 'counts marks not spaces'], ['measure-scale']),
    make_3d: S(['how many straws and balls?', 'match a skeleton to the solid', 'match a net', 'build from a description'],
        ['legacy'], 'write the numbers; draw a line', 'O2 cube → prisms → pyramids · O3 vertices dotted → none · O6 skeleton / solid',
        ['counts straws twice', 'confuses edges and vertices'], ['solid-kit']),
    polygons: S(['name the polygon by sides', 'regular or irregular?', 'draw a regular polygon', 'why is it irregular?'],
        ['legacy'], 'write the name from a bank; tick regular / irregular', 'O2 3-6 sides → 8, 10 sides → reasons · O3 equal sides marked → none · O6 outlines',
        ['a regular shape must be upright', 'counts vertices for sides wrongly on concave shapes'], ['shape-grid']),
    translate_grid: S(['translate a point', 'translate a shape', 'describe the translation', 'where is the new vertex?'],
        ['legacy'], 'draw the image or write the translation', 'O2 one direction → two → coordinates · O3 arrow drawn → none · O6 grid / coordinates',
        ['translates the shape by its size', 'counts the start square'], ['coord-grid']),
    draw_angles: S(['draw an angle with a protractor', 'draw a line of given length', 'draw and label', 'check a drawing'],
        ['legacy'], 'draw; the key shows the angle', 'O2 multiples of 10° → any → reflex · O3 protractor printed on the line → none · O6 protractor picture',
        ['reads the wrong scale', 'draws the angle on the wrong side'], ['angle-kit']),
    angles_point: S(['angles on a straight line sum to 180°', 'around a point to 360°', 'find the missing angle', 'two missing angles'],
        ['legacy'], 'write the angle', 'O2 two angles → three → two unknowns equal · O3 180°/360° reminder → none · O6 diagrams',
        ['uses 360° on a line', 'measures instead of calculating'], ['angle-kit']),
    lengths_angles_shapes: S(['missing length in a rectangle', 'missing angle in a square', 'regular polygon side', 'use marked equal sides'],
        ['legacy'], 'write the value', 'O2 rectangles → regular polygons · O3 equal-side marks explained → none · O6 diagrams',
        ['ignores the equal marks', 'adds all sides for one'], ['shape-grid']),
    shapes_3d_props: S(['name the solid from its properties', 'faces, edges, vertices table', 'which net?', 'prism or pyramid?'],
        ['legacy'], 'write the name; fill the table', 'O2 cube/cuboid → prisms → pyramids · O3 hidden edges dashed → none · O6 solids / nets',
        ['a cube is not a prism', 'counts faces on a net wrongly'], ['solid-kit']),
    reflect_grid: S(['reflect a point', 'reflect a shape in a vertical line', 'in a horizontal line', 'in the axes'],
        ['legacy'], 'draw the reflection', 'O2 vertical → horizontal → axes · O3 distances marked → none · O6 grid / coordinates',
        ['translates instead of reflecting', 'reflects to the wrong distance'], ['coord-grid', 'shape-grid']),
    angle_rules: S(['vertically opposite angles', 'angles in a triangle (180°)', 'in a quadrilateral (360°)', 'isosceles triangle angles', 'polygons'],
        ['legacy'], 'write the missing angle', 'O2 one rule → two rules · O3 the rule printed → none · O6 diagrams',
        ['uses 360° in a triangle', 'assumes angles look equal'], ['angle-kit']),
    circles: S(['radius or diameter?', 'diameter = 2 × radius', 'find the radius', 'name the part (circumference)'],
        ['legacy'], 'write the word from a bank or the length', 'O2 name → calculate · O3 centre marked → none · O6 circles',
        ['radius is the whole width', 'halves the radius for the diameter'], ['angle-kit']),
    draw_accurately: S(['draw a triangle from two sides and an angle', 'draw a quadrilateral', 'check a drawing', 'measure the missing side'],
        ['legacy'], 'draw; the key shows a drawing', 'O2 right-angled → any angle · O3 base line printed → none · O6 sketch shown / not',
        ['protractor on the wrong vertex', 'reads the inner and outer scale mixed'], ['angle-kit']),
    four_quadrants: S(['read and plot in four quadrants', 'which quadrant?', 'find the missing vertex', 'reflect a point across an axis (signs change)', 'distance between points with the same x or y (across an axis)'],
        ['legacy'], 'write the coordinates; plot', 'O2 quadrant I → II → all · O3 axes numbered every 1 → every 2 · O6 grid size',
        ['(x, y) swapped', 'distance across the axis ignores the sign'], ['coord-grid']),

    // ------------------------------------------------------------------ measurement
    compare_size: S(['circle the bigger', 'circle the smaller', 'order three by size', 'same size?'],
        ['wordpic'], 'circle one', 'O2 two → three objects · O3 base line drawn → none · O6 objects',
        ['compares height only', 'picks the busier picture'], ['picture-row']),
    capacity_early: S(['full, empty, half full?', 'which holds more?', 'order three containers', 'nearly full / nearly empty'],
        ['wordpic'], 'circle or write the word from a bank', 'O2 full/empty → half → order · O3 fill line marked → none · O6 containers',
        ['a taller container always holds more', 'half full means any amount'], ['measure-scale']),
    balance: S(['heavier, lighter or balanced?', 'which side is heavier?', 'what makes it balance?', 'order by mass from balances'],
        ['wordpic'], 'tick one', 'O2 two objects → three via two balances · O3 arrow on the heavy side → none · O6 balance picture',
        ['the higher pan is heavier', 'bigger is heavier'], ['balance']),
    day_order: S(['number the pictures 1-4', 'first, next, then, last', 'before or after?', 'morning, afternoon, evening, night', 'what comes next in the day?'],
        ['wordpic'], 'write 1-4 or a word from a bank', 'O2 3 → 4 events → times of day · O3 word bank with icons → words only · O6 picture cards',
        ['orders by picture position', 'confuses morning and evening'], ['picture-row']),
    time_talk: S(['today, yesterday, tomorrow', 'days of the week in order', 'months and seasons', 'before and after on a calendar'],
        ['timeline'], 'circle or write the word from a bank', 'O2 days → months → seasons · O3 calendar strip shown → none · O6 strip / calendar',
        ['yesterday and tomorrow swapped', 'week starts at any day'], ['calendar']),
    nonstandard_mass: S(['how many cubes balance it?', 'which is heavier (by count)?', 'order by mass', 'same mass?'],
        ['counters'], 'write the number of cubes', 'O2 to 10 cubes → to 20 · O3 cubes counted in 5s → none · O6 balance',
        ['counts the object as 1 cube', 'thinks more cubes means lighter'], ['balance']),
    nonstandard_capacity: S(['how many cups fill it?', 'which holds more?', 'order by capacity', 'compare with the same cup'],
        ['counters'], 'write the number of cups', 'O2 to 10 → 20 · O3 cups drawn in a row → none · O6 containers',
        ['different cup sizes compared as equal', 'counts half cups as whole']),
    time_units: S(['seconds, minutes or hours?', 'which takes longer?', 'order activities by time', 'match activity to unit'],
        ['wordpic'], 'circle the unit from a bank', 'O2 minutes/hours → seconds → order · O3 icons for each unit → none · O6 pictures',
        ['brushing teeth takes hours', 'seconds longer than minutes'], ['picture-row']),
    money_notes: S(['name the note', 'value of the note', 'which is worth more: note or coin?', 'count notes'],
        ['coins'], 'write the value', 'O2 1, 5 notes → 10, 20, 50, 100 · O3 value printed on the note → none · O6 currency (USD, QAR)',
        ['a coin is worth more because it is bigger', 'counts notes as 1 each']),
    ruler_cm: S(['measure in whole cm', 'measure in mm', 'how long? (starts at 0)', 'object not at 0'],
        ['legacy'], 'write the length with cm or mm', 'O2 whole cm → half cm → mm; start at 0 → not at 0 · O3 arrow to the reading → none · O6 ruler picture',
        ['starts at 1', 'counts lines not spaces'], ['measure-scale']),
    money_uk: S(['count notes and coins', 'dollars and cents', 'choose coins to make an amount', 'make the same amount two ways'],
        ['coins', 'money-columns'], 'write the amount; draw or write the coins', 'O2 coins → notes → dollars and cents · O3 coins sorted largest first → scattered · O6 currency',
        ['counts coins not values', 'writes $3.5 for $3.05']),
    money_2step: S(['one-step: buy one item, find the change', 'one-step: how much more is needed?', 'two-step: buy two items, then change', 'compare two totals', 'using $ and ¢ correctly (2.MD.C.8)'],
        ['word-work', 'money-columns'], 'write the amount with $ or ¢', 'O2 one step within $1 → two steps within $10 → $100 · O3 price tags and bar model → none · O6 pictures / plain',
        ['adds the change to the price', 'mixes cents and dollars'], ['bar-model']),
    length_ops: S(['add two lengths', 'longer by / shorter by', 'multiply or divide a length', 'story with a ruler picture', 'add or take away units (EE 2.MD.5)'],
        ['word-work'], 'write the answer with the unit', 'O2 same unit within 20 → within 100 → × ÷; cube trains for EE · O3 ruler or bar drawn → none · O6 pictures / plain',
        ['adds when the story compares', 'drops the unit'], ['bar-model', 'measure-scale']),
    metres: S(['measure in metres', 'cm or m?', 'compare lengths in m', 'choose the tool: ruler, metre stick, tape (2.MD.A.1)'],
        ['legacy'], 'write the length; circle the unit or tool', 'O2 whole m → m and cm · O3 metre stick drawn → none · O6 picture',
        ['a door is 2 cm tall', 'uses a ruler for a playground'], ['measure-scale']),
    mass_scales: S(['read a scale in g / kg', 'read ml / l on a jug', 'scale steps of 2, 5, 10, 100', 'which tool? scale, jug or ruler (EE 3.MD.2)'],
        ['legacy'], 'write the reading with its unit', 'O2 labelled every step → every 2nd, 5th → unlabelled intervals · O3 arrow to the tick → none · O6 dial / jug / bar scale',
        ['counts ticks as 1 each', 'reads the next labelled number'], ['measure-scale']),
    mass_ops: S(['add masses or capacities', 'difference', 'multiply or divide', 'one-step story with a scale picture', 'with fractions or decimals and a unit change (4.MD.A.2)'],
        ['word-work'], 'write the answer with the unit', 'O2 same unit → mixed units → × ÷ with decimals · O3 scale picture and bar → none · O6 pictures / plain',
        ['adds g to kg directly', 'divides the wrong way']),
    time_facts: S(['60 minutes in an hour', '24 hours in a day, 7 days in a week', 'convert hours to minutes', 'word problems'],
        ['clock', 'timeline'], 'write the number', 'O2 facts → one conversion → problems · O3 fact box → none · O6 clock / timeline',
        ['100 minutes in an hour', '1 hour 30 minutes = 130 minutes']),
    mm_cm_m: S(['measure in mm, cm, m', 'convert 2 m 30 cm = 230 cm', 'measure one object in two units and compare (2.MD.A.2)', 'mixed-unit answers'],
        ['legacy'], 'write the length in each unit', 'O2 cm ↔ mm → m ↔ cm → mixed · O3 conversion fact → none · O6 ruler picture',
        ['2 m 30 cm = 2030 cm', 'more units means longer object'], ['measure-scale']),
    compare_lengths: S(['compare in mixed units', 'order lengths', 'convert then compare', 'which is longer by how much?'],
        ['compare'], 'write <, > or =', 'O2 same unit → mixed · O3 conversion fact → none · O6 bars / numbers',
        ['compares the numbers without units', '1 m 20 cm < 125 cm because 1 < 125']),
    add_sub_lengths: S(['add lengths, same unit', 'mixed units', 'bar model longer by', 'shorter by'],
        ['word-work'], 'write the answer with the unit', 'O2 same unit → mixed · O3 bar model → none · O6 bar / plain',
        ['adds m to cm', 'difference by adding'], ['bar-model']),
    money_convert: S(['cents to dollars and cents', 'dollars to cents', 'record money with the point', 'compare amounts'],
        ['coins', 'money-columns'], 'write the amount', 'O2 whole dollars → cents → mixed · O3 place chart $ | ¢ → none · O6 chart / plain',
        ['345 cents = $34.5', '$3.5 means 3 dollars 5 cents']),
    roman_12: S(['read Roman numerals on a clock', 'write the time on a Roman clock', 'numeral to number', 'number to numeral'],
        ['clock'], 'write the number or time', 'O2 I-VI → VII-XII · O3 key beside the clock → none · O6 clock / cards',
        ['IV read as 6', 'IX read as 11']),
    time_calendar: S(['days in each month', 'convert weeks, days, hours', 'leap years', 'read a calendar page', 'compare durations'],
        ['timeline'], 'write the number', 'O2 days/weeks → months → years · O3 calendar shown → none · O6 calendar / table',
        ['every month has 30 days', '1 year = 100 days'], ['calendar', 'data-table']),
    area_compare: S(['make a shape with a given area', 'compare areas by counting squares', 'which is bigger?', 'same area, different shape'],
        ['legacy'], 'circle or write the area; draw', 'O2 whole squares → larger shapes · O3 squares numbered → none · O6 grid',
        ['compares perimeters', 'counts edges'], ['shape-grid']),
    km_m: S(['convert km to m', 'mixed units 2 km 300 m', 'compare distances', 'add distances'],
        ['legacy'], 'write the answer', 'O2 whole km → mixed · O3 fact box → none · O6 numbers',
        ['1 km = 100 m', '2 km 300 m = 2,030 m']),
    missing_lengths: S(['find a missing side in an L-shape', 'two missing sides', 'then the perimeter', 'T and U shapes'],
        ['legacy'], 'write the lengths', 'O2 one missing → two → perimeter · O3 matching sides coloured grey → none · O6 labelled / some labels',
        ['adds the wrong pair', 'forgets a side in the perimeter'], ['shape-grid']),
    regular_polygon: S(['perimeter of a regular polygon from one side', 'side from the perimeter', 'any polygon', 'which has the longer perimeter?'],
        ['legacy'], 'write the perimeter', 'O2 triangle/square → hexagon/octagon → reverse · O3 equal marks → none · O6 outlines',
        ['multiplies by the wrong number of sides', 'adds one side only']),
    money_estimate: S(['round prices to the nearest dollar', 'estimate the total', 'estimate the change', 'is it enough?', 'estimate a sum or difference within 30 / 100 in a story (EE 4.NBT.3, 5.NBT.4)'],
        ['money-columns', 'word-work'], 'write the rounded prices and the estimate', 'O2 within 30 → within 100 → dollars and cents · O3 number line between dollars → none · O6 price tags / list',
        ['rounds down always', 'adds the exact prices']),
    time_24h_convert: S(['12-hour to 24-hour', '24-hour to 12-hour', 'analogue to 24-hour', 'a.m./p.m. clues'],
        ['clock'], 'write the time', 'O2 on the hour → any time · O3 conversion strip → none · O6 clocks',
        ['14:00 = 4 p.m.', 'forgets 12:00 is noon']),
    area_estimate: S(['count whole squares', 'count half squares', 'estimate the area', 'compare estimates'],
        ['legacy'], 'write the estimate', 'O2 whole → halves → mixed · O3 half squares shaded → none · O6 grid',
        ['counts every touched square as 1', 'ignores half squares'], ['shape-grid']),
    timetables: S(['read a departure time', 'how long is the journey?', 'which bus arrives before 3:00?', 'wait time'],
        ['legacy'], 'write the time or duration', 'O2 read → durations → planning · O3 row and column ruled → none · O6 table',
        ['reads across the wrong row', 'subtracts times like decimals'], ['data-table']),
    metric_imperial: S(['inches to cm (≈ 2.5)', 'kg to lb (≈ 2.2)', 'which is longer?', 'approximate answers'],
        ['legacy'], 'write the approximate value', 'O2 one fact → mixed · O3 fact box beside → none · O6 plain',
        ['uses an equals sign as exact', 'divides instead of multiplies']),
    volume_cubes: S(['count unit cubes in a solid', 'volume in cm³', 'which has more volume?', 'pack a box and show layers × cubes = l × w × h (5.MD.C.5a)', 'estimate volume and capacity', 'fractional edge cubes (6.G.A.2 link)'],
        ['legacy'], 'write the number of cubic units', 'O2 single layer → layers → hidden cubes · O3 layers separated → stacked · O6 isometric / layers',
        ['counts faces not cubes', 'misses hidden cubes'], ['solid-kit']),
    time_convert: S(['seconds to minutes', 'hours to days', 'weeks and months', 'mixed conversions'],
        ['legacy'], 'write the number', 'O2 one step → two steps · O3 conversion table → none · O6 table / plain',
        ['uses 100 as the base', '2.5 hours = 2 h 50 min']),
    metric_calc: S(['convert then add', 'convert then compare', 'multi-step context', 'decimal conversions (5 cm = 0.05 m)'],
        ['word-work'], 'write the answer with the unit', 'O2 one conversion → two steps · O3 conversion step printed → none · O6 plain',
        ['moves the decimal point the wrong way', 'adds different units']),
    miles_km: S(['miles to km with 5 : 8', 'km to miles', 'double number line', 'compare distances'],
        ['legacy'], 'write the distance', 'O2 multiples of 5 → any · O3 double line drawn → none · O6 line / table',
        ['uses 8 : 5', 'adds 3']),
    same_area: S(['same area, different perimeter', 'same perimeter, different area (3.MD.D.8)', 'draw two rectangles with area 12', 'which pair matches?'],
        ['legacy'], 'write area and perimeter; circle the pair', 'O2 given → draw · O3 grid numbered → none · O6 grid',
        ['same area means same perimeter', 'counts the corner squares twice'], ['shape-grid']),
    area_triangle_grid: S(['count squares for a triangle', 'half the rectangle', 'right-angled triangles', 'any triangle'],
        ['legacy'], 'write the area', 'O2 right-angled on grid → any on grid → no grid · O3 rectangle dashed → none · O6 grid',
        ['uses the slant side as the height', 'forgets to halve'], ['shape-grid']),
    parallelogram: S(['area of a parallelogram (base × height)', 'cut and move a triangle', 'trapezoid by decomposing (6.G.A.1)', 'polygon split into triangles and rectangles (6.G.A.1)', 'find a missing base or height'],
        ['legacy'], 'write the area', 'O2 on grid → no grid → trapezoids/polygons · O3 height dashed → none · O6 grid / plain',
        ['uses the slant side', 'halves a parallelogram'], ['shape-grid']),

    // ------------------------------------------------------------------ number theory
    multiples_2_5_10: S(['is it a multiple of 2, 5, 10?', 'circle the multiples', 'odd or even ends', 'continue the multiples'],
        ['chartwindow'], 'circle or write', 'O2 to 50 → to 100 · O3 hundred square shaded → none · O6 chart / list',
        ['15 is a multiple of 10', 'even numbers end in 0 only']),
    common_mf: S(['list factors of two numbers, circle the common ones', 'list multiples, circle the common ones', 'Venn diagram', 'find all common factors to 100'],
        ['legacy'], 'write the lists; circle', 'O2 small numbers → to 100 · O3 lists started → none · O6 lists / Venn',
        ['lists only the greatest', 'stops the list early'], ['sort-rings']),
    square_cube: S(['square numbers as arrays', 'cube numbers as cubes', 'write 5² and 2³', 'is it a square number?', 'write a repeated product as a power (6.EE.A.1)'],
        ['arrays'], 'write the number or the notation', 'O2 squares → cubes → notation · O3 arrays drawn → none · O6 dots / cubes',
        ['5² = 10', '2³ = 6'], ['solid-kit']),
    divisibility_rules: S(['state the rule', 'apply the rule', 'which rule tells you?', 'sort by divisibility'],
        ['legacy'], 'tick or write yes/no', 'O2 2, 5, 10 → 3, 9 → 4, 6, 8, 25 · O3 rule card → none · O6 card / plain',
        ['divisible by 3 if it ends in 3', 'by 4 if even']),

    // ------------------------------------------------------------------ operations
    part_whole: S(['find the missing part', 'write the four sentences', 'which diagram matches?', 'whole unknown'],
        ['bond'], 'write the missing part or sentences', 'O2 within 5 → 10 → 20 · O3 counters in the circles → none · O6 cherry / bar',
        ['adds the whole and a part', 'writes 3 − 5 = 2']),
    systematic_bonds: S(['list all bonds of n in order', 'find the missing rows', 'spot the pattern', 'decompose ≤ 5 in more than one way (EE)'],
        ['bond', 'tenframe'], 'complete the two-column table', 'O2 5 → 10 → 20 · O3 first rows filled, ten frame beside → none · O6 table / frames',
        ['misses 0 + n', 'repeats a pair']),
    equal_groups_early: S(['equal or not?', 'make equal groups', 'add equal groups', 'doubles as equal groups', 'arrays to 5 × 5: write the repeated addition (2.OA.C.4)'],
        ['counters', 'arrays'], 'tick; write groups of; write the addition sentence', 'O2 2s, 5s, 10s → any to 25 · O3 groups ringed → none · O6 rings / arrays',
        ['counts groups as the total', 'adds unequal groups as equal']),
    add_sub_1_2: S(['one more / one less', 'add 1 or 2', 'subtract 1 or 2', 'one more as a picture: n objects and one more (K.CC.B.4c)'],
        ['seqstrip', 'counters'], 'write the answer', 'O2 within 10 → 20 · O3 track with start circled → none · O6 track / objects',
        ['counts the start number', 'adds instead of taking away']),
    bonds_20: S(['bonds to 20', 'use a bond to 10 (3 + 7 → 13 + 7)', 'add and subtract ones', 'missing part'],
        ['tenframe', 'bond'], 'write the missing part', 'O2 bonds to 10 → to 20 → within 20 · O3 two frames → none · O6 frames / bond',
        ['13 + 7 = 10', 'answers 3 for 20 − 7']),
    difference: S(['find the difference of two bars', 'how many more?', 'on a number line', 'write the subtraction'],
        ['compare', 'number-line'], 'write the difference and the sentence', 'O2 within 10 → 20 · O3 cubes paired → none · O6 cubes / bars / line',
        ['adds the two amounts', 'counts the larger bar']),
    bonds_100: S(['tens to 100 (30 + 70)', 'any pair to 100', 'missing part on a hundred square', 'bead string'],
        ['chartwindow', 'bond'], 'write the missing part', 'O2 tens → multiples of 5 → any · O3 hundred square shaded → none · O6 square / bond',
        ['37 + 73 = 100', 'makes 100 in each place (37 + 73)']),
    add_next_10: S(['to the next ten', 'cross the ten in two jumps', 'subtract back to a ten', 'number line jumps'],
        ['hop-line', 'number-line'], 'write the jumps and the answer', 'O2 to the ten → across → subtract · O3 ten marked on the line → none · O6 line',
        ['jumps to the wrong ten', 'forgets the second jump']),
    compare_sentences: S(['compare 7 + 5 and 7 + 6 without calculating', '< > = between expressions', 'true or false?', 'make it true'],
        ['equation'], 'write <, > or =', 'O2 one change → two changes · O3 matching parts linked → none · O6 plain',
        ['calculates every side', 'bigger first number means bigger']),
    add_sub_patterns: S(['3 + 4, 30 + 40, 300 + 400', 'what changes, what stays', 'subtract patterns', 'use the fact to explain (2.NBT.B.9 link)'],
        ['fact', 'pv'], 'complete the fact ladder', 'O2 1s/10s → 100s · O3 first row done → none · O6 ladder / chart',
        ['adds the zeros', '30 + 40 = 700']),
    cross_100: S(['add 10s across 100', 'subtract 10s across 100', 'number line', 'missing number'],
        ['hop-line'], 'write the answer', 'O2 +10 → +30 → −40 · O3 line with 100 marked → none · O6 line',
        ['180 + 30 = 1,110', 'forgets the hundreds change']),
    make_decisions: S(['mental or written?', 'why?', 'solve', 'find the easy ones'],
        ['stack', 'fact'], 'tick mental or written, then solve', 'O2 within 100 → 1,000 · O3 reason bank → none · O6 list',
        ['everything written', 'no regrouping check']),
    tables_links: S(['double the 2s to get the 4s', '3s → 6s → 12s', '9s as 10 − 1', 'related facts both ways (3 × 4 → 30 × 4 → 120 ÷ 4)'],
        ['mult-grid', 'fact'], 'fill the doubled table', 'O2 2→4 → 3→6 → 4→8 → 9s · O3 known table given → none · O6 table / columns',
        ['adds 2 instead of doubling', 'doubles the factor and the product']),
    how_many_ways: S(['list every pair', 'draw the combinations', 'write the multiplication', 'how many ways?'],
        ['arrays'], 'write the pairs or the product', 'O2 2 × 3 → 3 × 4 → 3 × 5 · O3 table started → none · O6 pictures / table',
        ['adds instead of multiplies', 'misses pairs'], ['data-table']),
    mult_three: S(['multiply three numbers', 'choose the easy pair first', 'show two ways give the same (associative, 3.OA.B.5)', 'find the missing factor'],
        ['fact', 'equation'], 'write the answer', 'O2 with 10 → any 1-digit · O3 bracket prompt → none · O6 brackets / plain',
        ['adds the third number', 'multiplies two and stops']),
    correspondence: S(['each hat with each scarf', 'one bag holds 5', 'table or tree', 'write the multiplication'],
        ['arrays'], 'complete the table; write the product', 'O2 2 × 3 → 4 × 5 · O3 table started → none · O6 table / tree',
        ['adds', 'misses a pairing'], ['data-table']),
    informal_mult: S(['partition to multiply (23 × 4)', 'grid method', 'add the partial products', 'which partition?'],
        ['area-model'], 'fill the parts and the total', 'O2 2-digit × 1-digit → 3-digit · O3 grid drawn → none · O6 grid / part-whole',
        ['multiplies tens as ones', 'adds the factors']),
    mental_add_sub: S(['partition', 'count on', 'compensate (+ 99 as + 100 − 1)', 'near multiples'],
        ['fact'], 'write the answer', 'O2 4-digit → 6-digit · O3 strategy prompt → none · O6 plain',
        ['compensates the wrong way', 'loses a place']),
    inverse_check: S(['check an addition by subtracting', 'check a subtraction by adding', 'find the missing number', 'large numbers'],
        ['stack'], 'write the check and the answer', 'O2 to 10,000 → 1,000,000 · O3 check frame → none · O6 stack',
        ['subtracts the wrong numbers', 'checks with the same operation']),
    compare_calcs: S(['compare without calculating (4,580 + 2,000 vs 4,580 + 1,999)', '< > =', 'explain', 'numerical expressions equal by a property (EE 6.EE.3)', 'three times as large (5.OA.A.2)'],
        ['equation'], 'write <, > or =', 'O2 one change → two changes · O3 matching parts linked → none · O6 plain',
        ['calculates both', 'bigger number means bigger result']),
    mult_multiples: S(['is it a multiple of 10, 100, 1,000?', 'generate multiples', 'circle multiples', 'why?'],
        ['legacy'], 'circle or write', 'O2 10 → 100 → 1,000 · O3 rule → none · O6 list',
        ['1,050 is a multiple of 100', 'every even is a multiple of 10']),
    long_mult: S(['4-digit × 2-digit', 'short division of 4-digit', 'choose a division method', 'find the error'],
        ['stack', 'division'], 'write the answer in the grid', 'O2 3 × 2 → 4 × 2 digits · O3 carry boxes and placeholder row → none · O6 grid',
        ['forgets the placeholder zero', 'adds carries in the wrong row'], ['long-multiplication']),
    div_factors: S(['divide by factors in turn', 'choose the factor pair', 'check', 'compare methods'],
        ['equation'], 'write each step', 'O2 ÷ 4, 6 → ÷ 12, 15 · O3 arrow diagram → none · O6 arrows / plain',
        ['divides by the sum of factors', 'uses a non-factor pair']),
    long_div_rem: S(['remainder as r', 'as a fraction', 'as a decimal', 'which form fits the story?'],
        ['division'], 'write the answer in the asked form', 'O2 r → fraction → decimal · O3 remainder box → none · O6 bus stop / long',
        ['writes the remainder as a decimal digit (r 3 = .3)', 'fraction over the quotient']),
    mental_estimate: S(['estimate to check', 'is the answer reasonable?', 'choose a mental method', 'round then calculate'],
        ['pv'], 'tick reasonable / not; write the estimate', 'O2 + − → × ÷ · O3 rounding line → none · O6 plain',
        ['rounds every number up', 'accepts an answer ten times too big']),
    known_facts: S(['24 × 15 = 360 so 24 × 16 = ?', 'decimal twins (2.4 × 15)', 'halve and double', 'explain'],
        ['fact'], 'write the answer', 'O2 +1 factor → ×10 → decimals · O3 link arrow → none · O6 plain',
        ['recalculates from scratch', 'adds 1 to the product']),
    add_or_mult: S(['add 3 or multiply by 3?', 'complete the table', 'more than vs times as many in a story (4.OA.A.2)', 'write the rule'],
        ['function-table'], 'tick; write the rule', 'O2 tables → stories · O3 difference and ratio shown → none · O6 table / story',
        ['3 times as many = 3 more', 'uses the first pair only']),

    // ------------------------------------------------------------------ place value
    compare_small: S(['compare numbers within 10 and 20', 'compare groups with words', 'greater than / less than / equal to', 'tens-and-ones pictures to 99 (EE 5.NBT.1)', 'order three'],
        ['compare', 'pv', 'base10'], 'write <, > or =, or the word from a bank', 'O2 to 10 → 20 → 99 · O3 pictures (frames / tens and ones) → numbers · O6 frames / rods / numbers',
        ['the sign points to the bigger number', 'compares ones before tens']),
    nl_20: S(['number at the arrow', 'mark a number', 'count along', 'estimate on a line with only ends', 'scales of 1s, 10s, 100s'],
        ['number-line', 'value-line'], 'write the number; mark it', 'O2 0-20 → 0-100 → 0-1,000 → 0-1,000,000 · O3 all ticks labelled → some → ends · O6 labels',
        ['counts ticks not intervals', 'assumes steps of 1']),
    flex_partition: S(['45 = 40 + 5 = 30 + 15', 'missing part', 'base-10 picture', 'three parts'],
        ['bond', 'base10', 'pv'], 'write the other part', 'O2 2-digit → 3 → 4 · O3 base-10 picture → none · O6 cherry / bar',
        ['only standard partitions', 'partitions into digits (45 = 4 + 5)']),
    roman_100: S(['numeral to number', 'number to numeral', 'no zero', 'compare'],
        ['equation'], 'write the value or the numeral', 'O2 to 20 → 50 → 100 · O3 key → none · O6 cards',
        ['IIII for 4', 'XL = 60']),
    roman_1000: S(['to 1,000 (D, M)', 'years', 'compare', 'missing numeral'],
        ['equation'], 'write the value', 'O2 to 500 → 1,000 → years · O3 key → none · O6 cards',
        ['CM = 1,100', 'MD = 500']),
    pv_more_less_big: S(['10,000 more / less', '100,000 more / less', 'missing start', 'mixed steps'],
        ['pv'], 'write the number', 'O2 1,000 → 10,000 → 100,000 · O3 strip → none · O6 chart / strip',
        ['changes the wrong digit', 'forgets the carry into millions']),
    dec_missing: S(['3.4 × __ = 340', '__ ÷ 100 = 0.25', 'missing power of 10', 'place value chart shift'],
        ['pv-support'], 'write the missing number', 'O2 × → ÷ → mixed · O3 shift arrows → none · O6 chart',
        ['adds zeros to decimals (3.4 × 10 = 3.40)', 'shifts the wrong way']),
    big_numbers: S(['read and write to 10,000,000', 'partition', 'compare', 'place on a line'],
        ['pv'], 'write the number / words from a bank', 'O2 1,000,000 → 10,000,000 · O3 place-value headings → none · O6 chart',
        ['misses a zero', 'groups digits wrongly']),

    // ------------------------------------------------------------------ ratio
    scale: S(['enlarge by a scale factor', 'find the scale factor', 'missing side of similar shapes', 'scale drawing lengths'],
        ['legacy'], 'write the factor or the length', 'O2 factors 2, 3 → fractions · O3 grid → none · O6 grid / plain',
        ['adds the scale factor', 'enlarges one side only'], ['shape-grid']),
    ratio_problems: S(['recipe for more people', 'share in a ratio', 'bar model', 'ratio table'],
        ['word-work'], 'write the amount', 'O2 simple → two-step · O3 bar model → none · O6 bar / table',
        ['adds instead of scaling', 'uses the ratio numbers as amounts'], ['bar-model', 'data-table']),
};
