// standards-audit.js — the rigorous CCSS + Wisconsin Essential Elements coverage verdicts (owner,
// 2026-09-25: "do the same check for CCSS and EE standards to make sure they are fully covered by our
// current skills and if not design new skills to cover them all").
//
// `design/STANDARDS_COVERAGE.md` used to count a standard covered whenever any skill was TAGGED to
// it. This module holds a verdict judged from what the skills actually deal — their generators,
// options, templates and seeded items (generateQuestionFor samples, read 2026-09-25) — against EVERY
// clause of the standard's text:
//
//   full      the skills below teach and assess every clause (with the option values in `note`);
//   partial   they teach part of it; `missing` names each missing clause exactly;
//   gap       nothing teaches it.
//
// Every missing clause names the proposal(s) that close it (`build`): a WRM proposal id
// (js/modules/wrm.js WRM_PROPOSALS, extended where needed in build-list.js WRM_EXTENSIONS) or a
// standards proposal id (build-list.js STANDARD_PROPOSALS). There is one build list.
//
// A pure data module, NOT imported by the app. `node tests/scripts/ws-standards.cjs` checks it
// (every CCSS leaf standard and every EE has a verdict; every skill in `by` is live and carries the
// code in standards.js; every `build` id exists); `--strict` fails while any verdict is not full;
// `--report` writes design/STANDARDS_COVERAGE.md and design/BUILD_LIST.md.
//
// KEYS  every CCSS standard that has no lettered parts, every lettered part (3.NF.A.3a), and a
//       parent that has its own clause beyond its parts (1.NBT.B.2, 2.NBT.A.1). A parent's status
//       is derived: full when its own verdict (if any) and all its parts are full; gap when all are
//       gaps; else partial. Every Essential Element by its DPI code.

const F = (by, note = '') => ({ status: 'full', by, note, missing: [], build: [] });
const P = (by, missing, build, note = '') => ({ status: 'partial', by, note, missing, build });
const G = (missing, build, note = '') => ({ status: 'gap', by: [], note, missing, build });

export const CCSS_AUDIT = {
    // ================================================================ Kindergarten
    'K.CC.A.1': F(['patterns:seq_10', 'counting:number_seq_fill', 'composing:hundreds_chart_fill'], 'by tens: seq_10; by ones to 100: number_seq_fill (step 1, to 100) and the hundreds chart'),
    'K.CC.A.2': F(['counting:count_sequence', 'counting:number_seq_fill']),
    'K.CC.A.3': P(['counting:count_objects', 'counting:zero_none'], ['writing the numerals 0-20 (formation: trace, copy, write)'], ['write_numerals'], 'zero as the numeral for none: counting:zero_none (build lane k2)'),
    'K.CC.B.4a': F(['counting:count_objects'], 'touch-and-count support pairs each object with one number name'),
    'K.CC.B.4b': F(['counting:count_objects', 'composing:ten_frame_build'], 'conservation: count_objects task "same" (A in rows, B moved and spread out: same number? check), build lane k2'),
    'K.CC.B.4c': P(['counting:count_sequence'], ['each next number name is a quantity one larger: n objects and one more, as a picture'], ['add_sub_1_2']),
    'K.CC.B.5': P(['counting:count_objects', 'composing:ten_frame_build', 'composing:ten_frame_build_teen'], ['given a number 1-20, count out that many from a larger group'], ['ten_count_out'], 'up to 20 in a circle: count_objects arrangement "circle" with the start marked (build lane k2)'),
    'K.CC.C.6': F(['comparing:compare_groups']),
    'K.CC.C.7': P(['placevalue:compare'], ['two numerals between 1 and 10 (the lowest band of compare is 99)'], ['compare_small']),
    'K.OA.A.1': P(['addition:add_5_pictures', 'subtraction:sub_5_pictures'], ['the pupil represents the operation: writes the equation for a picture and draws a picture for an equation'], ['pictures_to_sentence', 'part_whole']),
    'K.OA.A.2': F(['addition:add_wp_10', 'subtraction:sub_wp_10', 'addition:add_10_mixed', 'subtraction:sub_10_mixed']),
    'K.OA.A.3': F(['composing:number_bonds', 'composing:bonds_in_order'], 'every decomposition of one number, recorded in order as a table, with dots, or as equations 0 + 5 = 5: bonds_in_order (build lane k2)'),
    'K.OA.A.4': F(['composing:make_ten']),
    'K.OA.A.5': F(['addition:add_5_pictures', 'subtraction:sub_5_pictures', 'addition:add_facts', 'subtraction:sub_facts'], 'fluency: add_facts / sub_facts at band 5'),
    'K.NBT.A.1': F(['composing:teen_compose', 'composing:ten_frame_build_teen']),
    'K.MD.A.1': F(['comparing:compare_objects', 'comparing:compare_capacity', 'comparing:what_can_we_measure'], 'length and height: compare_objects; capacity (full / empty / holds more): compare_capacity; several attributes of one object, measurable or not, and the tool: what_can_we_measure (build lane k2)'),
    'K.MD.A.2': F(['comparing:compare_objects', 'measurement:heavier_lighter_visual']),
    'K.MD.B.3': F(['comparing:classify_count', 'comparing:sort_into_groups'], 'classify every object into two or three given categories, count each, the category with the most, the categories ordered by count: sort_into_groups (build lane k2)'),
    'K.G.A.1': P(['shapes_early:shape_positions'], ['name the shapes of objects in the environment', 'in front of, behind, next to (the skill has above, below, beside)'], ['shapes_world', 'position_map']),
    'K.G.A.2': F(['shapes_early:name_2d_shapes', 'shapes_early:name_3d_shapes', 'shapes_early:shape_name_match_2d', 'shapes_early:shape_name_match_3d']),
    'K.G.A.3': P(['shapes_early:name_3d_shapes', 'shapes_early:shape_name_match_3d'], ['identify shapes as flat (2-D) or solid (3-D)'], ['shape_sort']),
    'K.G.B.4': P(['shapes_early:shape_corners_count', 'shapes_early:count_sides_vertices_2d'], ['compare two shapes: similarities and differences', 'the parts of 3-D shapes', 'sides of equal length'], ['compare_shapes', 'shape_3d_tasks']),
    'K.G.B.5': G(['build shapes from components (sticks and balls)', 'draw shapes'], ['shape_draw', 'make_3d']),
    'K.G.B.6': F(['shapes_early:compose_shapes']),

    // ================================================================ Grade 1
    '1.OA.A.1': F(['addition:add_word_problems', 'subtraction:sub_word_problems', 'addition:comparison_word', 'subtraction:unknown_start_wp', 'addition:add_wp_20', 'subtraction:sub_wp_20'], 'every situation and unknown position at range 20; bar and equation supports'),
    '1.OA.A.2': P(['addition:add_three'], ['word problems with three addends (the skill is bare sums)'], ['add_three_forms']),
    '1.OA.B.3': P(['addition:add_sub_fact_family', 'addition:fact_family_sort'], ['the associative property as a strategy: add three numbers by making a ten first (2 + 6 + 4 = 2 + 10)'], ['add_three_forms']),
    '1.OA.B.4': F(['addition:add_sub_fact_family', 'addition:number_families_add', 'subtraction:missing_add_sub']),
    '1.OA.C.5': F(['addition:nl_add', 'subtraction:nl_sub', 'addition:number_line_add', 'subtraction:number_line_sub']),
    '1.OA.C.6': P(['addition:add_facts', 'subtraction:sub_facts', 'number_sense:make_a_ten', 'number_sense:doubles_near_doubles', 'addition:number_families_add'], ['decomposing a number leading to a ten in subtraction (13 − 4 = 13 − 3 − 1)'], ['make_ten_subtract']),
    '1.OA.D.7': P(['algebra:balance_addsub'], ['decide whether equations are true or false: addition:equal_sign is tagged but deals plain column addition (it routes to the operations generator)', 'the forms 6 = 6 and 7 = 8 − 1'], ['equal_sign_repair', 'compare_sentences']),
    '1.OA.D.8': F(['subtraction:missing_add_sub', 'addition:cloze_addition', 'algebra:balance_addsub']),
    '1.NBT.A.1': P(['counting:number_seq_fill', 'composing:hundreds_chart_fill'], ['counting across 100 to 120 on a chart', 'writing the numeral for a counted set above 20'], ['chart_120', 'tens_ones_group']),
    '1.NBT.B.2': F(['composing:base10_build'], 'own clause: the two digits are tens and ones'),
    '1.NBT.B.2a': F(['composing:tens_foundation_visual', 'composing:base10_regroup']),
    '1.NBT.B.2b': F(['composing:teen_compose', 'composing:ten_frame_build_teen'], 'teen numbers as a ten and some ones'),
    '1.NBT.B.2c': F(['composing:tens_foundation_visual']),
    '1.NBT.B.3': F(['placevalue:compare'], 'band 99'),
    '1.NBT.C.4': P(['addition:add_50_mixed', 'addition:add_100_mixed', 'addition:add_sub_10s'], ['concrete models or drawings for 2-digit addition, related to the written method', 'a 2-digit number plus a multiple of 10 as its own step'], ['stack_base10_support', 'tens_any']),
    '1.NBT.C.5': F(['placevalue:more_less_10', 'addition:add_sub_10s']),
    '1.NBT.C.6': P(['addition:add_sub_10s'], ['subtract any multiple of 10 from a multiple of 10 (70 − 30): the skill only takes 10 away'], ['tens_any']),
    '1.MD.A.1': P(['shapes_early:order_objects_length'], ['compare two lengths indirectly by using a third object'], ['order_length_tasks']),
    '1.MD.A.2': F(['shapes_early:measure_nonstandard']),
    '1.MD.B.3': F(['measurement:time_hour', 'measurement:time_half_hour']),
    '1.MD.C.4': F(['measurement:pictograph_intro', 'measurement:bar_graph_intro', 'graphs:tally_chart', 'graphs:build_pictograph'], 'organise and represent: build_pictograph; interpret: each category, totals, how many more'),
    '1.G.A.1': P(['shapes_early:shape_attributes', 'shapes_early:compose_from_attributes'], ['defining versus non-defining attributes (orientation, size)', 'build and draw shapes with given defining attributes'], ['defining_attributes', 'shape_draw']),
    '1.G.A.2': F(['shapes_early:compose_shapes', 'shapes_early:compose_hexagon']),
    '1.G.A.3': P(['shapes_early:partition_shapes'], ['the words halves, fourths, quarters and "half of / quarter of" (the skill writes 1/2)', 'the whole as two or four of the shares', 'more equal shares make smaller shares'], ['half_quarter']),

    // ================================================================ Grade 2
    '2.OA.A.1': F(['addition:add_word_problems', 'subtraction:sub_word_problems', 'subtraction:unknown_start_wp', 'addition:add_wp_100', 'subtraction:sub_wp_100', 'algebra:multi_step_word'], 'one step: every situation and unknown to 100; two steps: multi_step_word (+ and −)'),
    '2.OA.B.2': F(['addition:add_facts', 'subtraction:sub_facts']),
    '2.OA.C.3': P(['composing:odd_even', 'composing:select_even_odd', 'patterns:double'], ['decide odd or even for a group of objects (up to 20) by pairing or counting in 2s (the skills use the last digit)', 'write an even number as a sum of two equal addends'], ['odd_even_pairs']),
    '2.OA.C.4': P(['multiplication:arrays_groups', 'multiplication:dot_array_mult', 'multiplication:repeated_add_to_mult'], ['the pupil writes the total of an array (to 5 × 5) as a sum of equal addends (repeated_add_to_mult prints the sum)'], ['equal_groups_early']),
    '2.NBT.A.1': F(['composing:base10_build_hundreds', 'placevalue:place_value_disks', 'placevalue:unit_form'], 'own clause: three digits are hundreds, tens, ones (706 = 7 hundreds 0 tens 6 ones)'),
    '2.NBT.A.1a': G(['100 as a bundle of ten tens (composing:base10_regroup trades a ten for ten ones only: its tag was removed)'], ['regroup_hundreds']),
    '2.NBT.A.1b': G(['100, 200 … 900 as 1 … 9 hundreds and 0 tens, 0 ones'], ['hundreds_foundation']),
    '2.NBT.A.2': F(['composing:number_chart_fill', 'patterns:seq_5', 'patterns:seq_10', 'patterns:count_by_powers_of_10', 'patterns:skip_count_line']),
    '2.NBT.A.3': F(['composing:number_word_form', 'placevalue:expand', 'placevalue:combine', 'composing:base10_build_hundreds']),
    '2.NBT.A.4': F(['placevalue:compare']),
    '2.NBT.B.5': F(['addition:add_100_mixed', 'subtraction:sub_100_mixed', 'number_sense:compensation', 'subtraction:mixed_add_sub']),
    '2.NBT.B.6': F(['addition:add_column_multi']),
    '2.NBT.B.7': P(['addition:add_1k_mixed', 'subtraction:sub_1k_mixed', 'addition:add_sub_100s', 'subtraction:sub_check_by_adding'], ['concrete models or drawings (base-10, place-value disks) related to the written method'], ['stack_base10_support', 'cross_100']),
    '2.NBT.B.8': F(['placevalue:more_less_100', 'addition:add_sub_100s']),
    '2.NBT.B.9': G(['explain why addition and subtraction strategies work, using place value and the properties of operations'], ['explain_strategy', 'add_sub_patterns']),
    '2.MD.A.1': P(['measurement:reading_ruler'], ['centimetre rulers, metre sticks, yardsticks and tapes (the skill reads inches)', 'selecting the appropriate tool'], ['ruler_cm', 'metres']),
    '2.MD.A.2': G(['measure one object twice with units of different lengths and relate the counts to the unit size'], ['measure_two_units', 'mm_cm_m']),
    '2.MD.A.3': F(['measurement:estimate_length']),
    '2.MD.A.4': G(['measure to find how much longer one object is than another, in a standard unit'], ['ruler_difference', 'compare_lengths']),
    '2.MD.B.5': G(['addition and subtraction word problems about lengths in the same units, with ruler drawings'], ['length_ops', 'add_sub_lengths']),
    '2.MD.B.6': F(['addition:nl_add', 'subtraction:nl_sub', 'number_sense:place_on_number_line']),
    '2.MD.C.7': F(['measurement:time_5min', 'measurement:time_analog_digital', 'measurement:time_sense']),
    '2.MD.C.8': P(['measurement:money_count', 'measurement:money', 'measurement:money_change', 'measurement:enough_money'], ['word problems (stories) with dollar bills and coins using $ and ¢'], ['money_2step', 'money_uk']),
    '2.MD.D.9': P(['graphs:line_plot_g2'], ['generate the data by measuring several objects', 'make the line plot (the skill reads one)'], ['make_line_plot']),
    '2.MD.D.10': F(['graphs:build_bar_graph', 'graphs:build_pictograph', 'measurement:bar_graph_intro']),
    '2.G.A.1': P(['shapes_early:count_sides_vertices_2d', 'shapes_early:compose_from_attributes', 'shapes_early:count_edges_faces_vertices'], ['draw shapes with specified attributes'], ['shape_draw']),
    '2.G.A.2': P(['shapes_early:compose_rect_from_squares'], ['partition a rectangle into rows and columns of any size (the skill fills one 2 × 3 rectangle)', 'count the squares to find the total'], ['rect_rows_columns']),
    '2.G.A.3': P(['shapes_early:partition_shapes'], ['describe shares with words (halves, thirds, half of, a third of)', 'the whole as two halves, three thirds, four fourths', 'equal shares of identical wholes need not have the same shape'], ['fraction_parts']),

    // ================================================================ Grade 3
    '3.OA.A.1': F(['multiplication:arrays_groups', 'multiplication:repeated_add_to_mult', 'multiplication:equal_or_unequal_groups', 'multiplication:nl_mult']),
    '3.OA.A.2': F(['division:div_word_problems', 'division:share_into_groups', 'division:nl_div']),
    '3.OA.A.3': F(['multiplication:mult_word_problems', 'division:div_word_problems', 'algebra:build_expr_multdiv']),
    '3.OA.A.4': F(['division:missing_mult_div', 'number_ops_mixed:missing_factor_or_addend']),
    '3.OA.B.5': P(['multiplication:mult_properties'], ['the associative property (3 × 5 × 2 = 3 × 10); the skill offers order, breaking apart, × 1 and × 0'], ['mult_three']),
    '3.OA.B.6': F(['multiplication:mult_div_fact_family', 'division:missing_mult_div']),
    '3.OA.C.7': F(['multiplication:mult_facts', 'division:div_facts']),
    '3.OA.D.8': P(['algebra:multi_step_word', 'number_sense:estimate_sums_diffs'], ['two-step problems with × and ÷ (the skill\'s two steps are + and − only)', 'an equation with a letter for the unknown', 'one-step pools and tape diagrams were tagged here: tags moved to the one-step standards'], ['multi_step_four_ops', 'mental_estimate']),
    '3.OA.D.9': P(['multiplication:mult_chart', 'patterns:number_patterns_rule', 'patterns:count_by_fill'], ['patterns in the addition table', 'explain a pattern with a property (4 × n is always even)'], ['patterns_notice']),
    '3.NBT.A.1': F(['number_sense:nearest_10', 'number_sense:nearest_100', 'number_sense:rounding_visual']),
    '3.NBT.A.2': F(['addition:add_1k_mixed', 'subtraction:sub_1k_mixed']),
    '3.NBT.A.3': F(['multiplication:mult_zeros']),
    '3.NF.A.1': F(['fractions:identify', 'fractions:write_fraction', 'fractions:shade_fraction', 'composing:compose_whole']),
    '3.NF.A.2a': F(['composing:fraction_number_line', 'fractions:graph_fractions', 'fractions:fraction_nl_drag']),
    '3.NF.A.2b': F(['composing:fraction_number_line', 'fractions:fraction_nl_drag', 'fractions:order_frac_numline']),
    '3.NF.A.3a': P(['fractions:equiv_frac_visual'], ['equivalent fractions as the same point on a number line'], ['frac_nl_equiv', 'frac_count']),
    '3.NF.A.3b': F(['fractions:equiv_frac_visual', 'fractions:equiv_frac_nv', 'fractions:select_equiv_frac']),
    '3.NF.A.3c': P(['composing:whole_as_fraction', 'composing:compose_whole'], ['recognise a fraction as a whole number (6/1 = 6)', 'locate 4/4 and 1 at the same point of a number line'], ['whole_frac_reverse', 'frac_count']),
    '3.NF.A.3d': P(['fractions:compare', 'fractions:order_fractions'], ['same-numerator comparisons (3/5 vs 3/8)', 'comparisons are valid only for the same whole'], ['compare_numerator', 'frac_same_whole']),
    '3.MD.A.1': P(['measurement:time_1min', 'measurement:elapsed_mixed', 'measurement:elapsed_find_duration', 'measurement:elapsed_find_start'], ['word problems adding and subtracting time intervals (the skills are bare time lines)'], ['elapsed_stories']),
    '3.MD.A.2': P(['measurement:mass_volume_liquid'], ['estimate liquid volumes and masses', 'one-step word problems (+ − × ÷) with masses or volumes in the same units'], ['mass_ops', 'mass_scales'], 'comparing volumes without a scale: comparing:compare_capacity (build lane k2); estimating needs the scaled jug'),
    '3.MD.B.3': P(['graphs:bar_graph', 'graphs:pictograph', 'graphs:build_bar_graph'], ['draw a scaled picture graph and a scaled bar graph (the build skills use a scale of 1)'], ['bar_graph_scale', 'pictogram_scale']),
    '3.MD.B.4': P(['measurement:reading_ruler_hard', 'graphs:line_plot'], ['make the line plot from the measurements (the skill reads one)'], ['make_line_plot']),
    '3.MD.C.5a': F(['area_perimeter:area_unit_squares']),
    '3.MD.C.5b': F(['area_perimeter:area_unit_squares']),
    '3.MD.C.6': P(['area_perimeter:area_unit_squares'], ['named square units (cm², m², in², ft²) and improvised units'], ['area_tile_multiply', 'area_compare']),
    '3.MD.C.7a': P(['area_perimeter:area_unit_squares'], ['show that the tiled count equals the product of the side lengths'], ['area_tile_multiply']),
    '3.MD.C.7b': F(['area_perimeter:area']),
    '3.MD.C.7c': F(['area_perimeter:area_distributive_visual']),
    '3.MD.C.7d': F(['area_perimeter:area_polygon_decompose', 'area_perimeter:composite_shapes']),
    '3.MD.D.8': P(['area_perimeter:perimeter', 'area_perimeter:perimeter_intro', 'area_perimeter:perimeter_grid'], ['exhibit rectangles with the same perimeter and different areas, or the same area and different perimeters'], ['same_area', 'missing_lengths']),
    '3.G.A.1': P(['shapes_classify:hotspot_quads', 'shapes_classify:classify_quads'], ['draw quadrilaterals that are not rhombuses, rectangles or squares'], ['shape_draw', 'polygons']),
    '3.G.A.2': P(['fractions:identify', 'shapes_early:partition_shapes'], ['partition a shape into parts with equal areas (draw the cuts) and name each as a unit fraction'], ['partition_draw']),

    // ================================================================ Grade 4
    '4.OA.A.1': P(['multiplication:mult_comparison'], ['interpret an equation as a comparison statement (35 = 5 × 7: 5 times as many as 7)', 'write the equation for a verbal comparison'], ['comparison_statements']),
    '4.OA.A.2': P(['multiplication:mult_comparison', 'multiplication:mult_comparison_plain'], ['distinguish multiplicative comparison from additive comparison'], ['add_or_mult']),
    '4.OA.A.3': P(['division:remainder_interpret', 'division:remainder_contexts', 'algebra:multi_step_word', 'number_sense:estimate_products'], ['multistep problems using × and ÷', 'an equation with a letter for the unknown'], ['multi_step_four_ops']),
    '4.OA.B.4': F(['number_theory:factor_tchart_easy', 'number_theory:factors_identify', 'number_theory:multiples', 'number_theory:prime_composite', 'number_theory:divisibility_sort']),
    '4.OA.C.5': P(['patterns:number_patterns_rule', 'patterns:shape_pattern', 'patterns:number_pattern'], ['identify features of the pattern not explicit in the rule, and explain them informally'], ['patterns_notice']),
    '4.NBT.A.1': P(['placevalue:value', 'placevalue:identify', 'placevalue:pv_digit_drag'], ['a digit is worth ten times what it is worth in the place to its right (700 ÷ 70 = 10)'], ['value_ten_times']),
    '4.NBT.A.2': F(['placevalue:number_word_names', 'placevalue:expand', 'placevalue:compare', 'placevalue:combine']),
    '4.NBT.A.3': F(['number_sense:nearest_1000', 'number_sense:nearest_10000', 'number_sense:nearest_100000', 'number_sense:round_nl_thousands']),
    '4.NBT.B.4': F(['addition:add_10k_mixed', 'subtraction:sub_10k_mixed', 'addition:add_1m_mixed', 'subtraction:sub_1m_mixed']),
    '4.NBT.B.5': P(['multiplication:multiply', 'multiplication:area_model_mult', 'multiplication:area_model_mult_hard'], ['a 4-digit number × a 1-digit number (the sizes stop at 3 × 1)'], ['mult_4x1']),
    '4.NBT.B.6': F(['division:divide', 'division:box_division_hard', 'division:area_model_div_3by1', 'division:div_remainders'], 'divide at tiles 41 is 4-digit ÷ 1-digit'),
    '4.NF.A.1': F(['fractions:equiv_frac_visual', 'fractions:equivalent', 'fractions:equiv_frac_nv']),
    '4.NF.A.2': P(['fractions:compare', 'fractions:compare_frac_lcd', 'fractions:benchmark_fractions'], ['comparisons are valid only for the same whole', 'justify with a visual model'], ['frac_same_whole']),
    '4.NF.B.3a': F(['fraction_operations:add_fractions_like', 'fraction_operations:sub_fractions_like', 'fractions:fraction_bar_ops']),
    '4.NF.B.3b': F(['fraction_operations:decompose_fractions', 'fraction_operations:decompose_frac_nv', 'fractions:compose_target_frac']),
    '4.NF.B.3c': F(['fraction_operations:add_mixed_like', 'fraction_operations:sub_mixed_like']),
    '4.NF.B.3d': F(['fraction_operations:frac_word_problems', 'fraction_operations:frac_word_problems_plain']),
    '4.NF.B.4a': F(['fraction_operations:mult_frac_whole', 'fraction_operations:mult_frac_whole_nv']),
    '4.NF.B.4b': F(['fraction_operations:mult_frac_whole', 'fraction_operations:mult_frac_whole_nv']),
    '4.NF.B.4c': F(['fraction_operations:frac_word_mixed', 'fraction_operations:frac_word_mixed_plain', 'fractions:fraction_of_set_hard']),
    '4.NF.C.5': F(['fraction_operations:frac_10_100', 'fraction_operations:frac_10_100_nv']),
    '4.NF.C.6': F(['conversions:d_to_f', 'conversions:f_to_d', 'decimals:decimal_nl_drag']),
    '4.NF.C.7': P(['decimals:compare_decimal', 'decimals:order_decimals'], ['comparisons are valid only for the same whole', 'justify with a visual model'], ['dec_compare_model']),
    '4.MD.A.1': P(['measurement:length_customary', 'measurement:length_metric', 'measurement:capacity', 'measurement:unit_conversions'], ['record equivalents in a two-column conversion table', 'time units (hr, min, sec) as conversions'], ['conversion_table', 'time_convert', 'time_facts']),
    '4.MD.A.2': P(['measurement:unit_conversion_word', 'measurement:money_change', 'measurement:elapsed_find_duration'], ['four-operation word problems with distances, liquid volumes and masses, including simple fractions or decimals', 'measurement-scale diagrams'], ['mass_ops', 'length_ops', 'money_2step', 'timetables']),
    '4.MD.A.3': F(['area_perimeter:area', 'area_perimeter:perimeter', 'area_perimeter:area_perimeter']),
    '4.MD.B.4': P(['graphs:line_plot_fractions', 'graphs:line_plot'], ['make the line plot (1/2, 1/4, 1/8)', 'add and subtract fractions using the plot (longest − shortest)'], ['make_line_plot']),
    '4.MD.C.5a': G(['an angle is measured by the fraction of a circle its arc turns through; 1/360 of a turn is a one-degree angle'], ['turns_angles']),
    '4.MD.C.5b': G(['an angle that turns through n one-degree angles measures n degrees'], ['turns_angles']),
    '4.MD.C.6': P(['angles_lines:measure_angles'], ['measure with a protractor (the skill picks the closest of four estimates)', 'sketch angles of a given measure'], ['protractor_read', 'draw_angles']),
    '4.MD.C.7': F(['angles_lines:additive_angles']),
    '4.G.A.1': P(['angles_lines:identify_angles', 'angles_lines:identify_lines'], ['identify points, lines, line segments and rays', 'draw them, and draw right, acute and obtuse angles and perpendicular and parallel lines'], ['points_lines_rays', 'draw_angles']),
    '4.G.A.2': F(['shapes_classify:classify_triangles', 'shapes_classify:classify_quads', 'shapes_early:compose_from_attributes']),
    '4.G.A.3': F(['angles_lines:symmetry', 'angles_lines:place_symmetry_lines']),

    // ================================================================ Grade 5
    '5.OA.A.1': F(['order_of_operations:oop_medium', 'order_of_operations:paren_multi', 'order_of_operations:nested_complex']),
    '5.OA.A.2': P(['algebra:build_expr_multdiv', 'algebra:build_expr_addsub'], ['write expressions with brackets that record two-step calculations', 'interpret an expression without evaluating it (3 × (18932 + 921) is three times as large)'], ['write_numeric_expression', 'compare_calcs']),
    '5.OA.B.3': P(['patterns:pattern_relationship', 'algebra:function_table_easy'], ['form ordered pairs from the two patterns and graph them'], ['pattern_pairs_graph']),
    '5.NBT.A.1': P(['placevalue:place_value_10x'], ['a digit is 10 times the place to its right and 1/10 of the place to its left, compared directly'], ['value_ten_times', 'dec_pv_within1']),
    '5.NBT.A.2': P(['placevalue:place_value_10x'], ['whole-number exponents for powers of 10'], ['pv10_exponents', 'dec_missing']),
    '5.NBT.A.3a': G(['read and write decimals to thousandths: numerals, number names and expanded form'], ['thousandths_pv', 'decimal_pv']),
    '5.NBT.A.3b': F(['decimals:compare_thousandths', 'decimals:order_decimals']),
    '5.NBT.A.4': P(['decimals:round_decimals', 'decimals:round_thousandths'], ['round to the nearest whole number'], ['round_whole']),
    '5.NBT.B.5': P(['multiplication:multiply', 'multiplication:area_model_mult_hard', 'multiplication:mult_placeholder_zero'], ['the standard algorithm beyond 2 × 2 digits (3- and 4-digit × 2-digit) worked to the end'], ['long_mult']),
    '5.NBT.B.6': F(['division:long_div_2digit', 'division:div_fix_estimate', 'division:div_zero_in_quotient']),
    '5.NBT.B.7': P(['decimals:add_decimal', 'decimals:sub_decimal', 'decimals:mult_decimal', 'decimals:div_decimal'], ['concrete models or drawings for decimal operations, related to the written method'], ['decimal_models', 'dec_known_facts']),
    '5.NF.A.1': F(['fraction_operations:add_frac_unlike', 'fraction_operations:sub_frac_unlike', 'fraction_operations:add_mixed_unlike', 'fraction_operations:sub_mixed_unlike']),
    '5.NF.A.2': P(['fraction_operations:estimate_frac_ops'], ['word problems adding and subtracting fractions with unlike denominators'], ['frac_wp_unlike', 'frac_multistep']),
    '5.NF.B.3': F(['fraction_operations:frac_as_division', 'fraction_operations:frac_as_div_nv', 'fraction_operations:frac_as_div_word']),
    '5.NF.B.4a': F(['fractions:fraction_of_set_hard', 'fraction_operations:mult_frac_frac', 'fraction_operations:mult_frac_frac_nv']),
    '5.NF.B.4b': F(['fraction_operations:mult_frac_frac', 'fraction_operations:frac_mult_word'], 'area model overlap and garden-area stories'),
    '5.NF.B.5a': F(['fraction_operations:mult_scaling', 'fraction_operations:mult_scaling_nv']),
    '5.NF.B.5b': F(['fraction_operations:mult_scaling', 'fraction_operations:mult_scaling_nv']),
    '5.NF.B.6': P(['fraction_operations:frac_mult_word', 'fraction_operations:frac_mult_word_plain'], ['real-world problems multiplying mixed numbers'], ['mult_mixed_int']),
    '5.NF.B.7a': F(['fraction_operations:div_unit_fraction', 'fraction_operations:div_unit_frac_nv']),
    '5.NF.B.7b': F(['fraction_operations:div_unit_fraction', 'fraction_operations:div_unit_frac_nv']),
    '5.NF.B.7c': F(['fraction_operations:frac_mult_word', 'fraction_operations:frac_mult_word_plain']),
    '5.MD.A.1': P(['measurement:length_metric', 'measurement:unit_conversions', 'measurement:unit_conversion_word', 'measurement:capacity'], ['multi-step real-world problems that use the conversions', 'decimal conversions (5 cm = 0.05 m)'], ['metric_calc']),
    '5.MD.B.2': P(['graphs:line_plot_fractions'], ['make the line plot', 'use fraction operations on the plotted data (redistribute equally)'], ['make_line_plot']),
    '5.MD.C.3a': G(['a unit cube has one cubic unit of volume'], ['volume_cubes']),
    '5.MD.C.3b': G(['a solid packed with n unit cubes has a volume of n cubic units'], ['volume_cubes']),
    '5.MD.C.4': G(['measure volume by counting unit cubes (cm³, in³, ft³, improvised)'], ['volume_cubes']),
    '5.MD.C.5a': P(['area_perimeter:volume'], ['pack a prism with unit cubes and show the count equals l × w × h and B × h'], ['volume_cubes']),
    '5.MD.C.5b': F(['area_perimeter:volume', 'area_perimeter:volume_composite'], 'volume_composite deals single prisms today: formula practice'),
    '5.MD.C.5c': G(['volume of two joined non-overlapping prisms (area_perimeter:volume_composite is named for this but deals one prism: its tag was moved to 5.MD.C.5b)'], ['volume_composite_repair']),
    '5.G.A.1': F(['coordinates:coordinate_q1']),
    '5.G.A.2': P(['coordinates:coordinate_graph', 'coordinates:coordinate_q1'], ['represent real-world problems by graphing points and interpret the coordinates in context'], ['coord_context', 'line_graph']),
    '5.G.B.3': F(['shapes_classify:classify_quads']),
    '5.G.B.4': F(['shapes_classify:classify_quads', 'shapes_classify:classify_triangles']),

    // ================================================================ Grade 6
    '6.RP.A.1': F(['conversions:ratio_intro']),
    '6.RP.A.2': P(['conversions:unit_rate_intro'], ['unit rates that are fractions (3/4 cup per cup) and rate language'], ['unit_rate_fraction']),
    '6.RP.A.3a': P(['conversions:equiv_ratios', 'conversions:ratio_tables'], ['plot the pairs of a ratio table on the coordinate plane', 'compare ratios with tables'], ['ratio_table_plot']),
    '6.RP.A.3b': F(['conversions:unit_rate_intro', 'conversions:double_num_line']),
    '6.RP.A.3c': F(['conversions:percent_of_number', 'conversions:find_whole_from_pct', 'conversions:percent_visual']),
    '6.RP.A.3d': G(['convert measurement units with ratio reasoning'], ['dnl_units']),
    '6.NS.A.1': G(['divide fractions by fractions, with visual models and word problems'], ['div_frac_frac']),
    '6.NS.B.2': F(['division:long_div_2digit']),
    '6.NS.B.3': P(['decimals:add_decimal', 'decimals:sub_decimal', 'decimals:mult_decimal', 'decimals:div_decimal'], ['multiply a decimal by a decimal with the standard algorithm (mult_decimal multiplies by a whole number)'], ['mult_dec_dec']),
    '6.NS.B.4': P(['number_theory:gcf_easy', 'number_theory:gcf_hard', 'number_theory:lcm'], ['the distributive property to write a sum as the GCF × a sum (36 + 8 = 4 × (9 + 2))'], ['gcf_distributive']),
    '6.NS.C.5': P(['integers:number_line_int'], ['positive and negative numbers for opposite directions and values in real contexts, and the meaning of 0'], ['negative_count']),
    '6.NS.C.6a': F(['integers:opposite_numbers']),
    '6.NS.C.6b': P(['coordinates:coordinate_all'], ['the signs of the coordinates name the quadrant', 'points that differ only by signs are reflections across an axis'], ['four_quadrants']),
    '6.NS.C.6c': F(['integers:number_line_int', 'integers:integer_nl_drag', 'coordinates:coordinate_all', 'integers:ordering_rationals']),
    '6.NS.C.7a': F(['integers:compare_int', 'integers:order_negatives']),
    '6.NS.C.7b': P(['integers:compare_int', 'integers:order_negatives'], ['write and explain order statements in real-world contexts (−3 °C > −7 °C)'], ['negative_count']),
    '6.NS.C.7c': P(['integers:abs_value'], ['absolute value as a magnitude in a real-world situation (a debt)'], ['abs_context']),
    '6.NS.C.7d': G(['distinguish comparisons of absolute value from statements about order'], ['abs_context']),
    '6.NS.C.8': P(['coordinates:coord_distance_q1', 'coordinates:coordinate_all'], ['problems in all four quadrants', 'distances with absolute value across an axis'], ['four_quadrants']),
    '6.EE.A.1': P(['order_of_operations:exponents_simple', 'order_of_operations:oop_hard'], ['write expressions with whole-number exponents (3 × 3 × 3 × 3 = 3⁴)'], ['square_cube']),
    '6.EE.A.2a': F(['algebra:write_expression']),
    '6.EE.A.2b': G(['identify the parts of an expression (sum, term, product, factor, quotient, coefficient)'], ['parts_of_expression']),
    '6.EE.A.2c': P(['algebra:evaluate_expression', 'algebra:evaluate_expression_hard', 'order_of_operations:exponents_simple'], ['expressions from real-world formulas (V = s³, A = 6s²)'], ['formulae']),
    '6.EE.A.3': F(['algebra:distributive_expr', 'algebra:combine_like_terms']),
    '6.EE.A.4': P(['algebra:combine_like_terms'], ['decide whether two expressions are equivalent (the same value for every substitution)'], ['equiv_expressions']),
    '6.EE.B.5': F(['algebra:solve_eq_addsub', 'algebra:solve_eq_multdiv', 'algebra:inequalities', 'algebra:solve_unknown'], 'the "which candidates make it true?" bins'),
    '6.EE.B.6': F(['algebra:write_equation']),
    '6.EE.B.7': F(['algebra:solve_eq_addsub', 'algebra:solve_eq_multdiv', 'algebra:write_equation']),
    '6.EE.B.8': P(['algebra:inequalities'], ['write x > c or x < c for a real condition', 'show the infinitely many solutions on a number line'], ['inequality_write_graph']),
    '6.EE.C.9': P(['algebra:function_table_hard'], ['dependent and independent variables in a real situation', 'graph the pairs and relate the graph, table and equation'], ['two_variables']),
    '6.G.A.1': P(['area_perimeter:area_triangle', 'area_perimeter:area_polygon_decompose', 'area_perimeter:composite_shapes'], ['special quadrilaterals (parallelograms, trapezoids) and polygons decomposed into triangles'], ['parallelogram', 'area_triangle_grid']),
    '6.G.A.2': G(['volume of prisms with fractional edges, by packing unit-fraction cubes and by formula'], ['volume_fractional']),
    '6.G.A.3': P(['coordinates:coord_polygon', 'coordinates:coord_distance_q1'], ['draw polygons from vertex coordinates in all four quadrants'], ['four_quadrants']),
    '6.G.A.4': P(['shapes_classify:net_identify', 'coordinates:net_surface_area'], ['nets with triangles and the surface area of pyramids and triangular prisms'], ['net_sa_triangles']),
    '6.SP.A.1': F(['data_analysis:statistical_question']),
    '6.SP.A.2': G(['a distribution described by its centre, spread and overall shape'], ['describe_distribution']),
    '6.SP.A.3': P(['data_analysis:mean', 'data_analysis:median', 'data_analysis:range'], ['recognise which measures summarise the centre and which describe the variation'], ['describe_distribution']),
    '6.SP.B.4': P(['data_analysis:box_plot_intro', 'data_analysis:histogram_read'], ['display the data: make dot plots, histograms and box plots (the skills only read them)'], ['make_histogram_box', 'make_line_plot']),
    '6.SP.B.5a': F(['data_analysis:histogram_read']),
    '6.SP.B.5b': G(['describe the attribute measured, how it was measured and its units'], ['describe_distribution']),
    '6.SP.B.5c': P(['data_analysis:mean', 'data_analysis:median', 'data_analysis:box_plot_intro', 'data_analysis:mad'], ['describe the overall pattern and striking deviations (outliers) in context'], ['describe_distribution']),
    '6.SP.B.5d': G(['relate the choice of centre and variability measures to the shape of the distribution'], ['describe_distribution']),
};

export const EE_AUDIT = {
    // ================================================================ K
    'M.EE.K.CC.1': F(['counting:count_sequence', 'counting:number_seq_fill']),
    'M.EE.K.CC.4': F(['counting:count_objects']),
    'M.EE.K.CC.6': P(['composing:ten_frame_build', 'counting:count_objects'], ['count out up to three objects from a larger set'], ['ten_count_out']),
    'M.EE.K.CC.7': F(['comparing:compare_groups']),
    'M.EE.K.OA.1': F(['addition:add_5_pictures', 'subtraction:sub_5_pictures']),
    'M.EE.K.MD.1': F(['comparing:compare_objects', 'comparing:sort_into_groups'], 'sort by big / small and heavy / light: sort_into_groups attr size / weight (build lane k2)'),
    'M.EE.K.MD.2': F(['comparing:compare_objects', 'measurement:heavier_lighter_visual', 'comparing:sort_into_groups'], 'classify into groups by an attribute: sort_into_groups (build lane k2)'),
    'M.EE.K.MD.3': F(['comparing:classify_count', 'comparing:sort_into_groups'], 'by kind, shape, size and heavy / light: sort_into_groups (build lane k2)'),
    'M.EE.K.G.2': F(['shapes_early:name_2d_shapes', 'shapes_early:shape_name_match_2d'], 'matching shapes: "click all the triangles"'),
    'M.EE.K.G.3': F(['shapes_early:name_2d_shapes'], 'matching shapes of one kind'),
    // ================================================================ 1
    'M.EE.1.OA.1': F(['addition:add_5_pictures', 'subtraction:sub_5_pictures', 'addition:add_wp_20']),
    'M.EE.1.OA.2': F(['addition:add_5_pictures', 'addition:add_wp_10'], 'putting two sets together'),
    'M.EE.1.OA.5': F(['placevalue:more_less_10', 'addition:nl_add'], 'one more and one less with the strip support'),
    'M.EE.1.OA.7': F(['comparing:compare_groups'], 'direction "same"'),
    'M.EE.1.NBT.1': F(['counting:number_seq_fill', 'counting:count_objects']),
    'M.EE.1.NBT.2': F(['composing:make_ten', 'composing:ten_frame_build']),
    'M.EE.1.NBT.3': F(['comparing:compare_groups']),
    'M.EE.1.NBT.4': F(['composing:number_bonds', 'composing:bonds_in_order'], 'every way to make 2 to 5: bonds_in_order "Bonds of 2 to 5" (build lane k2)'),
    'M.EE.1.NBT.6': F(['composing:number_bonds', 'composing:bonds_in_order'], 'every split of 2 to 5: bonds_in_order "Bonds of 2 to 5" (build lane k2)'),
    'M.EE.1.MD.1': F(['shapes_early:order_objects_length', 'comparing:compare_objects']),
    'M.EE.1.MD.2': F(['comparing:compare_objects']),
    'M.EE.1.MD.3': P(['measurement:time_sense'], ['today, yesterday and tomorrow', 'morning, afternoon, day and night', 'activities before, next and after', 'telling time is the same every day'], ['day_order', 'time_talk']),
    'M.EE.1.MD.4': F(['measurement:pictograph_intro', 'graphs:tally_chart', 'comparing:sort_into_groups'], 'sorting the objects into categories first: sort_into_groups (build lane k2)'),
    'M.EE.1.G.1': G(['relative positions on, off, in and out (the attribute skills carry this EE only through the CCSS link)'], ['position_map']),
    'M.EE.1.G.2': P(['shapes_early:name_2d_shapes'], ['sort shapes of one size and orientation into groups by kind'], ['shape_sort']),
    'M.EE.1.G.3': F(['shapes_early:compose_shapes', 'shapes_early:compose_hexagon']),
    // ================================================================ 2
    'M.EE.2.OA.3': P(['patterns:halve'], ['equally distribute objects (not numbers) between two groups'], ['share_group']),
    'M.EE.2.OA.4': F(['multiplication:repeated_add_to_mult', 'multiplication:arrays_groups']),
    'M.EE.2.NBT.1': F(['composing:base10_build', 'composing:teen_compose']),
    'M.EE.2.NBT.2': P(['counting:count_objects', 'counting:count_sequence'], ['count out 1-30 objects from a larger group'], ['ten_count_out'], 'count 21-30 things: count_objects band 30, rows of ten (build lane k2)'),
    'M.EE.2.NBT.3': F(['composing:number_word_form', 'counting:number_seq_fill']),
    'M.EE.2.NBT.4': F(['comparing:compare_groups', 'placevalue:compare']),
    'M.EE.2.NBT.5': P(['number_ops_mixed:which_sign'], ['the meaning of + (combine, plus, add), − (separate, take) and = (the same amount as) in words'], ['sign_meanings']),
    'M.EE.2.NBT.6': F(['composing:number_bonds', 'composing:make_ten', 'composing:bonds_in_order'], 'every bond of 5 to 10 in order: bonds_in_order (build lane k2)'),
    'M.EE.2.NBT.7': F(['addition:add_10_mixed', 'subtraction:sub_10_mixed', 'addition:add_5_pictures', 'addition:add_facts']),
    'M.EE.2.MD.1': F(['shapes_early:measure_nonstandard']),
    'M.EE.2.MD.3': P(['shapes_early:order_objects_length'], ['order objects by lengths measured in non-standard units'], ['order_length_tasks']),
    'M.EE.2.MD.4': P(['shapes_early:order_objects_length'], ['order objects by lengths measured in non-standard units'], ['order_length_tasks']),
    'M.EE.2.MD.5': G(['increase or decrease a length by adding or subtracting units'], ['length_ops']),
    'M.EE.2.MD.6': F(['addition:nl_add', 'addition:number_line_add']),
    'M.EE.2.MD.7': P(['measurement:time_sense'], ['identify the digital hour that matches a routine activity'], ['routine_hour']),
    'M.EE.2.MD.8': F(['measurement:coin_value', 'measurement:money_compare']),
    'M.EE.2.MD.9': F(['graphs:build_bar_graph']),
    'M.EE.2.MD.10': F(['graphs:build_bar_graph', 'graphs:build_pictograph']),
    'M.EE.2.G.1': F(['shapes_early:name_2d_shapes']),
    // ================================================================ 3
    'M.EE.3.OA.1': F(['multiplication:repeated_add_to_mult', 'multiplication:arrays_groups']),
    'M.EE.3.OA.2': F(['multiplication:repeated_add_to_mult']),
    'M.EE.3.OA.6': F(['addition:add_facts', 'subtraction:sub_facts']),
    'M.EE.3.OA.7': F(['addition:add_wp_20', 'subtraction:sub_wp_20']),
    'M.EE.3.OA.8': F(['patterns:count_by_fill', 'patterns:number_patterns_rule']),
    'M.EE.3.NBT.1': F(['number_sense:between_tens', 'number_sense:rounding_visual']),
    'M.EE.3.NBT.2': F(['composing:tens_foundation_visual', 'composing:base10_build']),
    'M.EE.3.NBT.3': F(['composing:tens_foundation_visual', 'measurement:money_count']),
    'M.EE.3.NF.1': F(['fractions:identify', 'fractions:shade_fraction']),
    'M.EE.3.NF.2': F(['fractions:identify']),
    'M.EE.3.NF.3': F(['composing:compose_whole', 'composing:whole_as_fraction']),
    'M.EE.3.MD.1': F(['measurement:time_hour', 'measurement:time_analog_digital']),
    'M.EE.3.MD.2': P(['measurement:mass_volume_liquid'], ['identify the measuring tool (scale, jug) for a one-step mass or volume problem'], ['mass_scales']),
    'M.EE.3.MD.3': F(['graphs:bar_graph', 'graphs:pictograph']),
    'M.EE.3.MD.4': F(['measurement:reading_ruler', 'measurement:reading_ruler_hard']),
    'M.EE.3.G.1': F(['shapes_early:shape_attributes', 'shapes_early:count_sides_vertices_2d']),
    'M.EE.3.G.2': P(['fractions:identify'], ['recognise shapes partitioned into equal areas (equal versus unequal)'], ['fraction_parts', 'partition_draw']),
    // ================================================================ 4
    'M.EE.4.OA.1': F(['multiplication:repeated_add_to_mult']),
    'M.EE.4.OA.2': F(['multiplication:repeated_add_to_mult']),
    'M.EE.4.OA.3': F(['addition:add_wp_100', 'subtraction:sub_wp_100', 'algebra:tape_diagram']),
    'M.EE.4.OA.4': F(['multiplication:arrays_groups', 'multiplication:dot_array_mult']),
    'M.EE.4.OA.5': F(['patterns:shape_pattern']),
    'M.EE.4.NBT.2': P(['placevalue:compare'], ['compare whole numbers to 10 (the lowest band of compare is 99)'], ['compare_small']),
    'M.EE.4.NBT.3': P(['number_sense:estimate_sums_diffs'], ['estimates for real-world problems within 30'], ['money_estimate']),
    'M.EE.4.NBT.4': F(['addition:add_100_mixed', 'subtraction:sub_100_mixed']),
    'M.EE.4.NF.1': F(['fractions:identify']),
    'M.EE.4.NF.2': F(['fractions:identify', 'fractions:benchmark_fractions']),
    'M.EE.4.NF.3': F(['fractions:identify']),
    'M.EE.4.MD.1': F(['measurement:length_customary', 'measurement:length_metric', 'measurement:unit_conversions']),
    'M.EE.4.MD.2': P(['measurement:time_hour', 'measurement:mass_volume_liquid', 'measurement:coin_value'], ['use standard measurement to compare the lengths of objects (part c)'], ['ruler_difference']),
    'M.EE.4.MD.3': F(['area_perimeter:area_unit_squares']),
    'M.EE.4.MD.4': F(['graphs:bar_graph', 'graphs:build_bar_graph']),
    'M.EE.4.MD.5': F(['angles_lines:identify_angles', 'measurement:money_count'], 'angles in shapes: identify_angles; part d (Qatari currency): money_count at currency QAR'),
    'M.EE.4.MD.6': P(['angles_lines:measure_angles'], ['compare two angles: larger, smaller or the same'], ['turns_angles']),
    'M.EE.4.G.1': F(['angles_lines:identify_lines']),
    'M.EE.4.G.2': F(['shapes_classify:classify_triangles', 'shapes_early:shape_attributes']),
    'M.EE.4.G.3': F(['angles_lines:symmetry']),
    // ================================================================ 5
    'M.EE.5.OA.3': F(['patterns:number_pattern', 'patterns:pattern_relationship']),
    'M.EE.5.NBT.1': P(['placevalue:compare'], ['compare numbers to 99 using place-value models'], ['compare_small']),
    'M.EE.5.NBT.2': P(['placevalue:place_value_10x'], ['compare powers of ten by their number of zeros'], ['pv10_exponents']),
    'M.EE.5.NBT.3': F(['placevalue:compare']),
    'M.EE.5.NBT.4': P(['number_sense:estimate_sums_diffs'], ['estimates for real-world problems within 100'], ['money_estimate']),
    'M.EE.5.NBT.5': F(['multiplication:mult_facts'], 'constant 0, 1, 2, 5, 10'),
    'M.EE.5.NBT.6': F(['division:div_word_problems', 'division:share_into_groups'], 'fair shares and equal groups'),
    'M.EE.5.NBT.7': F(['fractions:write_fraction'], 'tenths models'),
    'M.EE.5.NF.1': F(['fractions:identify']),
    'M.EE.5.MD.1': F(['measurement:time_quarter', 'measurement:reading_ruler', 'measurement:mass_volume_liquid', 'measurement:money_compare']),
    'M.EE.5.MD.2': F(['graphs:bar_graph', 'graphs:pictograph', 'graphs:line_plot_g2']),
    'M.EE.5.MD.3': F(['shapes_early:name_3d_shapes']),
    'M.EE.5.MD.4': G(['the volume of a rectangular prism by counting unit cubes'], ['volume_cubes']),
    'M.EE.5.MD.5': P(['area_perimeter:volume'], ['count unit cubes (the skills use the formula)'], ['volume_cubes']),
    'M.EE.5.G.1': F(['shapes_early:compose_from_attributes']),
    'M.EE.5.G.2': F(['shapes_early:compose_from_attributes']),
    'M.EE.5.G.3': F(['shapes_classify:classify_quads', 'shapes_early:compose_from_attributes']),
    'M.EE.5.G.4': F(['shapes_classify:classify_quads', 'shapes_early:compose_from_attributes']),
    // ================================================================ 6
    'M.EE.6.RP.1': F(['conversions:ratio_intro']),
    'M.EE.6.NS.1': P(['fractions:compare'], ['compare two unit fractions (the skill does not target them)'], ['compare_numerator']),
    'M.EE.6.NS.2': F(['division:div_word_problems', 'division:share_into_groups']),
    'M.EE.6.NS.3': F(['multiplication:mult_facts'], 'constant 3, 4, 9'),
    'M.EE.6.NS.5': P(['integers:number_line_int'], ['describe quantities with opposite directions or values (temperature above / below zero) as positive and negative'], ['negative_count']),
    'M.EE.6.NS.6': P(['integers:number_line_int'], ['describe quantities with opposite directions or values as positive and negative'], ['negative_count']),
    'M.EE.6.NS.7': P(['integers:number_line_int'], ['describe quantities with opposite directions or values as positive and negative'], ['negative_count']),
    'M.EE.6.NS.8': P(['integers:number_line_int'], ['describe quantities with opposite directions or values as positive and negative'], ['negative_count']),
    'M.EE.6.EE.1-2': F(['order_of_operations:compare_expressions', 'algebra:inequalities'], 'true / false sorts of equations and inequalities'),
    'M.EE.6.EE.3': P(['addition:add_sub_fact_family'], ['identify equivalent numerical expressions using the properties of addition'], ['compare_calcs', 'equiv_expressions']),
    'M.EE.6.EE.5-7': F(['algebra:write_equation']),
    'M.EE.6.G.1': F(['area_perimeter:area_unit_squares']),
    'M.EE.6.G.2': P(['area_perimeter:volume'], ['count unit cubes to solve volume problems'], ['volume_cubes']),
    'M.EE.6.SP.1': F(['graphs:build_bar_graph']),
    'M.EE.6.SP.2': F(['graphs:build_bar_graph']),
    'M.EE.6.SP.4': F(['graphs:build_bar_graph', 'graphs:build_pictograph']),
    'M.EE.6.SP.5': F(['graphs:bar_graph', 'data_analysis:median']),
};

/*
 * THE TAG FIXES applied to SKILL_STANDARDS (js/modules/standards.js) by this audit, for the report.
 *   mis-tag  the skill did not teach the code: removed or moved to the code it does teach;
 *   add      the skill teaches the code but was not tagged (so the audit's `by` skill carries it);
 *   flag     the tag stays, but the skill does not deal what it promises: a repair is on the list.
 */
export const TAG_FIXES = [
    { kind: 'mis-tag', skill: 'composing:base10_regroup', remove: ['2.NBT.A.1a'], add: [], why: 'it trades 1 ten for 10 ones at bands 50 and 99; 100 as ten tens is never shown (1.NBT.B.2a stays)' },
    { kind: 'mis-tag', skill: 'graphs:line_plot', remove: ['2.MD.D.9', 'M.EE.2.MD.9'], add: ['4.MD.B.4', 'M.EE.4.MD.4'], why: 'every plot is in fractions of an inch (1/4, 1/8), so it is the Grade 3-4 line plot, not the Grade 2 whole-unit one' },
    { kind: 'mis-tag', skill: 'algebra:tape_diagram', remove: ['4.OA.A.3', '3.OA.D.8'], add: ['2.OA.A.1', '3.NBT.A.2'], why: 'one-step addition and subtraction with a bar model (to 200); no second step and no × or ÷' },
    { kind: 'mis-tag', skill: 'algebra:tape_diagram_plain', remove: ['4.OA.A.3', '3.OA.D.8'], add: ['2.OA.A.1', '3.NBT.A.2'], why: 'the same one-step items without the bar' },
    { kind: 'mis-tag', skill: 'number_ops_mixed:word_problems_mixed', remove: ['3.OA.D.8', '4.OA.A.3'], add: ['3.OA.A.3', '2.OA.A.1', '4.OA.A.2'], why: 'a pool of ONE-step stories (+, −, ×, ÷, times as many); two-step and multistep problems never occur' },
    { kind: 'mis-tag', skill: 'number_ops_mixed:word_problems_mixed_plain', remove: ['3.OA.D.8', '4.OA.A.3'], add: ['3.OA.A.3', '2.OA.A.1', '4.OA.A.2'], why: 'the same one-step pool without pictures' },
    { kind: 'mis-tag', skill: 'area_perimeter:volume_composite', remove: ['5.MD.C.5c'], add: ['5.MD.C.5b'], why: 'despite its name it deals ONE rectangular prism or cube (V = l × w × h); a repair is on the build list (volume_composite_repair)' },
    { kind: 'mis-tag', skill: 'order_of_operations:compare_expressions', remove: ['5.OA.A.2'], add: ['M.EE.6.EE.1-2'], why: 'the pupil evaluates both sides (5.OA.A.1); nothing is written or interpreted without evaluating' },
    { kind: 'flag', skill: 'addition:equal_sign', remove: [], add: [], why: 'routes to the operations generator and deals plain column addition ("5 + 11 = ?"): its true/false generator in gen-algebraic.js is never reached; repair on the build list (equal_sign_repair)' },
    // missing tags: the skill teaches the code (its items were read) but was not tagged
    { kind: 'add', skill: 'counting:number_seq_fill', remove: [], add: ['K.CC.A.1', 'M.EE.K.CC.1'], why: 'counts by ones to 100 (step 1, band 100)' },
    { kind: 'add', skill: 'composing:hundreds_chart_fill', remove: [], add: ['K.CC.A.1'], why: 'counting by ones to 100 on the chart' },
    { kind: 'add', skill: 'counting:count_objects', remove: [], add: ['K.CC.A.3', 'K.CC.B.4a', 'M.EE.1.NBT.1'], why: 'writes the numeral for a count (1-20) with one-to-one touch counting' },
    { kind: 'add', skill: 'addition:add_facts', remove: [], add: ['K.OA.A.5', 'M.EE.2.NBT.7'], why: 'band 5 is fluency within 5' },
    { kind: 'add', skill: 'subtraction:sub_facts', remove: [], add: ['K.OA.A.5'], why: 'band 5 is fluency within 5' },
    { kind: 'add', skill: 'composing:teen_compose', remove: [], add: ['1.NBT.B.2b'], why: '11-19 as a ten and some ones' },
    { kind: 'add', skill: 'composing:ten_frame_build_teen', remove: [], add: ['1.NBT.B.2b'], why: 'builds 11-19 as one full frame and ones' },
    { kind: 'add', skill: 'graphs:build_pictograph', remove: [], add: ['1.MD.C.4', 'M.EE.2.MD.10', 'M.EE.6.SP.4'], why: 'organises and represents data in up to three categories' },
    { kind: 'add', skill: 'algebra:multi_step_word', remove: [], add: ['2.OA.A.1'], why: 'two-step addition and subtraction problems within 100' },
    { kind: 'add', skill: 'algebra:multi_step_word_plain', remove: [], add: ['2.OA.A.1'], why: 'two-step addition and subtraction problems within 100' },
    { kind: 'add', skill: 'area_perimeter:area_unit_squares', remove: [], add: ['3.MD.C.5a', '3.MD.C.7a', 'M.EE.4.MD.3', 'M.EE.6.G.1'], why: 'measures area in unit squares; the tiled rectangle is the start of 3.MD.C.7a' },
    { kind: 'add', skill: 'shapes_classify:classify_quads', remove: [], add: ['3.G.A.1', '4.G.A.2'], why: 'rhombuses, rectangles and squares as quadrilaterals; parallel sides and right angles as the sorting property' },
    { kind: 'add', skill: 'shapes_early:partition_shapes', remove: [], add: ['3.G.A.2'], why: 'equal parts named as unit fractions' },
    { kind: 'add', skill: 'fractions:equiv_frac_visual', remove: [], add: ['4.NF.A.1'], why: 'two models of equivalent fractions with different numbers and sizes of parts' },
    { kind: 'add', skill: 'shapes_early:compose_from_attributes', remove: [], add: ['4.G.A.2', 'M.EE.5.G.1', 'M.EE.5.G.2', 'M.EE.5.G.3', 'M.EE.5.G.4'], why: 'selects shapes by parallel sides and right angles (4.G.A.2); sorts shapes by a shared attribute (the Grade 5 EEs)' },
    { kind: 'add', skill: 'multiplication:multiply', remove: [], add: ['5.NBT.B.5'], why: 'tiles 22 is 2-digit × 2-digit with the standard algorithm' },
    { kind: 'add', skill: 'fraction_operations:frac_mult_word', remove: [], add: ['5.NF.B.4b'], why: 'area of a rectangle with fractional side lengths' },
    { kind: 'add', skill: 'measurement:capacity', remove: [], add: ['5.MD.A.1'], why: 'converts 500 mL to 0.5 L' },
    { kind: 'add', skill: 'coordinates:coordinate_q1', remove: [], add: ['5.G.A.2'], why: 'graphing points in the first quadrant' },
    { kind: 'add', skill: 'shapes_classify:classify_triangles', remove: [], add: ['5.G.B.4'], why: 'classifies triangles by sides and angles' },
    { kind: 'add', skill: 'decimals:add_decimal', remove: [], add: ['6.NS.B.3'], why: 'multi-digit decimals in columns' },
    { kind: 'add', skill: 'decimals:sub_decimal', remove: [], add: ['6.NS.B.3'], why: 'multi-digit decimals in columns' },
    { kind: 'add', skill: 'decimals:mult_decimal', remove: [], add: ['6.NS.B.3'], why: 'the standard algorithm for decimal × whole' },
    { kind: 'add', skill: 'coordinates:coordinate_all', remove: [], add: ['6.NS.C.8'], why: 'plotting in all four quadrants' },
    { kind: 'add', skill: 'algebra:solve_eq_addsub', remove: [], add: ['6.EE.B.5'], why: 'the "which candidates make it true?" bins are substitution from a set' },
    { kind: 'add', skill: 'algebra:solve_eq_multdiv', remove: [], add: ['6.EE.B.5'], why: 'the same substitution bins' },
    { kind: 'add', skill: 'data_analysis:histogram_read', remove: [], add: ['6.SP.B.5a'], why: '"how many data points in total?" reports the number of observations' },
    // Essential Elements whose own wording the skill practises (standards.js header rule)
    { kind: 'add', skill: 'shapes_early:name_2d_shapes', remove: [], add: ['M.EE.K.G.3', 'M.EE.1.G.2'], why: 'matching and sorting shapes of one kind ("click all the triangles")' },
    { kind: 'add', skill: 'addition:add_5_pictures', remove: [], add: ['M.EE.1.OA.2'], why: 'putting two sets together' },
    { kind: 'add', skill: 'addition:add_wp_10', remove: [], add: ['M.EE.1.OA.2'], why: 'putting two sets together in a story' },
    { kind: 'add', skill: 'comparing:compare_groups', remove: [], add: ['M.EE.1.OA.7'], why: 'direction "same": two groups with an equal quantity' },
    { kind: 'add', skill: 'comparing:compare_objects', remove: [], add: ['M.EE.1.MD.1', 'M.EE.1.MD.2'], why: 'longer / shorter, taller / shorter' },
    { kind: 'add', skill: 'shapes_early:compose_shapes', remove: [], add: ['M.EE.1.G.3'], why: 'put two shapes together to make a shape' },
    { kind: 'add', skill: 'shapes_early:compose_hexagon', remove: [], add: ['M.EE.1.G.3'], why: 'put shapes together to make a shape' },
    { kind: 'add', skill: 'counting:count_sequence', remove: [], add: ['M.EE.2.NBT.2'], why: 'names the next number in a sequence 1-10' },
    { kind: 'add', skill: 'number_ops_mixed:which_sign', remove: [], add: ['M.EE.2.NBT.5'], why: 'choosing the sign that makes the equation true' },
    { kind: 'add', skill: 'shapes_early:measure_nonstandard', remove: [], add: ['M.EE.2.MD.1'], why: 'measures length with non-standard units' },
    { kind: 'add', skill: 'shapes_early:order_objects_length', remove: [], add: ['M.EE.2.MD.3', 'M.EE.2.MD.4'], why: 'orders objects by length' },
    { kind: 'add', skill: 'measurement:time_sense', remove: [], add: ['M.EE.2.MD.7', 'M.EE.1.MD.3'], why: 'routine activities with their digital times' },
    { kind: 'add', skill: 'graphs:build_bar_graph', remove: [], add: ['M.EE.2.MD.9', 'M.EE.4.MD.4', 'M.EE.6.SP.1', 'M.EE.6.SP.2', 'M.EE.6.SP.4'], why: 'creates a bar graph from sorted data' },
    { kind: 'add', skill: 'multiplication:repeated_add_to_mult', remove: [], add: ['M.EE.3.OA.2', 'M.EE.4.OA.1', 'M.EE.4.OA.2'], why: 'repeated addition connected to multiplication' },
    { kind: 'add', skill: 'composing:tens_foundation_visual', remove: [], add: ['M.EE.3.NBT.3'], why: 'counts by tens with rods' },
    { kind: 'add', skill: 'fractions:identify', remove: [], add: ['M.EE.3.NF.2', 'M.EE.4.NF.2', 'M.EE.4.NF.3', 'M.EE.5.NF.1'], why: 'identifies a fractional part of a whole, halves and fourths' },
    { kind: 'add', skill: 'shapes_early:shape_attributes', remove: [], add: ['M.EE.3.G.1', 'M.EE.4.G.2'], why: 'describes sides and vertices of 2-D shapes' },
    { kind: 'add', skill: 'shapes_early:count_sides_vertices_2d', remove: [], add: ['M.EE.3.G.1'], why: 'describes sides and vertices of 2-D shapes' },
    { kind: 'add', skill: 'addition:add_wp_100', remove: [], add: ['M.EE.4.OA.3'], why: 'one-step real-world addition within 100' },
    { kind: 'add', skill: 'subtraction:sub_wp_100', remove: [], add: ['M.EE.4.OA.3'], why: 'one-step real-world subtraction within 100' },
    { kind: 'add', skill: 'multiplication:arrays_groups', remove: [], add: ['M.EE.4.OA.4'], why: 'shows a product as equal groups or an array' },
    { kind: 'add', skill: 'multiplication:dot_array_mult', remove: [], add: ['M.EE.4.OA.4'], why: 'shows a product as an array' },
    { kind: 'add', skill: 'number_sense:estimate_sums_diffs', remove: [], add: ['M.EE.4.NBT.3', 'M.EE.5.NBT.4'], why: 'estimates sums and differences by rounding' },
    { kind: 'add', skill: 'measurement:mass_volume_liquid', remove: [], add: ['M.EE.4.MD.2', 'M.EE.5.MD.1'], why: 'measures mass and volume on standard scales' },
    { kind: 'add', skill: 'angles_lines:identify_angles', remove: [], add: ['M.EE.4.MD.5'], why: 'finds the angles in a shape' },
    { kind: 'add', skill: 'placevalue:compare', remove: [], add: ['M.EE.5.NBT.1'], why: 'compares numbers to 99 by place value' },
    { kind: 'add', skill: 'multiplication:mult_facts', remove: [], add: ['M.EE.5.NBT.5', 'M.EE.6.NS.3'], why: 'products with the constants 0, 1, 2, 5, 10 and 3, 4, 9' },
    { kind: 'add', skill: 'division:div_word_problems', remove: [], add: ['M.EE.5.NBT.6', 'M.EE.6.NS.2'], why: 'fair shares: "place equally … how many in each group?"' },
    { kind: 'add', skill: 'division:share_into_groups', remove: [], add: ['M.EE.5.NBT.6', 'M.EE.6.NS.2'], why: 'equal groups with counters' },
    { kind: 'add', skill: 'fractions:write_fraction', remove: [], add: ['M.EE.5.NBT.7'], why: 'models of tenths (7/10)' },
    { kind: 'add', skill: 'measurement:time_quarter', remove: [], add: ['M.EE.5.MD.1'], why: 'time to the quarter hour' },
    { kind: 'add', skill: 'measurement:reading_ruler', remove: [], add: ['M.EE.5.MD.1'], why: 'measures length with a standard unit' },
    { kind: 'add', skill: 'graphs:bar_graph', remove: [], add: ['M.EE.5.MD.2', 'M.EE.6.SP.5'], why: 'interprets and summarises data in a bar graph' },
    { kind: 'add', skill: 'graphs:pictograph', remove: [], add: ['M.EE.5.MD.2'], why: 'interprets a picture graph' },
    { kind: 'add', skill: 'graphs:line_plot_g2', remove: [], add: ['M.EE.5.MD.2'], why: 'interprets a line plot' },
    { kind: 'add', skill: 'fractions:compare', remove: [], add: ['M.EE.6.NS.1'], why: 'compares fractions, unit fractions among them' },
    { kind: 'add', skill: 'integers:number_line_int', remove: [], add: ['M.EE.6.NS.7', 'M.EE.6.NS.8'], why: 'negative numbers on a line: part of the opposite-quantity EE' },
    { kind: 'add', skill: 'algebra:inequalities', remove: [], add: ['M.EE.6.EE.1-2'], why: 'true or false for an inequality' },
    { kind: 'add', skill: 'addition:add_sub_fact_family', remove: [], add: ['M.EE.6.EE.3'], why: 'turnaround facts are equivalent numerical expressions' },
    { kind: 'add', skill: 'data_analysis:median', remove: [], add: ['M.EE.6.SP.5'], why: 'summarises a data set' },
    { kind: 'add', skill: 'measurement:money_compare', remove: [], add: ['M.EE.2.MD.8'], why: 'which collection has more money: money has value (the EE linked to its own 2.MD.C.8 tag was missing)' },
];
