// Shared mutable state object - all modules import the same reference
export const state = {
    xp: 0,
    streak: 0,
    lastPlayDate: null,
    badges: [],
    ttsEnabled: true,
    category: "operations",
    skill: "add",
    difficulty: "medium", // Deprecated: always "medium". Difficulty baked into skill variants.
    range: 100,
    decimalPlaces: 0,
    timerDuration: 0,
    problemCount: 20,
    selectedNumbers: Array.from({ length: 12 }, (_, i) => i + 1),
    gameMode: "practice",
    hasAnswered: false,
    lastAnswerCorrect: false,
    // Wrong-answer retry tracking (Practice + MAP Practice)
    currentQAttempts: 0,         // count of wrong attempts on current question
    currentQAttemptHistory: [],  // submitted-but-wrong answers (for cross-out display)
    qCount: 0,
    score: 0,
    currentQ: null,
    timerInterval: null,
    timerRemaining: 0,
    heroPos: 70,
    monsterPos: 10,
    racePos: 0,
    cpuPos: 0,
    cpuInterval: null,
    bossInterval: null,
    worksheetQs: [],
    sessionHistory: [],
    sessionStartTime: null,
    historyFilter: 'today',
    streakDays: [],
    // Progress Tracking
    skillProgress: {},
    recentPerformance: [],
    adaptiveDifficulty: 'medium',
    consecutiveCorrect: 0,
    consecutiveWrong: 0,
    questionStartTime: null,
    // Gamification
    level: 1,
    xpForCurrentLevel: 0,
    xpToNextLevel: 100,
    sessionTimeMs: 0,
    sessionTimerInterval: null,
    lastTimeMilestone: 0,
    cumulativeTimeMs: 0,
    sessionStreak: 0,
    lastStreakBonus: 0,
    correctSinceLastSurprise: 0,
    nextSurpriseAt: 0,
    spacedRepetition: {},
    reviewStreak: 0,
    lastReviewDate: null,
    totalProblemsThisSession: 0,
    isReviewSession: false,
    wrongThenRightTracking: { wrongCount: 0, recovering: false, rightCount: 0 },
    isMixedMode: false,
    mixedModeSettings: null,
    // Game Stats Banner (daily — resets each new day)
    effortScore: 0,
    dailyCorrect: 0,
    dailyTotal: 0,
    dailyActiveTimeMs: 0,
    dailyDate: null,
    lastInteractionTime: 0,
    isIdlePaused: false,
    _idleModalShown: false,
    bannerTimerInterval: null,
    bannerGameStartTime: 0,
    celebrationsEnabled: true,
    // Practice log (7-day per-skill tracking)
    practiceLog: {},
    // On-task timer
    questionElapsedMs: 0,
    questionTimerInterval: null,
    savedMoodFace: null,
    // Teacher sharing / infinity mode
    infinityMode: false,
    roundNumber: 1,
    roundDurationMs: 180000,
    roundStartTime: 0,
    shareSettings: null,
    landingSettings: null,
    _timerProgressShown: {},
    shareLinkType: 'direct',
    wrongStreak: 0,
    lastCorrectAnswerTime: 0,
    timerFrozen: false,
    gameTimerPaused: false,
    // Per-skill session tracking (for Learning Stats)
    currentSessionSkills: {},  // { skillId: { attempted: 0, correct: 0, timeMs: 0, label: '' } }
    statsFilterDays: 0,  // 0 = all time, 1 = today, 7 = week, 30 = month
    // Quiz/Test mode
    quizMode: false,
    currentQuiz: null,
    currentQuizResult: null,
    quizQuestionIndex: 0,
    quizOrder: [],
    quizSectionIndex: 0,
    quizAllQuestions: [],
    // MAP Test Practice mode
    mapMode: false,
    mapTier: null,                  // 'k2' | '35'
    mapSessionMode: null,           // 'simulation' | 'practice'
    mapSelectedBands: [],
    mapSelectedDomains: [],
    mapItemCount: 0,
    mapItemCountTarget: 20,
    mapCurrentRit: 170,
    mapCorrectStreak: 0,
    mapIncorrectStreak: 0,
    mapPerDomainItems: { OA: 0, NO: 0, MD: 0, G: 0 },
    mapPerDomainCorrect: { OA: 0, NO: 0, MD: 0, G: 0 },
    mapPerDomainRitSum: { OA: 0, NO: 0, MD: 0, G: 0 },
    mapHistory: [],
    mapStartedAt: null,
    mapEndedAt: null,
    mapTimeCapMs: 0,
    mapFeatures: {
        ttsEnabled: false,
        audioAutoPlay: false,
        largeTargets: false,
        highContrast: 'default',
        fontScale: 1.0,
        reduceMotion: false,
        clickClickOnly: false,
        numpadOnly: false,
        answerEliminator: false,
        scratchpadOpen: false,
        calculatorEnabled: false,
        language: 'en',
    },
    lastMapResult: null,
    // Tab switch detection
    tabAwayTimeMs: 0,
    tabSwitchCount: 0,
    // Fullscreen mode
    fullscreenPromptShown: false,
    fullscreenExitToastShown: false,
    isFullscreen: false,
};
