// Shared mutable state object - all modules import the same reference
export const state = {
    xp: 0,
    streak: 0,
    lastPlayDate: null,
    badges: [],
    ttsEnabled: true,
    category: "operations",
    skill: "add",
    difficulty: "medium", // Deprecated: always "medium". Difficulty baked into skill variants.
    range: 100,
    decimalPlaces: 1,
    timerDuration: 0,
    problemCount: 20,
    selectedNumbers: Array.from({ length: 12 }, (_, i) => i + 1),
    gameMode: "practice",
    hasAnswered: false,
    qCount: 0,
    score: 0,
    currentQ: null,
    timerInterval: null,
    timerRemaining: 0,
    heroPos: 70,
    monsterPos: 10,
    racePos: 0,
    cpuPos: 0,
    cpuInterval: null,
    bossInterval: null,
    worksheetQs: [],
    sessionHistory: [],
    sessionStartTime: null,
    historyFilter: 'today',
    streakDays: [],
    // Progress Tracking
    skillProgress: {},
    recentPerformance: [],
    adaptiveDifficulty: 'medium',
    consecutiveCorrect: 0,
    consecutiveWrong: 0,
    questionStartTime: null
};
