// Shared mutable state object - all modules import the same reference
export const state = {
    xp: 0,
    streak: 0,
    lastPlayDate: null,
    badges: [],
    ttsEnabled: true,
    category: "operations",
    skill: "add",
    difficulty: "medium", // Deprecated: always "medium". Difficulty baked into skill variants.
    range: 100,
    decimalPlaces: 1,
    timerDuration: 0,
    problemCount: 20,
    selectedNumbers: Array.from({ length: 12 }, (_, i) => i + 1),
    gameMode: "practice",
    hasAnswered: false,
    qCount: 0,
    score: 0,
    currentQ: null,
    timerInterval: null,
    timerRemaining: 0,
    heroPos: 70,
    monsterPos: 10,
    racePos: 0,
    cpuPos: 0,
    cpuInterval: null,
    bossInterval: null,
    worksheetQs: [],
    sessionHistory: [],
    sessionStartTime: null,
    historyFilter: 'today',
    streakDays: [],
    // Progress Tracking
    skillProgress: {},
    recentPerformance: [],
    adaptiveDifficulty: 'medium',
    consecutiveCorrect: 0,
    consecutiveWrong: 0,
    questionStartTime: null,
    // Gamification
    level: 1,
    xpForCurrentLevel: 0,
    xpToNextLevel: 100,
    sessionTimeMs: 0,
    sessionTimerInterval: null,
    lastTimeMilestone: 0,
    cumulativeTimeMs: 0,
    sessionStreak: 0,
    lastStreakBonus: 0,
    correctSinceLastSurprise: 0,
    nextSurpriseAt: 0,
    spacedRepetition: {},
    totalProblemsThisSession: 0,
    isReviewSession: false,
    wrongThenRightTracking: { wrongCount: 0, recovering: false, rightCount: 0 },
    isMixedMode: false,
    mixedModeSettings: null,
    // Game Stats Banner (daily — resets each new day)
    effortScore: 0,
    dailyCorrect: 0,
    dailyTotal: 0,
    dailyActiveTimeMs: 0,
    dailyDate: null,
    lastInteractionTime: 0,
    isIdlePaused: false,
    bannerTimerInterval: null,
    bannerGameStartTime: 0,
    celebrationsEnabled: true,
    // On-task timer
    questionElapsedMs: 0,
    questionTimerInterval: null,
    savedMoodFace: null,
    // Teacher sharing / infinity mode
    infinityMode: false,
    roundNumber: 1,
    roundDurationMs: 180000,
    roundStartTime: 0,
    shareSettings: null,
    landingSettings: null,
    _timerProgressShown: {},
    shareLinkType: 'direct',
    wrongStreak: 0,
    lastCorrectAnswerTime: 0,
    timerFrozen: false
};
