#!/usr/bin/env node
/*
 * ws-wrm — the White Rose Maths small-step inventory and the skill -> small-step map.
 *
 *   node tests/scripts/ws-wrm.cjs                 # GATE: validate, write design/WRM_COVERAGE.md,
 *                                                 # print ws-wrm: OK / FAIL
 *   node tests/scripts/ws-wrm.cjs --report-only   # the same, but exit 0 while steps are still gaps
 *                                                 # (a broken map or database still exits 1)
 *   node tests/scripts/ws-wrm.cjs --check         # validate only, write nothing
 *   node tests/scripts/ws-wrm.cjs --write-db      # regenerate js/modules/wrm-db.js from
 *                                                 # data/curriculum/wrm-steps.json (then validate)
 *
 * The inventory is data/curriculum/wrm-steps.json (every WRM year -> block -> small step with its
 * v3 CCSS codes and Essential Elements; rebuilt from the school site by ws-wrm-extract.cjs). The
 * browser reads a compact copy, js/modules/wrm-db.js, which this script generates and checks is in
 * sync. The map is SKILL_WRM in js/modules/wrm.js; the build list for the gaps is WRM_PROPOSALS.
 *
 * THE GATE FAILS TODAY, by design: many small steps have no skill yet (the owner's rule: "a coverage
 * check that fails while any small step has no skill, the same way the standards check works").
 * Use --report-only until the gaps in design/WRM_COVERAGE.md are built. Do NOT add this script to
 * any "every gate must pass" list before then.
 *
 * Failures:
 *   coverage   (suppressed by --report-only) a small step no skill fully teaches;
 *   structure  (always) wrm-db.js out of date; a duplicate or malformed step id; a CCSS or EE code
 *              not in data/standards; a SKILL_WRM key that is not a live, non-pool skill; a step id
 *              that does not exist; a step listed twice for one skill; a partial with no text; a
 *              step that is not covered and has no proposal; a proposal that lists a covered step
 *              under `steps` (move it to `improves`), names an unknown step, or proposes an id that
 *              is already a live skill.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');

const ROOT = path.resolve(__dirname, '..', '..');
const STEPS_JSON = path.join(ROOT, 'data', 'curriculum', 'wrm-steps.json');
const DB_JS = path.join(ROOT, 'js', 'modules', 'wrm-db.js');
const REPORT = path.join(ROOT, 'design', 'WRM_COVERAGE.md');
const args = process.argv.slice(2);
const WRITE_DB = args.includes('--write-db');
const REPORT_ONLY = args.includes('--report-only');
const CHECK = args.includes('--check');

const structural = [];
const fail = (m) => structural.push(m);
const pct = (n, d) => (d ? `${Math.round((100 * n) / d)}%` : '-');

/* ------------------------------------------------------------ wrm-db.js */
function dbSource(inv) {
    const years = inv.years.map((y) => ({ id: y.id, name: y.name, usGrade: y.usGrade, schoolGrade: y.schoolGrade }));
    const blocks = [];
    const steps = [];
    for (const y of inv.years) {
        for (const b of y.blocks) {
            blocks.push({ id: b.id, term: b.term, termBlock: b.termBlock, name: b.name });
            for (const s of b.steps) {
                const r = { id: s.id, title: s.title, ccss: s.ccss, ee: s.ee, flag: s.flag };
                if (s.power) r.power = true;
                if (s.siteTitle) r.siteTitle = s.siteTitle;
                steps.push(r);
            }
        }
    }
    const j = (v) => JSON.stringify(v);
    const lines = (arr) => `[\n${arr.map((x) => `    ${j(x)},`).join('\n')}\n]`;
    return `// wrm-db.js — GENERATED by \`node tests/scripts/ws-wrm.cjs --write-db\` from
// data/curriculum/wrm-steps.json. Do not edit by hand: edit the JSON (or rebuild it from the school
// site with tests/scripts/ws-wrm-extract.cjs) and regenerate. The JSON holds the full records
// (Drive file ids, v3 notes, Awsaj supplement lessons); this is the compact copy the browser reads.

export const WRM_YEARS = ${lines(years)};

export const WRM_BLOCKS = ${lines(blocks)};

export const WRM_STEPS = ${lines(steps)};
`;
}

/* ------------------------------------------------------------ inventory checks */
function checkInventory(inv, ccCodes, eeCodes) {
    const ids = new Set();
    let n = 0, nb = 0;
    for (const y of inv.years) {
        for (const b of y.blocks) {
            nb += 1;
            if (!/^(R|Y[1-6])\.B\d{1,2}$/.test(b.id)) fail(`inventory: malformed block id ${b.id}`);
            for (const s of b.steps) {
                n += 1;
                if (!/^(R|Y[1-6])\.B\d{1,2}\.S\d{1,2}$/.test(s.id)) fail(`inventory: malformed step id ${s.id}`);
                if (!s.id.startsWith(`${b.id}.`)) fail(`inventory: ${s.id} sits in block ${b.id}`);
                if (ids.has(s.id)) fail(`inventory: duplicate step id ${s.id}`);
                ids.add(s.id);
                if (!s.title) fail(`inventory: ${s.id} has no title`);
                for (const c of s.ccss) if (!ccCodes.has(c)) fail(`inventory: ${s.id} names ${c}, which is not in ccss-math.json`);
                for (const c of s.ee) if (!eeCodes.has(c)) fail(`inventory: ${s.id} names ${c}, which is not in ee-math.json`);
            }
            for (const p of b.supplements || []) for (const c of p.ccss) if (!ccCodes.has(c)) fail(`inventory: supplement "${p.title}" names ${c}, which is not in ccss-math.json`);
        }
    }
    if (n !== inv.meta.counts.steps || nb !== inv.meta.counts.blocks) fail(`inventory: ${nb} blocks / ${n} steps, meta says ${inv.meta.counts.blocks} / ${inv.meta.counts.steps}`);
    return ids;
}

/* ------------------------------------------------------------ report */
function writeReport(ctx) {
    const { inv, cov, props, label, ccRecs, eeRecs, std } = ctx;
    const out = [];
    const L = (s = '') => out.push(s);
    const sk = (k) => `${label(k)} (\`${k}\`)`;
    const S = cov.summary;
    const stepMap = new Map(cov.steps.map((s) => [s.id, s]));
    L('# White Rose Maths coverage');
    L();
    L('Generated by `node tests/scripts/ws-wrm.cjs`. Do not edit by hand: change the map (`SKILL_WRM`) or the');
    L('build list (`WRM_PROPOSALS`) in `js/modules/wrm.js`, or the inventory in `data/curriculum/wrm-steps.json`');
    L('(rebuilt from the school site by `tests/scripts/ws-wrm-extract.cjs`), then regenerate.');
    L();
    L('A small step is **covered** when at least one live skill teaches it fully: its key idea, task and');
    L('vocabulary at the step\'s level, possibly with option values (shown in braces). **Partial** means skills');
    L('teach only part of it; the text says what is missing, and a partial never counts. A **gap** has no skill.');
    L('Every step that is not covered names a proposal from the build list below.');
    L();
    L(`Grade rule: ${inv.meta.gradeRule}`);
    L();
    L(`Step ids: ${inv.meta.idFormat}`);
    L();
    L('Sources:');
    for (const s of inv.meta.sources) L(`- ${s}`);
    L();
    L('## Summary');
    L();
    L(`- ${inv.meta.counts.years} years, ${inv.meta.counts.blocks} blocks, ${inv.meta.counts.steps} small steps (Taskmaster and Year 6 Projects folders hold no small steps and are not counted).`);
    L(`- Covered ${S.covered} (${pct(S.covered, S.total)}), partial only ${S.partial} (${pct(S.partial, S.total)}), gap ${S.gap} (${pct(S.gap, S.total)}).`);
    L(`- ${Object.keys(ctx.map).length} skills carry WRM tags. ${Object.keys(props).length} proposals (${Object.values(props).filter((p) => p.kind === 'new').length} new skills, ${Object.values(props).filter((p) => p.kind === 'option').length} options on existing skills) would close every gap.`);
    L();
    L('| Year | US grade | Blocks | Steps | Covered | Partial only | Gap |');
    L('|---|---|---|---|---|---|---|');
    for (const y of inv.years) {
        const t = S.byYear[y.id] || { total: 0, covered: 0, partial: 0, gap: 0 };
        L(`| ${y.name} | ${y.usGrade} | ${y.blocks.length} | ${t.total} | ${t.covered} (${pct(t.covered, t.total)}) | ${t.partial} | ${t.gap} |`);
    }
    L(`| **All** | | **${inv.meta.counts.blocks}** | **${S.total}** | **${S.covered} (${pct(S.covered, S.total)})** | **${S.partial}** | **${S.gap}** |`);
    L();
    L('## Source disagreements');
    L();
    L('Where the Drive folders, the site pacing, the v3 crosswalk and our standards database disagree');
    L('(recorded by the extractor in `meta.disagreements`, plus the reconciliation notes in the JSON):');
    L();
    for (const d of inv.meta.disagreements) L(`- ${d}`);
    for (const d of inv.meta.reconciliation || []) L(`- ${d}`);
    L();
    L('## GAP LIST: the build list, by family');
    L();
    L('Every proposal below closes the steps listed under "Closes" (steps with no full-coverage skill today).');
    L('"Strengthens" lists covered steps the proposal would also serve. An option proposal extends an');
    L('existing skill instead of adding a new id ("a ladder step is a skill plus option values").');
    L();
    const fams = [...new Set(Object.values(props).map((p) => p.family))].sort();
    for (const f of fams) {
        const list = Object.entries(props).filter(([, p]) => p.family === f && p.steps.length).sort((a, b) => b[1].steps.length - a[1].steps.length);
        if (!list.length) continue;
        const n = list.reduce((a, [, p]) => a + p.steps.length, 0);
        L(`### ${f} (${list.length} proposals, ${n} steps)`);
        L();
        for (const [id, p] of list) {
            const what = p.kind === 'new' ? `new skill \`${p.skill}\`` : `option on \`${p.skill}\`: ${p.option}`;
            L(`- **${p.name}** — ${what}. Teaches ${p.teaches}. Representation: ${p.representation}.  `);
            L(`  Closes (${p.steps.length}): ${p.steps.map((s) => `${s} ${(stepMap.get(s) || {}).title || ''}`).join('; ')}${p.improves && p.improves.length ? `  \n  Strengthens: ${p.improves.join(', ')}` : ''}  `);
            L(`  _proposal id: ${id}_`);
        }
        L();
    }
    // standards in WRM with no skill
    const wrmCodes = new Map();
    const note = (c, where) => { if (!wrmCodes.has(c)) wrmCodes.set(c, []); wrmCodes.get(c).push(where); };
    for (const y of inv.years) for (const b of y.blocks) {
        for (const s of b.steps) { for (const c of s.ccss) note(c, s.id); for (const c of s.ee) note(c, s.id); }
        for (const p of b.supplements || []) { for (const c of p.ccss) note(c, `${b.id} supplement "${p.title}"`); for (const c of p.ee || []) note(c, `${b.id} supplement "${p.title}"`); }
    }
    L('## Standards that WRM teaches and no skill covers');
    L();
    L('Every CCSS code and Wisconsin Essential Element named by a WRM step (or an Awsaj supplement lesson) that');
    L('no live skill covers in `js/modules/standards.js` (approximate mappings do not count). These need a skill');
    L('whatever happens to the WRM gaps.');
    L();
    const uncoveredC = [...wrmCodes.keys()].filter((c) => !c.startsWith('M.EE') && ccRecs.has(c) && !ccRecs.get(c).covered).sort();
    const uncoveredE = [...wrmCodes.keys()].filter((c) => c.startsWith('M.EE') && eeRecs.has(c) && !eeRecs.get(c).covered).sort();
    if (!uncoveredC.length && !uncoveredE.length) L('None: every standard WRM names has at least one skill.');
    for (const c of uncoveredC) L(`- **${c}** ${ccRecs.get(c).text}  \n  WRM: ${wrmCodes.get(c).slice(0, 12).join(', ')}${wrmCodes.get(c).length > 12 ? ' ...' : ''}`);
    for (const c of uncoveredE) L(`- **${c}** ${eeRecs.get(c).text}  \n  WRM: ${wrmCodes.get(c).slice(0, 12).join(', ')}${wrmCodes.get(c).length > 12 ? ' ...' : ''}`);
    L();
    L('## Year by year, step by step');
    L();
    for (const y of inv.years) {
        L(`### ${y.name} (US ${y.usGrade === 'PK' ? 'PK4' : `grade ${y.usGrade}`})`);
        L();
        for (const b of y.blocks) {
            L(`#### ${b.id} ${b.term} Block ${b.termBlock}: ${b.name}`);
            L();
            for (const s0 of b.steps) {
                const s = stepMap.get(s0.id);
                const mark = s.status === 'covered' ? 'covered' : s.status === 'partial' ? 'PARTIAL' : 'GAP';
                const codes = [...s0.ccss, ...s0.ee].join(', ') || 'Beyond CCSS';
                L(`- **${s.id}** ${s0.title}${s0.siteTitle ? ` (site: ${s0.siteTitle})` : ''} — ${mark}. _${codes}_  `);
                const full = (ctx.rev.get(s.id) || []).filter((h) => !h.partial);
                if (full.length) L(`  Skills: ${full.map((h) => `${sk(h.key)}${h.note ? ` {${h.note}}` : ''}`).join('; ')}  `);
                for (const p of s.partials) L(`  Partial: ${sk(p.key)}, missing ${p.missing}  `);
                if (s.proposals.length) L(`  Proposal: ${s.proposals.map((id) => props[id].name).join('; ')}  `);
            }
            for (const p of b.supplements || []) {
                const cov2 = p.ccss.map((c) => `${c}${ccRecs.has(c) && ccRecs.get(c).covered ? '' : ' (no skill)'}`).join(', ');
                L(`- _Awsaj supplement (not a WRM step):_ ${p.title} — ${cov2}`);
            }
            L();
        }
    }
    fs.writeFileSync(REPORT, `${out.join('\n')}\n`);
}

/* ------------------------------------------------------------ main */
(async () => {
    let inv, cc, ee;
    try {
        inv = JSON.parse(fs.readFileSync(STEPS_JSON, 'utf8'));
        cc = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/standards/ccss-math.json'), 'utf8'));
        ee = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/standards/ee-math.json'), 'utf8'));
    } catch (e) {
        console.log(`ws-wrm: FAIL\n  cannot read the inventory or the standards database: ${e.message}`); process.exit(1);
    }
    const ccCodes = new Set(cc.standards.map((s) => s.code));
    const eeCodes = new Set(ee.essentialElements.flatMap((e) => [e.code, ...(e.subs || []).map((x) => x.code)]));
    const stepIds = checkInventory(inv, ccCodes, eeCodes);
    const src = dbSource(inv);
    if (WRITE_DB) { fs.writeFileSync(DB_JS, src); console.log(`wrote ${path.relative(ROOT, DB_JS)}`); }
    else if (!fs.existsSync(DB_JS) || fs.readFileSync(DB_JS, 'utf8') !== src) fail('js/modules/wrm-db.js is out of date: run `node tests/scripts/ws-wrm.cjs --write-db`');

    // Node has no localStorage; data.js reads it at load.
    const mem = {};
    globalThis.localStorage = { getItem: (k) => (k in mem ? mem[k] : null), setItem: (k, v) => { mem[k] = String(v); }, removeItem: (k) => { delete mem[k]; } };
    const origLog = console.log;
    console.log = () => {};
    let data, std, wrm;
    try {
        data = await import(pathToFileURL(path.join(ROOT, 'js/modules/data.js')).href);
        std = await import(pathToFileURL(path.join(ROOT, 'js/modules/standards.js')).href);
        wrm = await import(pathToFileURL(path.join(ROOT, 'js/modules/wrm.js')).href);
    } catch (e) {
        console.log = origLog;
        console.log(`ws-wrm: FAIL\n  cannot load the modules: ${e.message}`); process.exit(1);
    } finally { console.log = origLog; }

    const live = new Map();
    for (const [cat, list] of Object.entries(data.SKILLS)) {
        if (!Array.isArray(list)) continue;
        for (const s of list) if (!s.retired) live.set(`${cat}:${s.v}`, s.l);
    }
    const map = wrm.SKILL_WRM;
    const props = wrm.WRM_PROPOSALS;
    for (const [key, list] of Object.entries(map)) {
        if (!live.has(key)) { fail(`map: ${key} is not a live skill`); continue; }
        const se = std.SKILL_STANDARDS[key];
        if (se && se.pool) fail(`map: ${key} is a mixed pool; tag the skills it draws from instead`);
        if (!Array.isArray(list) || !list.length) { fail(`map: ${key} needs a non-empty list of steps`); continue; }
        const seen = new Set();
        for (const e of list) {
            const id = typeof e === 'string' ? e : e && e.step;
            if (!stepIds.has(id)) fail(`map: ${key} names ${id}, which is not a WRM small step`);
            if (seen.has(id)) fail(`map: ${key} lists ${id} twice`);
            seen.add(id);
            if (typeof e === 'object' && e) {
                if ('partial' in e && !(typeof e.partial === 'string' && e.partial.trim())) fail(`map: ${key} ${id} is partial with no text`);
                if ('note' in e && !(typeof e.note === 'string' && e.note.trim())) fail(`map: ${key} ${id} has an empty note`);
                if (!('partial' in e) && !('note' in e)) fail(`map: ${key} ${id} is an object with neither note nor partial`);
            }
        }
    }
    const cov = wrm.wrmCoverage();
    if (cov.steps.length !== stepIds.size) fail(`wrm-db.js has ${cov.steps.length} steps, the inventory ${stepIds.size}`);
    const proposed = new Set(Object.values(props).map((p) => p.skill));
    const status = new Map(cov.steps.map((s) => [s.id, s.status]));
    for (const [id, p] of Object.entries(props)) {
        for (const f of ['kind', 'skill', 'name', 'teaches', 'representation', 'family']) if (!p[f]) fail(`proposal ${id}: missing ${f}`);
        if (!['new', 'option'].includes(p.kind)) fail(`proposal ${id}: kind must be 'new' or 'option'`);
        if (p.kind === 'new' && live.has(p.skill)) fail(`proposal ${id}: ${p.skill} is already a live skill (tag it, or make this an option)`);
        if (p.kind === 'option' && !live.has(p.skill) && !proposed.has(p.skill)) fail(`proposal ${id}: option on ${p.skill}, which is neither a live skill nor a proposal`);
        if (p.kind === 'option' && !p.option) fail(`proposal ${id}: an option proposal needs its option text`);
        if (!Array.isArray(p.steps)) { fail(`proposal ${id}: steps must be a list`); continue; }
        if (!p.steps.length && !(p.improves || []).length) fail(`proposal ${id}: closes and strengthens nothing (delete it)`);
        for (const s of p.steps) {
            if (!stepIds.has(s)) fail(`proposal ${id}: unknown step ${s}`);
            else if (status.get(s) === 'covered') fail(`proposal ${id}: ${s} is covered now; move it to improves or drop it`);
        }
        for (const s of p.improves || []) if (!stepIds.has(s)) fail(`proposal ${id}: unknown step ${s} in improves`);
    }
    const gaps = [];
    for (const s of cov.steps) {
        if (s.status === 'covered') continue;
        gaps.push(s);
        if (!Object.values(props).some((p) => p.steps.includes(s.id))) fail(`step ${s.id} "${s.title}" is ${s.status} and no proposal closes it`);
    }
    // lookup helpers agree with the map
    const probe = Object.entries(map)[0];
    if (probe) {
        const [k, list] = probe;
        const [c, v] = k.split(':');
        if (wrm.wrmFor(c, v).length !== list.length) fail(`wrmFor(${k}) disagrees with SKILL_WRM`);
    }
    const covered = cov.steps.find((s) => s.status === 'covered');
    if (covered && !wrm.skillsForWrmStep(covered.id).length) fail(`skillsForWrmStep(${covered.id}) is empty for a covered step`);

    const rev = new Map();
    for (const [key, list] of Object.entries(map)) for (const e of list) {
        const id = typeof e === 'string' ? e : e.step;
        if (!rev.has(id)) rev.set(id, []);
        rev.get(id).push({ key, partial: (typeof e === 'object' && e.partial) || '', note: (typeof e === 'object' && e.note) || '' });
    }
    const scov = std.coverage();
    const ccRecs = new Map(scov.ccss.map((r) => [r.code, r]));
    const eeRecs = new Map(scov.ee.map((r) => [r.code, r]));
    for (const e of ee.essentialElements) for (const x of e.subs || []) if (!eeRecs.has(x.code) && eeRecs.has(e.code)) eeRecs.set(x.code, eeRecs.get(e.code));

    if (!structural.length && !CHECK) {
        writeReport({ inv, cov, props, map, rev, std, ccRecs, eeRecs, label: (k) => live.get(k) || k });
        console.log(`wrote ${path.relative(ROOT, REPORT)}`);
    }
    const S = cov.summary;
    console.log(`wrm: ${inv.meta.counts.years} years, ${inv.meta.counts.blocks} blocks, ${S.total} small steps; ${Object.keys(map).length} skills tagged; ${Object.keys(props).length} proposals`);
    console.log(`coverage: covered ${S.covered}/${S.total} (${pct(S.covered, S.total)}), partial only ${S.partial}, gap ${S.gap}`);
    console.log(`  by year: ${inv.years.map((y) => `${y.id} ${pct((S.byYear[y.id] || {}).covered, (S.byYear[y.id] || {}).total)}`).join('  ')}`);
    if (structural.length) {
        console.log('ws-wrm: FAIL');
        for (const f of structural.slice(0, 40)) console.log(`  ${f}`);
        if (structural.length > 40) console.log(`  ... and ${structural.length - 40} more`);
        process.exit(1);
    }
    if (gaps.length) {
        console.log(`ws-wrm: FAIL${REPORT_ONLY ? ' (report only: exit 0)' : ''}`);
        console.log(`  ${gaps.length} small steps have no full-coverage skill (${S.partial} partial, ${S.gap} gap); the build list is in design/WRM_COVERAGE.md`);
        for (const s of gaps.slice(0, 10)) console.log(`  ${s.id} ${s.title}: ${s.status}`);
        if (gaps.length > 10) console.log(`  ... and ${gaps.length - 10} more`);
        process.exit(REPORT_ONLY ? 0 : 1);
    }
    console.log('ws-wrm: OK');
})();
